% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  10pt,
  a4paper,
]{scrbook}
\usepackage{xcolor}
\usepackage[left=2.54cm,right=2.54cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{2}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


% Palatino font:
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{palatino}

\usepackage{ragged2e}

%\usepackage{mathpazo}
\usepackage{newpxtext}
\usepackage{newpxmath}

\usepackage{upquote}

% front page
\usepackage[colorlinks]{hyperref} % for text color on title
\usepackage{titling} % makes \thetitle etc available...
\usepackage{lipsum}
\usepackage{tikz}
\tikzstyle{bag} = [align=center] % allows new lines in text below
\AtBeginDocument{\thispagestyle{empty}
\definecolor{titlecolor}{HTML}{1C2404}
\begin{tikzpicture}[remember picture,overlay]
\draw (current page.center) node[inner sep=0] {\resizebox{!}{350mm}{\includegraphics{highres_banner.pdf}}};
\draw (current page.center) node[inner sep=0, opacity=0.5] {\resizebox{!}{100mm}{\includegraphics{ausegl_sort.pdf}}};
% \draw (current page.center) node[bag] {  
        \draw (17, 1.7) node[bag, align=right, anchor=north east] {  
    % \mytitlefont 
    \color{titlecolor} \Large \textbf{Thesis} \\ 
    \\ 
    % \mytitlefont 
    \color{titlecolor} \Huge \textbf{\thetitle} \\ 
    \\ 
    % \mytitlefont
    \color{titlecolor} \huge \theauthor \\
    \\
    % \mytitlefont 
    \color{titlecolor} \Large \thedate 
    };
\end{tikzpicture}
\clearpage}

% back side
\AtEndDocument{\clearpage\thispagestyle{empty}
\begin{tikzpicture}[remember picture,overlay]
\draw (current page.center) node[inner sep=0] {\resizebox{!}{350mm}{\includegraphics{highres_banner.pdf}}};
% \draw (current page.center) node[bag] {  
    \draw (17, 1.7) node[bag, align=right, anchor=north east] {  
        % \mytitlefont 
        \color{titlecolor} \large Bioinformatics Research Centre \\ 
        % \mytitlefont 
        \color{titlecolor} \large Department of Molecular Biology and Genetics \\ 
        % \mytitlefont 
        \color{titlecolor} \large Aarhus University \\
        % \mytitlefont 
        \color{titlecolor} \large Universitetsbyen 81 \\
        % \mytitlefont 
        \color{titlecolor} \large 8000 Aarhus C \\
        % \mytitlefont 
        \color{titlecolor} \large Denmark
        };

\end{tikzpicture}}


% % picture (AU logo in title page)
% \usepackage{titlepic}
% % \usepackage{graphicx}
% \titlepic{\resizebox{!}{50mm}{\includegraphics[width=\textwidth]{ausegl_sort.pdf}}}



% \pagestyle{plain} % no running header

\usepackage[many]{tcolorbox}
\definecolor{quotegray}{HTML}{505050}
\newtcolorbox{myquote}{%
    enhanced jigsaw, 
    breakable,      % allow page breaks
    frame hidden,   % hide the default frame
    left=1cm,       % left margin
    right=1cm,      % right margin
    colback=white,
    fontupper=\color{quotegray},
    overlay={%
        \node [scale=4,
            text=lightgray,
            inner sep=0pt,] at ([xshift=0.5cm,yshift=-0.7cm]frame.north west){``}; 
        \node [scale=4,
            text=lightgray,
            inner sep=0pt,] at ([xshift=-0.5cm]frame.south east){''};  
            },
        % paragraph skips obeyed within tcolorbox
                parbox=false,
}
% redefine the 'quote' environment to use this 'myquote' environment
\renewenvironment{quote}{\begin{myquote}}{\end{myquote}}

% add a dummy abstract environment that is defined in quarto manuscript 
% but not in the quarto book that we run first to give it a slot in the 
% side bar
\ifcsmacro{abstract}{}{
  \let\endmyenvironment\undefined%
  \newenvironment{abstract}{\chapter*{Abstract}}{}
}

% \usepackage{framed} % not sure i need this anymore

% \usepackage[T1]{fontenc}
% \usepackage{inconsolata}

% % I have to only define Shaded if it is already defined.
% % The reason is that pandoc does not define the macro if there are not code blocks in the a markdown file.
% \ifx \@Shaded \@empty

% \renewcommand{\KeywordTok}[1]{\textcolor[rgb]{0, 0, 0}{\textbf{{#1}}}} % def and or not reg
% \renewcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.373, 0.298, 0.580}{\textbf{{#1}}}} % print open 
% \renewcommand{\VariableTok}[1]{\textcolor[rgb]{0.141, 0.392, 0.824}{\textbf{{#1}}}}
% \renewcommand{\OperatorTok}[1]{\textcolor[rgb]{0, 0, 0}{{#1}}} % def and or not reg
% \renewcommand{\DataTypeTok}[1]{\textcolor[rgb]{1.0,0.13,0.00}{{#1}}}
% \renewcommand{\DecValTok}[1]{\textcolor[rgb]{0.655, 0.498, 0.161}{{#1}}}
% \renewcommand{\BaseNTok}[1]{\textcolor[rgb]{0.259, 0.592, 0.596}{{#1}}}
% \renewcommand{\FloatTok}[1]{\textcolor[rgb]{0.655, 0.498, 0.161}{{#1}}}
% \renewcommand{\CharTok}[1]{\textcolor[rgb]{0.678,0.141,0.098}{{#1}}}
% \renewcommand{\StringTok}[1]{\textcolor[rgb]{0.678,0.141,0.098}{{#1}}}
% \renewcommand{\CommentTok}[1]{\textcolor[rgb]{0.135, 0.134, 0.133}{{#1}}}
% \renewcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{{#1}}}
% \renewcommand{\AlertTok}[1]{\textcolor[rgb]{1.00,0.00,0.00}{\textbf{{#1}}}}
% \renewcommand{\FunctionTok}[1]{\textcolor[rgb]{0.549, 0.102, 0.063}{\textbf{{#1}}}}  % function name
% \renewcommand{\RegionMarkerTok}[1]{{#1}}
% \renewcommand{\ErrorTok}[1]{\textcolor[rgb]{1.00,0.00,0.00}{\textbf{{#1}}}}
% \renewcommand{\NormalTok}[1]{\textcolor[rgb]{0, 0, 0}{{#1}}}


% \else
%   % no code blocks with markup...
% \fi

\usepackage{etoolbox}
\makeatletter
\g@addto@macro{\appendix}{%
  \patchcmd{\@@makechapterhead}% <cmd>
    {\endgraf\nobreak\vskip.5\baselineskip}% <search>
    {\hspace*{-.5em}:\space}% <replace>
    {}{}% <success><failure>
  \patchcmd{\@chapter}% <cmd>
    {\addchaptertocentry{\thechapter}}% <search>
    {\addchaptertocentry{Appendix~\thechapter:}}% <replace>
    {}{}% <success><failure>
  \addtocontents{toc}{%
    \protect\patchcmd{\protect\l@chapter}% <cmd>
      {1.5em}% <search>
      {6.5em}% <replace>
      {}{}}% <success><failure>
}
\renewcommand{\autodot}{}% Remove all end-of-counter dots
\makeatother


% restart chapter numbers in each part
\makeatletter
\@addtoreset{chapter}{part}
\makeatother


% \usepackage{chngcntr}
% \counterwithin*{subsubsection}{chapter}
% \counterwithout*{subsubsection}{section}
% \counterwithout*{subsubsection}{subsection}

% %  % KMT only use subsubsection number (this increments though the book 
% %  % when we supress numbering with  {.unnumbered} after each header except Exerisices
% \renewcommand\thesubsubsection{\arabic{section}}
% \renewcommand\thesubsubsection{\arabic{subsection}}
% \renewcommand\thesubsubsection{\arabic{chapter}-\arabic{subsubsection}}


\renewcommand*{\chapterformat}{%
\textcolor[rgb]{0.7, 0.7, 0.7}{\thechapter}\autodot\enskip%
}
\renewcommand*{\sectionformat}{%
\textcolor[rgb]{0.7, 0.7, 0.7}{\thesection}\autodot\enskip%
}
\renewcommand*{\subsectionformat}{%
\textcolor[rgb]{0.7, 0.7, 0.7}{\thesubsection}\autodot\enskip%
}
\renewcommand*{\subsubsectionformat}{%
\textcolor[rgb]{0.7, 0.7, 0.7}{\thesubsubsection}\autodot\enskip%
}



% % prevent latex from "floating" the figures
% \usepackage{float}
% \let\origfigure\figure
% \let\endorigfigure\endfigure
% \renewenvironment{figure}[1][2] {
%     \expandafter\origfigure\expandafter[H]
% } {
%     \endorigfigure
% }

\usepackage{xcolor}
\let\oldemph\emph
\renewcommand\emph[1]{\oldemph{\color{gray}#1}} % delete this line to make italics black again.



% \usepackage{parskip}
% \newlength{\currentparskip}
% \newenvironment{tableminipage}
%   {\setlength{\currentparskip}{\parskip}% save the value
%    \begin{minipage}{\textwidth}% open the minipage
%    \setlength{\parskip}{\currentparskip}% restore the value
%   }
%   {\end{minipage}}

% \usepackage{etoolbox}
% \AtBeginEnvironment{table}{\begin{tableminipage}}
% \AtEndEnvironment{table}{\end{tableminipage}}
% % \AtBeginEnvironment{tabular}{\tiny}

% \let\oldtabular\tabular
% \let\endoldtabular\endtabular
% \renewenvironment{tabular}{\bgroup\footnotesize\oldtabular}%
%                           {\endoldtabular\egroup}

% \let\oldlongtable\longtable
% \let\endoldlongtable\endlongtable
% \renewenvironment{longtable}{\footnotesize\oldlongtable}{\endoldlongtable} 

% \makeatletter
% \renewenvironment{table}{%
%   \if@tablecaptionabove\let\caption\captionabove
%   \else\let\caption\captionbelow\fi
%   \small\@float{table}%
% }{%
%   \end@float
% }
% \makeatother

% \usepackage{longtable}
% \makeatletter
% \renewenvironment{longtable}{%
%   \if@tablecaptionabove\let\caption\captionabove
%   \else\let\caption\captionbelow\fi
%   \small\@float{longtable}%
% }{%
%   \end@float
% }
% \makeatother



% \usepackage[font={footnotesize},labelfont={bf}]{caption}
% \AddToHook{env/longtable/before}{\fontsize{8}{10}\selectfont}
% \AddToHook{env/longtable/after}{\normalsize}
% \AddToHook{env/table/before}{\fontsize{8}{10}\selectfont}
% \AddToHook{env/table/after}{\normalsize}




%\captionsetup[table]{labelformat={empty}

% \let\oldlongtable\longtable
% \def\longtable{%
% \footnotesize
% \oldlongtable}


% \usepackage{longtable}
% \usepackage{caption}
% \captionsetup[table]{font={tiny}}

% \AddToHook{env/longtable/before}{\footnotesize}
% \AddToHook{env/longtable/after}{\normalsize}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% %% from arcxiv.sty:  %%%
\RedeclareSectionCommand[
  beforeskip=-2ex,
  afterskip=1.5ex
]{chapter}

\RedeclareSectionCommand[
  beforeskip=-1.8ex,
  afterskip=0.8ex
]{section}

\RedeclareSectionCommand[
  beforeskip=--1.5ex,
  afterskip=0.5ex
]{subsection}

\RedeclareSectionCommand[
  beforeskip=1.5ex,
  afterskip=-1em
]{subsubsection}

\RedeclareSectionCommand[
  beforeskip=1.5ex,
  afterskip=-1em
]{paragraph}

% \RedeclareSectionCommand[
%   beforeskip=1.5ex plus 0.5ex minus 0.2ex,
%   afterskip=-1em
% ]{subparagraph}


% \setkomafont{section}{\normalfont\Large\bfseries\raggedright}
% \setkomafont{subsection}{\normalfont\large\bfseries\raggedright}
% \setkomafont{subsubsection}{\normalfont\normalsize\bfseries\raggedright}
% \setkomafont{paragraph}{\normalfont\normalsize\bfseries}
% \setkomafont{subparagraph}{\normalfont\normalsize\bfseries}

% \setkomafont{caption}{\small}
% \setkomafont{captionlabel}{\bfseries\sffamily}

%% Tables
% \usepackage[style=plaintop]{floatrow}
% \floatsetup[table]{capposition=top}
% \floatsetup[figure]{capposition=bottom}
% \floatsetup[table]{font=small}
% \usepackage{booktabs} % professional-quality tables (arxiv.sty)

\usepackage[font={footnotesize},labelfont={bf}]{caption}
\AddToHook{env/longtable/before}{\fontsize{8}{10}\selectfont}
\AddToHook{env/longtable/after}{\normalsize}
\AddToHook{env/table/before}{\fontsize{8}{10}\selectfont}
\AddToHook{env/table/after}{\normalsize}
\AddToHook{env/codelisting/before}{\fontsize{8}{10}\selectfont}
\AddToHook{env/codelisting/after}{\normalsize}

% \AddToHook{cmd/subcaption/before}{\vspace{-3mm}}
%\AddToHook{cmd/subcaption/after}{\vspace{-2cm}}


% \captionsetup[longtable]{font={footnotesize},labelfont={footnotesize}, position={top}, labelfont={bf}}
\captionsetup[sub]{font=footnotesize,labelfont=footnotesize, position=top}
\captionsetup[codelisting]{font=footnotesize, labelfont=bf}
% \captionsetup[subtable]{font=scriptsize,labelfont=scriptsize, position=top}

%\captionsetup[subfigure]{margin=150pt}

% \setlength\LTleft{0pt}
% \setlength\LTright{0pt}
% \begin{longtable}{@{\extracolsep{...}}...}

%\AddToHook{phantomsection/before}{\normalsize}
\AddToHook{phantomsection/after}{\normalsize}


%%% For code blocks using the Shaded environment
% \AddToHook{env/Shaded/before}{\vspace{-0.5em}\small} % Reduces space before
% \AddToHook{env/Shaded/after}{\vspace{-1em}} % Reduces space after
\usepackage{framed}
\definecolor{shadecolor}{RGB}{245,245,245}

\ifcsmacro{Shaded}{%
  \renewenvironment{Shaded}
  {
    \vspace{-0.5em} % Add spacing before
    \begin{snugshade} % Begin shaded block
    \small % Smaller font
  }
  {
    \end{snugshade} % End shaded block
    \vspace{-1em} % Add spacing after
  }
}{%
  \newenvironment{Shaded}
  {
    \vspace{-0.5em} % Add spacing before
    \begin{snugshade} % Begin shaded block
    \small % Smaller font
  }
  {
    \end{snugshade} % End shaded block
    \vspace{-1em} % Add spacing after
  }
}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Fase-type fordelinger og Bayesiansk inferens i populationsgenetik},
  pdfkeywords={Coalescent theory, Phase-type
distributions, SVGD, Population genetics, Papio},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}


\title{Fase-type fordelinger og Bayesiansk inferens i
populationsgenetik}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Coalescentmodeller for enkelt-populationer, to-ø og
IM-modellen anvendt på Papio spp.}
\author{Emma Christensen \and Kasper Munch \and Kasper Urup Kjeldsen}
\date{June 5, 2026}
\begin{document}
\frontmatter
\cleardoublepage
\thispagestyle{empty}
{\centering
\hbox{}\vskip 0cm plus 1fill

{%\mytitlefont 
\Huge\bfseries Fase-type fordelinger og Bayesiansk inferens i
populationsgenetik \par}
\vspace{3ex}
{\Large\bfseries Coalescentmodeller for enkelt-populationer, to-ø og
IM-modellen anvendt på Papio spp. \par}
\vspace{6ex}

    {\Large\bfseries Emma Christensen \par}
    %
        %
        {\bfseries\large Aarhus University \par}
    %
    {\Large\bfseries Kasper Munch \par}
    %
        %
        {\bfseries\large Molecular Biology and Genetics \par}
        \vspace{3ex}
        %
        {\bfseries\large Aarhus University, Denmark \par}
    %
    {\Large\bfseries Kasper Urup Kjeldsen \par}
    %
        %
        {\bfseries\large Biology \par}
        \vspace{3ex}
        %
        {\bfseries\large Aarhus University, Denmark \par}
    %
%
\vskip 0cm plus 2fill

{\resizebox{!}{50mm}{\includegraphics[width=\textwidth]{ausegl_sort.pdf}} \par}
\vskip 0cm plus 2fill

{\bfseries\Large\textit{Master of Science in Bioinformatics} \par}
\vspace{3ex}

{\bfseries\large June 5, 2026 \par}
\vspace{3ex}

\vspace{12ex}
{\small Submitted in fulfillment of the requirements
of the degree of Master of Science in Bioinformatics \par}
\pagebreak

\begin{quote}
\raggedright    
\begin{itemize}
\tightlist
\item
\end{itemize} \par
\raggedleft    
    {- Emma Christensen \par}
    {- Kasper Munch \par}
    {- Kasper Urup Kjeldsen \par}
%    
\end{quote}
}

\renewcommand*\contentsname{Table of contents}
{
\setcounter{tocdepth}{1}
\tableofcontents
}
\listoffigures
\listoftables

\setstretch{1}
\mainmatter
\chapter{Introduktion}\label{introduktion}

Genetisk variation er grundlaget for evolution. Når man sammenligner
DNA-sekvenser fra forskellige individer af samme art, vil man næsten
altid finde små forskelle i deres arvemateriale. På nogle positioner kan
det ene individ eksempelvis have et \(A\) (adenin), mens det andet har
et \(G\) (guanin). Disse forskelle er opstået gennem mutationer, som er
blevet ophobet over mange generationer. Antallet og fordelingen af
mutationerne afhænger af de evolutionære processer, der har formet
populationen: genetisk drift, migration, rekombination og ændringer i
populationsstørrelse (Wakeley 2009). Genetiske data indeholder dermed
information om en populations historie og indenfor populationsgenetik er
det netop denne information man gerne vil, udtrække fra de observerede
sekvenser.

Populationsgenetik beskæftiger sig med sammenhængen mellem genetisk
variation og de processer, der skaber den. Disse processer beskrives ved
fremadrettede modeller, hvor man følger udviklingen af allelfrekvenser
generation for generation. En af de mest klassiske modeller er
Wright-Fisher-modellen, som blev udviklet i begyndelsen af det 20.
århundrede af Sewall Wright og Ronald Fisher (Hobolth et al. 2019,
2018). Selvom sådanne modeller giver en præcis beskrivelse af
evolutionære processer, vil de hurtigt blive matematisk og
beregningsmæssigt komplekse, når man ønsker at analysere genetiske data
fra mange individer.

Coalescent-teorien tilbyder et alternativt perspektiv. I stedet for at
beskrive evolutionen fremad i tid beskriver teorien de genealogiske
relationer mellem de observerede sekvenser baglæns i tid. Teorien blev
introduceret af John Kingman i 1982 (Kingman 1982) og udgør i dag et af
de vigtigste teoretiske fundamenter inden for populationsgenetik
(Wakeley 2009). Udgangspunktet er, at alle individer i en stikprøve
deler fælles forfædre, hvis man går langt nok tilbage i tiden. Når man
følger de genetiske linjer baglæns, vil de gradvist smelte sammen
(coalescere), indtil alle linjer mødes i en fælles forfader.
Tidspunkterne for disse sammenfletninger afhænger af den underliggende
populationshistorie og bærer derfor information om størrelser som
effektiv populationsstørrelse, migrationsrater og historiske
begivenheder. I de senere år er der udviklet en række matematiske
værktøjer, som gør det muligt at analysere coalescent-modeller mere
systematisk og præcist. En udvikling er anvendelsen af fase-type
fordelinger, som oprindeligt blev udviklet inden for anvendt
sandsynlighedsteori til at beskrive absorptionstider i Markov-processer
(Bladt and Nielsen 2017). Da coalescent-processer naturligt kan
beskrives som absorptionsprocesser, viser fase-type teorien sig at være
et værktøj til at udlede fordelinger, momenter og sandsynligheder
analytisk under passende modelkonstruktioner. Teorien giver mulighed for
at håndtere mere komplekse modeller med populationsstruktur, migration,
rekombination og tidsvarierende populationsstørrelser inden for den
samme matematiske ramme, men dette er ikke en automatisk egenskab ved
alle fase-type modeller, men afhænger af, at tilstandsrummet er
konstrueret korrekt (Hobolth et al. 2024).

Disse beregninger kan implementeres i Python-biblioteket
\texttt{phasic}, som gør det muligt at konstruere store tilstandsrum og
beregne fordelinger og momenter direkte ud fra de tilhørende
Markov-kæder. For at kunne anvende modellerne på genetiske data kræves
desuden statistiske metoder til parameterinferens. I dette speciale
anvendes en Bayesiansk tilgang, hvor usikkerhed omkring parametrene
beskrives ved posteriorfordelinger og der benyttes Stein Variational
Gradient Descent (SVGD) (Liu and Wang 2016), som approksimerer
posteriorfordelingen ved hjælp af en samling partikler og giver hurtig
konvergens i modeller med mange parametre. Disse analytiske muligheder
adskiller fase-type tilgangen fra mange eksisterende metoder.
Eksisterende coalescent-baserede analyser bygger ofte på simulation
eller forsimplede summary statistics. Det kan gøre det vanskeligt at
beregne fordelinger, momenter og likelihoods analytisk for mere
komplekse modeller. Fase-type fordelinger giver en mulig løsning, fordi
de gør det muligt at beskrive absorptionstider og akkumulerede
genealogiske størrelser i en fælles Markov-ramme. Det er dog nødvendigt
at undersøge, hvor godt disse metoder fungerer i praksis, hvordan
inferensen kan kalibreres og under hvilke betingelser parametre som
migration og populationsstørrelse faktisk er identificerbare. Dette
speciale bidrager med en systematisk undersøgelse af, hvordan
fase-type-baserede coalescentmodeller kan implementeres, verificeres og
kombineres med Bayesiansk inferens. Først valideres modellerne på
simulerede data med kendte parametre. Derefter undersøges
parameteridentificerbarhed og sensitivitet over for mutationsraten. Til
sidst anvendes metoderne på helgenomsekvenseringsdata fra bavianer
slægten \emph{Papio}. Formålet med dette speciale er at besvare følgende
spørgsmål: Kan \texttt{phasic}-implementeringen af Kingmans coalescent,
to-ø-modellen og IM-modellen verificeres analytisk og giver modellerne
korrekte momenter, tæthedsfunktioner og Site-frekvent-spectrum (SFS)? Er
SVGD-inferens kalibreret korrekt, så \(95\%\)-posteriorintervallet
indeholder den sande parameterværdi i ca. \(95\%\) af gentagelserne?
Hvornår er parametrene for to-ø- og IM-modellen identificerbare i
praksis? Hvad kan modellerne fortælle os om den evolutionære historie
for \emph{Papio}-slægten?

\section{Standard coalescent}\label{standard-coalescent}

Udgangspunktet for coalescent-teorien er, at alle individer i en
population deler fælles forfædre, hvis man går tilstrækkeligt langt
tilbage i tiden. Hvis man har en stikprøve af \(n\) DNA-sekvenser fra
det samme locus, vil alle disse sekvenser være beslægtede. Følger man de
genetiske linjer baglæns gennem generationerne, vil de før eller siden
mødes i fælles forfædre, indtil der kun er en linje tilbage. Det fælles
stamtræ, der beskriver disse slægtskabsrelationer, kaldes en genealogi.
Genealogien kan ikke observeres direkte i DNA-dataene. Det, vi
observerer, er mutationerne langs træets grene. Genealogien fungerer
derfor som en stokastisk variabel, der forbinder evolutionære processer
med de genetiske mønstre, vi ser i dataene (Wakeley 2009). Den seneste
fælles forfader for alle individer i stikprøven kaldes \emph{Most Recent
Common Ancestor} (MRCA). Coalescent-teorien beskriver den tilfældige
proces, hvor de genealogiske linjer gradvist coalescere, når man følger
dem baglæns i tid, indtil de alle mødes i MRCA. Tidspunkterne for disse
coalescent-hændelser bærer information om populationshistorien. I små
populationer vil linjerne typisk mødes hurtigt, mens de i store
populationer kan eksistere side om side i lang tid, før de finder en
fælles forfader. Mutationer udgør forbindelsen mellem genealogien og de
data, vi faktisk observerer. Under infinite-sites-modellen antages
mutationer at være så sjældne, at hver mutation kun opstår en gang i
hele den evolutionære historie (Wakeley 2009). Dermed kan en mutation
knyttes til en bestemt gren i genealogien: alle individer, der
nedstammer fra denne gren, bærer mutationen, mens de øvrige ikke gør.
Antager man desuden selektiv neutralitet, kan genealogien og
mutationsprocessen behandles uafhængigt af hinanden. Man modellerer
først genealogien og placerer derefter mutationer på grenene som en
separat Poisson-proces. En vigtig egenskab ved coalescent-processen er,
at den er en Markovproces. Sandsynligheden for den næste hændelse
afhænger kun af den nuværende tilstand og ikke af hele den tidligere
historie. Formelt skrives dette som \[
P(X_{t+s} = j \mid X_u, \, u \leq t) = P(X_{t+s} = j \mid X_t).
\]

Det eneste, man behøver at vide for at beskrive den videre udvikling af
processen, er derfor, hvor mange linjer der aktuelt er til stede. Den
standard coalescent er en kontinuert-tids approksimation af
Wright-Fisher-modellen, som er den klassiske model for genetisk drift
(Hobolth et al. 2019). I Wright-Fisher-modellen er populationsstørrelsen
\(2N\) konstant fra generation til generation og hvert kromosom vælger
sin forfader tilfældigt blandt de \(2N\) kromosomer i den foregående
generation. Sandsynligheden for, at to tilfældigt valgte kromosomer har
samme forfader i en generation, er derfor \(\frac{1}{2N}\). Kingman
viste, at hvis tid måles i enheder af \(2N\) generationer og hvis man
lader \(N \to \infty\), konvergerer denne diskrete model mod en
kontinuert-tids Markov-kæde (Kingman 1982). Når der er \(k\) linjer til
stede, er ventetiden til næste coalescenthændelse eksponentielt fordelt
med rate \(\frac{k(k-1)}{2}\), fordi der findes præcis \(\binom{k}{2}\)
mulige linjepar og hvert par coalescerer med rate \(1\) (Hobolth et al.
2019): \[
T_k \sim \mathrm{Exp}\!\left(\frac{k(k-1)}{2}\right), \qquad k = n, n-1, \ldots, 2.
\]

Ventetiderne er stokastisk uafhængige, hvilket betyder, at tidspunktet
for den næste coalescenthændelse ikke afhænger af, hvilke linjer der
coalescerede tidligere. Træhøjden \(H = \sum_{k=2}^{n} T_k\) er derfor
summen af disse uafhængige ventetider. Træhøjden beskriver, hvor langt
tilbage i tiden man skal gå for at nå MRCA. Dens forventning og varians
er (Hobolth et al. 2019): \[
\mathbb{E}[H] = \sum_{k=2}^{n} \frac{2}{k(k-1)} = 2\!\left(1 - \frac{1}{n}\right), \qquad
\mathrm{Var}[H] = \sum_{k=2}^{n} \frac{4}{k^2(k-1)^2}.
\]

Vi ser dermed, at den forventede træhøjde hurtigt nærmer sig værdien
\(2\). Allerede ved relativt små stikprøvestørrelser ligger man tæt på
denne grænseværdi. Hvis målet er at estimere tidspunktet for MRCA mere
præcist, giver det derfor begrænset information at tilføje mange ekstra
sekvenser. En anden vigtig størrelse er den totale grenlængde
\(L = \sum_{k=2}^{n} k\,T_k\). I modsætning til træhøjden vokser den
totale grenlængde logaritmisk med stikprøvestørrelsen og indeholder
derfor stadig ny information, når flere sekvenser inkluderes. Det er
især denne størrelse, der forbinder genealogien med mutationsprocessen.
Dens forventning er \[
\mathbb{E}[L] = \sum_{k=2}^{n} \frac{2}{k-1} = 2\,a_n, \qquad a_n = \sum_{j=1}^{n-1} \frac{1}{j}.
\]

hvor \(a_n=\sum_{j=1}^{n-1} \frac{1}{j}\) er det harmoniske tal kendt
fra Wattersons estimator (Hobolth et al. 2019; Watterson 1975).
Coalescent-processen beskriver altså den skjulte genealogi og de
tidsmæssige relationer mellem de observerede sekvenser. Genealogien kan
imidlertid ikke observeres direkte. Det vi faktisk måler, er
mutationerne langs træets grene. For at forbinde genealogi med genetiske
data er det derfor nødvendigt også at beskrive mutationsprocessen.

\section{Mutationer og
site-frekvens-spektret}\label{mutationer-og-site-frekvens-spektret}

Givet en genealogi antages mutationer at opstå tilfældigt langs træets
grene. Under den neutrale model beskrives mutationerne som en
Poisson-proces, hvor antallet af mutationer på en gren afhænger af
grenens længde. Betinget på en samlet grenelængde \(t\) følger antallet
af mutationer derfor en Poisson-fordeling med parameter \(\theta t/2\).
Da mutationerne placeres på grenene af genealogien, bliver den totale
grenelængde den centrale forbindelse mellem coalescent-processen og de
observerede data. Det forventede antal segregerende sites bliver derfor
(Hobolth et al. 2019) \[
\mathbb{E}[S] = \frac{\theta}{2}\,\mathbb{E}[L] = \theta \sum_{j=1}^{n-1} \frac{1}{j} = \theta\, a_n.
\]

Det fører til Wattersons estimator \(\hat{\theta}_W = S/a_n\) som er den
klassiske metode til at estimere \(\theta\) fra antallet af segregerende
sites. En alternativ estimator er baseret på det gennemsnitlige antal
parvise sekvensforskelle (Hobolth et al. 2021): \[
\hat{\theta}_\pi = \frac{1}{\binom{n}{2}} \sum_{i < j} \pi_{ij},
\]

hvor \(\pi_{ij}\) er antallet af mutationer, der adskiller sekvens \(i\)
og \(j\). Tajimas \(D\)-statistik er forskellen mellem de to
estimatorer, skaleret med standardafvigelsen for forskellen (Hobolth et
al. 2021; Tajima 1989): \[
D = \frac{\hat{\theta}_\pi - \hat{\theta}_W}{\sqrt{\mathrm{Var}(\hat{\theta}_\pi - \hat{\theta}_W)}}
\]

Under neutralitet og konstant populationsstørrelse forventes \(D\) at
ligge omkring nul. Negative værdier indikerer et overskud af sjældne
mutationer, hvilket ofte forbindes med populationsvækst eller positiv
selektion. Positive værdier peger derimod på et underskud af sjældne
mutationer og kan være tegn på flaskehalse, populationsstruktur eller
balancerende selektion.

Mens Wattersons estimator og Tajimas \(D\) opsummerer variationen i data
ved hjælp af enkelte tal, giver site-frekvens-spektret (SFS) et mere
detaljeret billede. SFS beskriver, hvor mange mutationer der observeres
i præcis \(i\) ud af de \(n\) sekvenser. Formelt skrives det som
\((\xi_1,\xi_2,\ldots,\xi_{n-1}),\) hvor \(\xi_i\) tæller antallet af
sites, hvor den afledte allel forekommer i præcis \(i\) individer. Under
standard coalescenten med neutralitet og konstant populationsstørrelse
gælder
\(\mathbb{E}[\xi_i] = \frac{\theta}{i}, \qquad i = 1, 2, \ldots, n-1\)
(Hobolth et al. 2021). Sjældne mutationer forventes at dominere
spektret. Især forventes singletons at forekomme langt hyppigere end
mutationer med høj frekvens. Dette afspejler direkte formen på
genealogien, hvor en stor del af den samlede grenelængde ligger på de
ydre grene tæt på nutiden. SFS kan vise, at hvis der er populationsvækst
vil man se et overskud af sjældne mutationer, mens flaskehalse ofte
reducerer antallet af singletons. Ved at sammenligne observerede og
forventede frekvensspektre kan man derfor opnå information om
populationens historie. Figure~\ref{fig-sfs} viser det forventede
site-frekvens-spektrum for \(n=4\) beregnet analytisk ved hjælp af
\texttt{phasic} (Munch 2026).

\begin{figure}[H]

\centering{

\includegraphics[width=8.21875in,height=4.0625in]{index_files/figure-latex/..-notebooks-01_coalescent_basics-fig-sfs-output-1.png}

}

\caption{\label{fig-sfs}Site Frekvens Spektrum for \(n=4\). Forventet
grenlængde per frekvensklasse beregnet via reward-transformation:
singletons (blå, \(\mathbb{E}[L_1]=2.0\)), doubletons (orange,
\(\mathbb{E}[L_2]=1.0\)) og tripletons (grøn,
\(\mathbb{E}[L_3]=0.667\)). Singletons dominerer fordi ydre grene altid
er kortere end interne grene i Kingmans coalescent.}

\end{figure}%

Singleton-dominansen ses tydeligt. Mutationer, der kun forekommer i et
individ, er langt de hyppigste, mens frekvenserne falder hurtigt for
større frekvensklasser. SFS giver dermed et detaljeret billede af
variationen i data. Hvis man ønsker at beregne fordelinger, momenter og
kovarianser for sådanne størrelser analytisk, kræver det imidlertid et
mere generelt matematisk værktøj nemlig fase-type fordelinger.

\section{Fase-type fordelinger}\label{fase-type-fordelinger}

Coalescent-processen kan beskrives som en absorptionsproces i en
Markov-kæde. Processen starter med et \(n\) aktive linjer og absorberes,
når alle linjer er coalesceret til MRCA. Denne type processer beskrives
naturligt ved fase-type fordelinger (Bladt and Nielsen 2017; Hobolth et
al. 2024). En fase-type fordeling beskriver absorptionstiden \(\tau\) i
en kontinuert-tids Markov-kæde med \(p\) transiente tilstande og en
absorberende tilstand. Systemet beskrives ved intensitetsmatricen
(Hobolth et al. 2024): \[
\Lambda = \begin{pmatrix} \mathbf{T} & \mathbf{t} \\ \mathbf{0} & 0 \end{pmatrix},
\]

hvor \(\mathbf{T}\) er sub-intensitetsmatricen med negative
diagonalindgange og \(\mathbf{t} = -\mathbf{T}\mathbf{e}\) er
exit-raterne til den absorberende tilstand. Vi skriver
\(\tau \sim \mathrm{PH}(\alpha, \mathbf{T})\) og lader \(\alpha\) angive
startfordelingen. Den store fordel ved denne repræsentation er, at
tæthedsfunktioner, fordelinger og momenter kan beregnes direkte ved
hjælp af matrixoperationer (Bladt and Nielsen 2017): \[
f_\tau(s) = \alpha \, e^{\mathbf{T}s} \, \mathbf{t}, \qquad
\mathbb{E}[\tau] = \alpha(-\mathbf{T})^{-1}\mathbf{e}, \qquad
\mathbb{E}[\tau^n] = n!\,\alpha(-\mathbf{T})^{-n}\mathbf{e}.
\]

Matricen \(\mathbf{U} = (-\mathbf{T})^{-1}\) kaldes Green-matricen; dens
\((i,j)\)-te element fortæller, hvor lang tid processen i forventning
tilbringer i tilstand \(j\), givet at processen starter i tilstand \(i\)
de såkaldte sojourn-tider. For Kingmans coalescent er træhøjden \(H\)
fase-type fordelt med startvektor \(\alpha = (1, 0, \ldots, 0)\) og
sub-intensitetsmatricen (Hobolth et al. 2024): \[
\mathbf{T} = \begin{pmatrix} -\lambda_n & \lambda_n & & \\ & -\lambda_{n-1} & \lambda_{n-1} & \\ & & \ddots & \\ & & & -\lambda_2 \end{pmatrix}, \qquad \lambda_k = \binom{k}{2}.
\]

I \texttt{phasic} konstrueres dette tilstandsrum automatisk ud fra en
callback-funktion, der definerer hvilke overgange der er mulige og med
hvilke rater. For \(n = 4\) er tilstandene beskrevet ved vektoren
\((s_1, s_2, s_3, s_4)\), der tæller antallet af grene med henholdsvis
\(1, 2, 3\) og \(4\) efterkommere i stikprøven, som illustreret i
Figure~\ref{fig-graf}.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-01_coalescent_basics-fig-graf-output-1.pdf}}

}

\caption{\label{fig-graf}Tilstandsrum for Kingmans coalescent med
\(n=4\) prøver. Tilstandsvektoren \((s_1, s_2, s_3, s_4)\) tæller det
antal linjer der har henholdsvis \(1\), \(2\), \(3\) og \(4\)
efterkommere. Starttilstanden \((4,0,0,0)\) repræsenterer fire separate
linjer; absorptionstilstanden \((0,0,0,1)\) er MRCA. Pilene viser mulige
koalescensstransitioner med tilhørende rater.}

\end{figure}%

Fase-type repræsentationen giver adgang til langt mere end blot
træhøjden. Mange populationsgenetiske størrelser kan beskrives som
akkumulerede størrelser langs processen snarere end som absorptionstider
i sig selv. Dette leder til reward-transformationer og den multivariate
fase-type teori.

\section{Reward-transformationer og multivariat
fase-type}\label{reward-transformationer-og-multivariat-fase-type}

En af de mest nyttige egenskaber ved fase-type fordelinger er, at
teorien kan udvides til at beskrive størrelser, der akkumuleres langs en
Markov-proces. Det interessant, er nemlig hvor lang tid processen
tilbringer i bestemte tilstande. Det gælder eksempelvis den totale
grenelængde, ydre grenelængde eller grenlængder knyttet til bestemte
frekvensklasser i SFS. Figure~\ref{fig-pdf-grenlangder} viser PDF og CDF
for singleton-, doubleton- og tripleton-grenlængder beregnet på denne
måde.

\begin{figure}[H]

\centering{

\includegraphics[width=8.21875in,height=4.0625in]{index_files/figure-latex/..-notebooks-01_coalescent_basics-fig-pdf-grenlangder-output-1.png}

}

\caption{\label{fig-pdf-grenlangder}PDF og CDF for singleton- (blå),
doubleton- (orange) og tripleton-grenlængder (\(n=4\)).
Singleton-fordelingen er en blanding af eksponentielle fordelinger og
udviser en bred tunge; tripleton-fordelingen er mere koncentreret. Den
absorberende tilstand bidrager til en spids ved \(t=0\) for tripletons.}

\end{figure}%

Ideen ved reward-transformationer er at hver tilstand tildeles en vægt,
også kaldet en reward. Når processen bevæger sig gennem tilstandsrummet,
akkumuleres den vægtede tid. Hvis \(r(i)\) angiver reward-værdien i
tilstand \(i\), kan den samlede reward skrives som
\(\tilde{\tau} = \int_0^\tau r(X_t),dt.\) Et centralt resultat i
fase-type teorien er, at denne størrelse igen er fase-type fordelt, når
alle rewards er positive (Bladt and Nielsen 2017). Mere præcist gælder
\[
\tilde{\tau} \sim \mathrm{PH}\!\bigl(\alpha,\, \Delta(\mathbf{r})^{-1}\mathbf{T}\bigr).
\]

Dette gør det muligt at analysere en lang række størrelser inden for den
samme matematiske ramme. Den totale grenelængde \(L\) er et eksempel.
Når der er \(k\) aktive linjer i genealogien, bidrager hver linje med
til den akkumulerede tid. Reward-vektoren bliver derfor
\(\mathbf{r}_L=(n,n-1,\ldots,2).\) Den totale grenelængde kan dermed
fortolkes som en reward-transformeret version af træhøjden \(H\). På
samme måde kan man konstruere rewards, der kun tæller bestemte typer
grene, eksempelvis ydre grene eller grene med et bestemt antal
efterkommere.

I praksis er man ofte interesseret i flere størrelser på samme tid.
Træhøjde, total grenelængde og ydre grenelængde beskriver forskellige
aspekter af den samme genealogi og er derfor statistisk afhængige. For
at håndtere dette udvides teorien til multivariate fase-type fordelinger
(MPH). I MPH kobles flere reward-vektorer med den samme underliggende
Markov-proces. Dette giver adgang til fælles fordelinger, kovarianser og
blandede momenter. For to reward-transformerede variable \(Y_1\) og
\(Y_2\) er det blandede moment givet ved (Hobolth et al. 2024) \[
\mathbb{E}[Y_1 Y_2] = \alpha \mathbf{U} \Delta(\mathbf{r}_1) \mathbf{U} \Delta(\mathbf{r}_2) \mathbf{e} + \alpha \mathbf{U} \Delta(\mathbf{r}_2) \mathbf{U} \Delta(\mathbf{r}_1) \mathbf{e},
\]

For et lille eksempel med \(n=3\) sekvenser (Hobolth et al. 2024) kan
man beskrive træhøjde, total grenelængde, ydre grenelængde og indre
grenelængde simultant som \[
(H, L, E, I) \sim \mathrm{MPH}\!\left(\mathbf{e}_1, \mathbf{T}, \mathbf{R}\right), \qquad
\mathbf{T} = \begin{pmatrix} -3 & 3 \\ 0 & -1 \end{pmatrix}, \quad
\mathbf{R} = \begin{pmatrix} 1 & 3 & 3 & 0 \\ 1 & 2 & 1 & 1 \end{pmatrix}.
\]

Dermed kan man udlede både forventninger, varianser og kovarianser
analytisk uden at simulere genealogier. Indtil nu har fokus været på
kontinuerte størrelser som tider og grenelængder. Mange af de
størrelser, der observeres direkte i genetiske data, er imidlertid
diskrete. Det gælder eksempelvis antallet af segregerende sites og de
enkelte komponenter i site-frekvens-spektret. For at beskrive disse
størrelser, udvides teorien nu til diskrete fase-type fordelinger.

\section{Den diskrete fase-type fordeling og segregerende
sites}\label{den-diskrete-fase-type-fordeling-og-segregerende-sites}

Mens fase-type fordelinger beskriver kontinuerte variable som tider og
grenelængder, beskriver diskrete fase-type fordelinger (DPH)
tællevariable. Dette gør dem særligt velegnede til at modellere
mutationsdata. En måde at forstå konstruktionen på er at betragte
forholdet mellem mutationer og coalescent-hændelser som en konkurrence.
Når processen befinder sig i en tilstand med \(k\) aktive linjer, kan
den næste hændelse enten være en mutation eller en coalescenthændelse.
Sandsynligheden for at næste hændelse er en mutation er (Hobolth et al.
2021): \[
p_k = \frac{\theta/2}{\theta/2 + \binom{k}{2}} = \frac{\theta}{\theta + k(k-1)}.
\]

Denne konkurrence mellem mutation og coalescent giver anledning til en
diskret Markov-kæde, som kan analyseres ved hjælp af DPH-teorien. Et
vigtigt resultat er, at antallet af segregerende sites kan beskrives
direkte ved en diskret fase-type fordeling. Betinget på den
underliggende genealogi gælder (Hobolth et al. 2024) \[
S+1 \sim \mathrm{DPH} (\alpha_L,\mathbf P),
\]

Hvor
\({P} = \left(\mathbf{I} - \frac{2}{\theta}\mathbf{T}_L\right)^{-1}\).
Dette giver mulighed for at beregne sandsynligheder og likelihoods
analytisk i stedet for via simulation. På samme måde kan de enkelte
komponenter i SFS beskrives ved diskrete fase-type fordelinger. Dermed
kan man ikke blot beregne forventninger, men hele fordelinger samt
kovarianser mellem forskellige frekvensklasser. Indtil videre har alle
modellerne været baseret på et enkelt locus. I virkelige genomer er
situationen imidlertid mere kompleks, fordi rekombination betyder, at
forskellige positioner i genomet kan have forskellige genealogier.

Standard-coalescenten antager, at alle positioner i et kort locus kan
approksimeres som om, de deler den samme genealogi. Dette er en rimelig
approksimation for korte DNA-segmenter, men bliver mindre realistisk,
når man analyserer større dele af genomet. Årsagen er rekombination.
Under meiosen kan genetisk materiale udveksles mellem kromosomer,
hvilket betyder, at forskellige dele af genomet kan nedarves fra
forskellige forfædre. To nærliggende positioner i genomet vil derfor
ikke nødvendigvis have den samme genealogi. For at beskrive dette
udvides coalescent til et ancestral recombination graph (ARG). Hvor
coalescent-processen alene indeholder hændelser, der samler linjer,
indeholder ARG'et både coalescent- og rekombinationshændelser. De to
typer hændelser har modsatrettede effekter. Coalescent-hændelser
reducerer antallet af aktive linjer ved at samle dem, mens rekombination
kan splitte ancestrale linjer op og skabe nye genealogiske forbindelser.
Resultatet er et mere komplekst tilstandsrum. Figure~\ref{fig-arg-graph}
viser tilstandsrummet for to-locus ARG-modellen med \(n=2\).

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-arg-graph-output-1.pdf}}

}

\caption{\label{fig-arg-graph}Tilstandsrum for to-locus ARG-modellen
(\(n=2\), to loci separeret af rekombinationsrate \(\rho\)). Knuder
repræsenterer konfigurationer: begge linjer i ét locus ukoalescerede
(øverst), delvist koalescerede (midterste) og MRCA-tilstande
(absorberende). Blå pile: koalescentovergange (rate
\(\propto \theta_0\)). Røde pile: rekombinationsovergange (rate
\(\propto \theta_1=\rho\)). Rekombination skaber nye parrede tilstande
der forsinker absorptionen.}

\end{figure}%

Sammenlignet med standard coalescent (Figure~\ref{fig-graf}) er antallet
af mulige tilstande væsentligt større, selv for små stikprøvestørrelser.
Dette skyldes, at modellen nu skal holde styr på, hvilke dele af genomet
der deler fælles historie og hvilke der allerede er blevet adskilt af
rekombination. Rekombination parameteren \(\rho = 4N_e r\) beskriver
styrken af rekombinationsprocessen på samme måde, som
\(\theta = 4N_e \mu\) beskriver mutationsprocessen. ARG-modeller giver
mulighed for at udnytte information fra hele genomer frem for et enkelt
loci. Samtidig illustrerer de, hvordan fase-type teorien kan anvendes på
langt mere komplekse genealogiske strukturer end den klassiske standard
coalescent. En anden vigtig generalisering af standard coalescent er at
tage højde for populationsstruktur. I naturen er populationer sjældent
fuldstændigt homogene og migration mellem geografisk adskilte
populationer kan have stor betydning for de genealogiske mønstre, der
observeres i data.

\section{Populationsstruktur: to-ø-modellen og
IM-modellen}\label{populationsstruktur-to-uxf8-modellen-og-im-modellen}

Den klassiske standard coalescent bygger på antagelsen om panmixi, dvs.
at alle individer i populationen har samme sandsynlighed for at
reproducere med hinanden. Denne antagelse er sjældent realistisk.
Geografiske barrierer, habitatfragmentering og begrænset spredning
betyder ofte, at individer primært udveksler gener med nærliggende
populationer. Når populationer er opdelt i delpopulationer, ændres
genealogierne markant. To individer fra samme population vil typisk dele
fælles forfædre hurtigere end to individer fra forskellige populationer.
Genealogien kommer derfor til at indeholde information ikke blot om
populationsstørrelse, men også om migration mellem populationer. En af
de simpleste modeller for populationsstruktur er to-ø-modellen. Modellen
består af to populationer, der har migration mellem sig med en konstant
migrationsrate \(m\). Hver population følger de samme principper som
standard coalescent, men der tilføjes migrationsovergange mellem
populationerne (Hobolth et al. 2024). Hvis to linjer befinder sig i
samme population, kan de coalescere direkte. Hvis de befinder sig i
forskellige populationer, må mindst en af dem først migrere, før en
coalescenthændelse kan finde sted. Migration fungerer dermed som en
mekanisme, der forsinker coalescent-processen. For at beskrive dette må
tilstandsrummet udvides. Hver linje karakteriseres nu ikke alene ved
antallet af efterkommere, men også ved hvilken population linjen aktuelt
befinder sig i. Dette giver en mere kompleks Markov-kæde end den
klassiske standard coalescent. Figure~\ref{fig-two-island-graph} viser
tilstandsrummet for to-ø-modellen med \(n=2\).

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-two-island-graph-output-1.pdf}}

}

\caption{\label{fig-two-island-graph}Tilstandsrum for to-ø modellen med
\(n=2\) linjer. Tilstandsvektoren \((s_1, s_2, \text{pop})\) tracker om
de to linjer befinder sig i population \(1\), population \(2\) eller er
delt. Pile angiver mulige overgange: koalescentovergange (blå) sker
inden for samme population; migrationsovergange (rød) sender en linje
fra én population til den anden. Absorptionstilstanden MRCA nås når
begge linjer er i samme population og koalescerer.}

\end{figure}%

Figure~\ref{fig-two-island-graph} illustrerer, hvordan migration og
coalescent konkurrerer med hinanden. Coalescenthændelser reducerer
antallet af aktive linjer, mens migration flytter linjer mellem
populationerne. Selv med blot to linjer bliver tilstandsrummet
betydeligt større end i standard coalescent (Figure~\ref{fig-graf}). I
denne model parametriseres processerne ved \(\theta_0 = 4N_e\mu\) og
\(\theta_1 = 4N_em,\) hvor \(\mu\) er mutationsraten og \(m\)
migrationsraten. En vigtig statistisk udfordring ved modellen er
identificerbarhed. Høj migration og høj coalescentrate kan producere
meget lignende genealogiske mønstre. Begge mekanismer fører til korte
TMRCA-tider og dermed relativt ens fordelinger af genetisk variation.
Når migrationen bliver meget høj, bliver det derfor vanskeligt at
afgøre, om et observeret mønster skyldes hyppig migration eller hurtig
coalescent. Selvom to-ø-modellen er et vigtigt skridt mod mere
realistiske modeller, beskriver den stadig populationerne som stationære
gennem hele deres historie. I mange biologiske situationer er man
imidlertid interesseret i populationer, der på et tidspunkt har splittet
sig fra en fælles forfaderpopulation. Dette leder til
isolation-with-migration(IM)-modellen.

IM-modellen kombinerer populationsstruktur med et historisk
split-tidspunkt. Modellen antager, at de to nuværende populationer
opstod fra en fælles ancestral population for \(t_s\) generationer
siden. Fra nutiden og tilbage til split-tidspunktet udvikler
populationerne sig som en to-ø-model med migration. Før
split-tidspunktet eksisterer kun den fælles ancestral population.
Modellen introducerer dermed en naturlig tidsmæssig struktur i
genealogien. Nutidige populationer kan være adskilte, men deler stadig
en fælles evolutionær fortid. Et vigtigt aspekt ved IM-modellen er, at
den er tidsinhomogen. Overgangsraterne ændrer sig ved split-tidspunktet
og processen beskrives derfor ikke længere af en enkelt
generator-matrix. I stedet opdeles historien i epoker med forskellige
rater. Dermed bliver det muligt at beskrive hændelser såsom flaskehalse
og ekspansioner hvilket efterlader karakteristiske signaturer i
TMRCA-fordelingen. Figure~\ref{fig-sfs-epoch} viser, hvordan SFS ser ud
under en tidsinhomogen model med tre epoker.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/figure-latex/..-notebooks-05_time_inhomogeneous-fig-sfs-epoch-output-1.png}}

}

\caption{\label{fig-sfs-epoch}SFS under \(3\)-epoke model med \(n=10\)
og population-størrelser \(N_e=[1, 5, 10]\) (nuværende, fortid, fjern
fortid). Blå søjler: singletons (\(1\)-ton); orange: doubletons
(\(2\)-ton); grøn: tripletons (\(3\)-ton); osv. Singletons dominerer
kraftigt (\(>40\%\) af total grenlængde) fordi den nuværende lille
population (\(N_e=1\)) giver mange korte ydre grene som producerer
singletons. Fortidens store population (\(N_e=10\)) bidrager med lange
interne grene der giver flatere højere frekvenser.}

\end{figure}%

En lille nuværende population (epoch med \(N_e = 1\)) giver mange korte
grene og dermed et markant overskud af singletons i SFS. I
\texttt{phasic} håndteres sådanne modeller ved at opbygge processen
epoke for epoke og kombinere dem analytisk. Dette gør det muligt at
beregne fordelinger og momenter for relativt komplekse demografiske
modeller uden omfattende simulation (Røikjer et al. 2022; Munch 2026).

\section{Bayesiansk inferens med
SVGD}\label{bayesiansk-inferens-med-svgd}

I dette speciale bruges Bayesiansk inferens, hvor posterioren er givet
ved \[
\pi(\theta \mid \mathbf{x}) \propto p(\mathbf{x} \mid \theta)\, \pi_0(\theta).
\]

Her repræsenterer \(p(\mathbf x\mid\theta)\) likelihooden, mens
\(\pi_0(\theta)\) er priorfordelingen. En fordel ved Bayesiansk inferens
er, at usikkerheden kvantificeres direkte. I stedet for at producere et
enkelt estimat opnås en hel sandsynlighedsfordeling over
parameterværdier. Dette er relevant, hvor data ofte er støjfyldte og
hvor flere forskellige parameterkombinationer kan forklare de samme
observationsmønstre. Udfordringen er, at posteriorfordelingen sjældent
kan beregnes analytisk. For komplekse coalescentmodeller bliver
integralerne hurtigt uoverskuelige og man må derfor benytte numeriske
metoder. Den klassiske løsning er Markov Chain Monte Carlo (MCMC), men
sådanne metoder kan være beregningstunge og langsomme for de
grafbaserede modeller, der anvendes i dette speciale. Derfor benyttes
Stein Variational Gradient Descent (SVGD) (Liu and Wang 2016). SVGD
repræsenterer posterioren ved en samling partikler
\({\theta_1,\theta_2,\ldots,\theta_{n_p}}\) som iterativt flyttes gennem
parameterrummet. Opdateringen er givet ved \[
\theta_i \leftarrow \theta_i + \epsilon\, \hat{\phi}^*(\theta_i)
\]

Hvor \[
\hat{\phi}^*(\theta) = \frac{1}{n_p}\sum_{j=1}^{n_p}\Bigl[k(\theta_j, \theta)\,\nabla_{\theta_j}\log\pi(\theta_j\mid\mathbf{x}) + \nabla_{\theta_j}k(\theta_j, \theta)\Bigr],
\]

De to led i opdateringen har forskellige funktioner. Det første led
trækker partiklerne mod områder med høj posterior sandsynlighed. Det
andet led virker frastødende og forhindrer partiklerne i at kollapse til
et enkelt punkt. Kombinationen af de to mekanismer gør det muligt at
approksimere hele posteriorfordelingen frem for blot dens maksimum (Liu
and Wang 2016).

\section{Bavianer som modelsystem}\label{bavianer-som-modelsystem}

Modellerne i notebooks 01--06 testes udelukkende på simulerede data med
kendte sande parametre. Formålet er til sidst at anvende dem på rigtige
biologiske data og til det bruges bavianer slægten \emph{Papio} som
modelsystem.

\emph{Papio} er en gruppe af nært beslægtede primater, som lever i store
dele af Afrika (Kopp et al. 2023). Slægten består af seks nulevende
arter:

\begin{itemize}
\tightlist
\item
  Olive bavian (\emph{Papio anubis}),
\item
  Yellow bavian (\emph{Papio cynocephalus}),
\item
  Chacma bavian (\emph{Papio ursinus}),
\item
  Guinea bavian (\emph{Papio papio}),
\item
  Hamadryas bavain (\emph{Papio hamadryas})
\item
  Kinda bavain (\emph{Papio kindae}).
\end{itemize}

Disse seks arter adskilles i to klader: en nordlig klade bestående af
\emph{P. hamadryas}, \emph{P. anubis} og \emph{P. papio} og en sydlig
klade bestående af \emph{P. kindae}, \emph{P. cynocephalus} og \emph{P.
ursinus} som divergerede fra en fælles stamfader for mere end 1 million
år siden ({Rogers et al.} 2019; {Vilgalys et al.} 2022). Den geografiske
fordeling og hybridzonerne er vist i Figure~\ref{fig-Kort}.

\begin{figure}

\centering{

\includegraphics[width=0.5\linewidth,height=\textheight,keepaspectratio]{illustrations/Kort.png}

}

\caption{\label{fig-Kort}\emph{Papio} baboon arter. Nuværende udbredelse
af hver bavianart samt placeringen af tre veldokumenterede aktive
hybridzoner er også vist. x1: hybridzone mellem \emph{P. hamadryas} og
\emph{P. anubis}, x2: hybridzone mellem \emph{P. cynocephalus} og
\emph{P. anubis}, x3: hybridzone mellem \emph{P. kindae} og \emph{P.
ursinus}. Billede fra Rogers et al., 2019.}

\end{figure}%

På trods af disse geografiske adskillelser kan flere arter krydse sig
med hinanden i naturen og producere fertile hybrider ({Sørensen et al.}
2023; {Jordan et al.} 2018). I flere kontaktzoner er der
veldokumenterede hybridzoner med løbende genflow. {Rogers et al.} (2019)
analyserede helgenomsekvenseringsdata for alle seks arter og
dokumenterede multiple episoder af admixture og introgression, herunder
genetisk bidrag fra en uidentificeret ancestral linje til \emph{P.
papio} og aktiv nuklear DNA-swamping ved hybridzonen mellem \emph{P.
anubis} og \emph{P. cynocephalus}. Som det fremgår af
Figure~\ref{fig-Kort}, overlapper arterne geografisk ved en række
hybridzoner, hvor aktiv genudveksling er dokumenteret ({Sørensen et al.}
2023). {Sørensen et al.} (2023) udvidede denne analyse til 225 vilde
bavianer fra 19 lokaliteter og dokumenterede admixture mellem \emph{P.
anubis} og \emph{P. cynocephalus} i det sydlige Tanzania, en tæt
genealogisk forbindelse mellem Kinda-bavianer og yellow-bavianerne, samt
tegn på tre-vejs admixture i yellow-bavianeren, et mønster som ikke
tidligere er observeret i denne slægt. Bavianernes evolutionære historie
begyndte omtrent samtidig med evolutionen af menneskeslægten
\emph{Homo}, altså for omkring 2 millioner år siden ({Rogers et al.}
2019). I modsætning til mennesker, hvor kun en art eksisterer i dag, har
bavianer bevaret flere linjer. PSMC-analyser (Li and Durbin 2011) viser,
at alle seks populationer har oplevet fald i effektiv
populationsstørrelse de seneste 100.000 år, sandsynligvis i forbindelse
med klimatiske ændringer ({Rogers et al.} 2019). Det gør dem særligt
velegnede som modelsystem til at studere både divergens og hybridisering
i naturlige populationer. I dette speciale anvendes estimater fra
{Sørensen et al.} (2023), herunder en mutationsrate på
\(\mu = 0.9 \times 10^{-8}\) per site per generation og en
generationstid på \(g = 11\) år, til at omsætte modelparametre til
absolutte størrelser.

\chapter{Metode}\label{metode}

Analysen er bygget op omkring otte Jupyter notebooks. NB01--NB06
anvender udelukkende simulerede data med kendte sande parametre.
Formålet er at verificere, at implementeringen er korrekt og at
undersøge, under hvilke betingelser metoderne fungerer eller bryder
sammen. Først derefter anvendes modellerne på de observerede bavian-data
i NB07A og NB07B. Alle analyser er implementeret i Python ved hjælp af
biblioteket \texttt{phasic} (Munch 2026), en oversigt over tabellerne
kan ses i Table~\ref{tbl-notebooks}.

\begin{longtable}[]{@{}ll@{}}
\caption{Oversigt over de otte
notebooks.}\label{tbl-notebooks}\tabularnewline
\toprule\noalign{}
Notebook & Hvad der gøres \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Notebook & Hvad der gøres \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
NB01 & Verificering af coalescent som fase-type fordeling \\
NB02 & Kalibrering af SVGD: optimizer, læringsrate og prior \\
NB03 & To-ø modellen: identificerbarhed og asymmetrisk migration \\
NB04 & Numerisk præcision og beregningstid \\
NB05 & Flaskehalse, demografiske ændringer og IM-modellen \\
NB06 & Joint probability-inferens og sensitivitet over for \(\mu\) \\
NB07A & Forbehandling og beskrivelse af bavian-genomdata \\
NB07B & Inferens på bavianpopulationer \\
\end{longtable}

\section{Genomdata og forbehandling}\label{genomdata-og-forbehandling}

Genomdataene stammer fra {Sørensen et al.} (2023), som sekventerede 225
vilde bavianer fra alle seks \emph{Papio}-arter fordelt på 19
lokaliteter i Afrika. I dette speciale analyseres de seks populationer:
\emph{P. anubis}, \emph{P. cynocephalus}, \emph{P. kindae}, \emph{P.
papio}, \emph{P. hamadryas} og \emph{P. ursinus}. For at holde
beregninger håndterbare til inferensanalyserne udvælges et delsæt af
individer per population: \(n=4\) haploide prøver til
enkelt-populations-modellen og \(n=6\) per population til to-ø- og
IM-modellen, svarende til henholdsvis 35 og 140 tilstande i
tilstandsrummet. Alle analyser er baseret på kromosom \(20\) i VCF
format fra {Sørensen et al.} (2023) og loci med manglende data er
filtreret fra. Da der ikke er en klar outgroup til at bestemme den
ancestrale allel, bruger jeg den foldede SFS, som tæller antallet af
sites med minor allelefrekvens \(i\) og \(n-i\) som en kategori. Det
reducerer information om mutationsretning, men man undgår fejl fra
forkert ancestral state-bestemmelse. Antallet af mutationer per locus
beregnes som antallet af segregerende sites. Omregningen fra den
skalerede parameter \(\theta = 4N_e\mu\) til effektiv
populationsstørrelse benytter mutationsraten
\(\mu = 0{,}9 \times 10^{-8}\) mutationer per site per generation og
generationstiden \(g = 11\) år ({Sørensen et al.} 2023). Et estimat
\(\hat{\theta}\) omregnes til \(\hat{N}_e = \hat{\theta} / (4\mu)\) og
TMRCA-tider i \(2N_e\) generationsenheder omregnes til år som
\(t_{\text{år}} = t \cdot 2\hat{N}_e \cdot g\).

\section{Implementering og
kalibrering}\label{implementering-og-kalibrering}

Coalescentgrafen konstrueres i \texttt{phasic} via en callback-funktion,
der for en tilstandsvektor returnerer alle mulige overgange og
tilhørende rater. Kanternes rater angives via liste-syntaksen
\texttt{{[}rate{]}}, så \(\theta\) nemt kan skiftes ud via
\texttt{graph.update\_weights(theta)} og grafen kan bruges direkte til
Bayesiansk inferens. For strukturerede modeller to-ø og IM udvides
tilstandsrummet til at inkludere populations-identitet for hver linje.
IM-modellen implementeres ved at koble to separate grafer sammen med
\texttt{add\_epoch}, som beregner overgangssandsynlighederne analytisk
for hvert skift mellem epoker.

Alle modeller valideres mod msprime (Kelleher et al. 2016) ved at
simulere data med kendte parametre og tjekke at phasic giver det samme
resultat. Valideringen bruger ploidy=1 og parametriseringen
\(\theta = 4N_e\mu\) og for to-ø modellen oversættes migrationsrate
\(m\) til den skalerede parameter \(\theta_1 = m \cdot 2N_e\).

SVGD kalibreres systematisk i NB02 og NB04 over optimizer-valg,
prior-valg, antal partikler og iterationer. DataPrior centreres
automatisk via Wattersons estimator fra data, hvilket gør den robust
uden at man behøver specificere den manuelt. Den valgte
standardkonfiguration til alle efterfølgende analyser er Adamelia(0.2)
som optimizer, DataPrior til coalescentparametre, HalfCauchyPrior til
migrationsparametre, 20 partikler og 300 iterationer til
enkelt-parameter-modeller og 400 iterationer til to-parameter-modeller.

\chapter{Resultater}\label{resultater}

\section{Verificering af
Coalescentmodellen}\label{verificering-af-coalescentmodellen}

I Figure~\ref{fig-graf} ses tilstandsrummet for \(n=4\). Her tjekkes om
implementeringen faktisk giver de rigtige svar. Det første tjek er om
\texttt{phasic}s beregnede \(\mathbb{E}[H]\) stemmer med den analytiske
løsning for \(n=2\) til \(8\).

{

\begin{longtable}[]{@{}llll@{}}

\caption{\label{tbl-verificering}Verificering af \(\mathbb{E}[H]\) mod
analytisk formel \(\sum_{k=2}^{n} 2/[k(k-1)]\) for \(n=2\) til \(n=8\).
Forskellen er nul for alle \(n\), hvilket bekræfter at phasic beregner
de korrekte forventede koalescenttider.}

\tabularnewline

\toprule\noalign{}
& E{[}H{]} numerisk & E{[}H{]} analytisk & Forskel \\
n & & & \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2 & 1.00000 & 1.00000 & 0.0 \\
3 & 1.33333 & 1.33333 & 0.0 \\
4 & 1.50000 & 1.50000 & 0.0 \\
5 & 1.60000 & 1.60000 & 0.0 \\
6 & 1.66667 & 1.66667 & 0.0 \\
7 & 1.71429 & 1.71429 & 0.0 \\
8 & 1.75000 & 1.75000 & 0.0 \\

\end{longtable}

}

Afvigelsen er nul for alle prøvestørrelser i
Table~\ref{tbl-verificering}. Det bekræfter at tilstandsrummet er bygget
rigtigt og at Gauss-elimineringen i \texttt{phasic} giver resultater der
stemmer med den analytiske løsning. Det er et godt første skridt, men
ikke nok i sig selv det viser kun at de interne beregninger er
konsistente, ikke at modellen beskriver virkeligheden korrekt. Det næste
tjek er derfor mere afgørende: om den analytiske fase-type PDF stemmer
med TMRCA-fordelinger simuleret i msprime. msprime bruger en helt anden
tilgang i stedet for at løse matrixligninger simulerer det tusindvis af
tilfældige genealogier og tæller. At de to giver det samme resultat er
den egentlige validering.

\begin{figure}[H]

\centering{

\includegraphics[width=8.21875in,height=4.125in]{index_files/figure-latex/..-notebooks-01_coalescent_basics-fig-msprime-val-nb01-output-1.png}

}

\caption{\label{fig-msprime-val-nb01}msprime-validering af Kingmans
coalescent (\(n=4\)). Venstre: histogram af \(10{,}000\) simulerede
TMRCA-værdier (blå) sammenlignet med analytisk fase-type PDF (orange
kurve). Højre: empirisk ECDF (blå trin) versus analytisk CDF (orange
kurve). Den tætte overensstemmelse bekræfter at phasic-implementeringen
er korrekt.}

\end{figure}%

De to kurver ligger nærmest oven i hinanden i
Figure~\ref{fig-msprime-val-nb01}. Tæthedsfunktionen og den kumulative
fordelingsfunktion stemmer overens over hele fordelingens forløb med en
relativ afvigelse på kun \(1{,}66\%\). Det er inden for den variation
man forventer ved 3000 simuleringer \texttt{phasic} beregner analytisk
ved hjælp af matrixeksponentialer, mens msprime tæller over stokastiske
simuleringer. At de to giver praktisk talt identiske resultater giver
stor tillid til at implementeringen og skaleringen er korrekte. Alle
mere komplekse modeller i dette speciale er bygget videre på denne
verificerede base. Med implementeringen bekræftet kan man begynde at
kigge på, hvad modellen siger om selve coalescentprocessen. En central
størrelse er opholdstiden i de forskellige faser altså hvor lang tid
processen i gennemsnit bruger på hvert trin, fra \(n\) aktive linjer ned
til MRCA. Table~\ref{tbl-sojourn} viser disse sojourn-tider for \(n=4\).

{

\begin{longtable}[]{@{}llll@{}}

\caption{\label{tbl-sojourn}Forventede sojourn-tider per fase for
\(n=4\). Med \(k\) aktive linjer er den forventede opholdstid
\(\mathbb{E}[T_k] = 2/[k(k-1)]\) coalescent-enheder. Fasen med \(k=2\)
linjer (\(\mathbb{E}[T_2]=1.0\)) udgør den absolut største andel af den
samlede forventede TMRCA på 1.5 coalescent-enheder.}

\tabularnewline

\toprule\noalign{}
& \$k\$ linjer & Tilstande & \$\textbackslash mathbb\{E\}{[}T\_k{]} =
\textbackslash frac\{2\}\{k(k-1)\}\$ \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 4 & (4, 0, 0, 0) & 0.16667 \\
1 & 3 & (2, 1, 0, 0) & 0.33333 \\
2 & 2 & (0, 2, 0, 0), (1, 0, 1, 0) & 1.00000 \\

\end{longtable}

}

Fasen med \(k=2\) aktive linjer tager klart længst
\(\mathbb{E}[T_2] = 1{,}000\) coalescentenhed mens de tidlige faser er
meget kortvarige. Fasen med \(k=4\) linjer bidrager kun med
\(\mathbb{E}[T_4] = 0{,}167\) coalescent-enheder. Det betyder at langt
det meste af genealogiens tidslinje tilbringes i de allersidste
coalescenttrin, når der kun er 2 linjer tilbage, der venter på at finde
en fælles forfader. Det er også disse sene trin der er mest følsomme
over for populationsstørrelsen. Figure~\ref{fig-linje-dynamik} viser
sandsynlighedsfordelingen over tilstandene dynamisk over tid, så man kan
se præcis hvornår i processen hver tilstand dominerer.

\begin{figure}[H]

\centering{

\includegraphics[width=8.21875in,height=4.0625in]{index_files/figure-latex/..-notebooks-01_coalescent_basics-fig-linje-dynamik-output-1.png}

}

\caption{\label{fig-linje-dynamik}Sandsynlighedsfordelingen over
coalescenttilstande som funktion af tid (\(n=4\)). Hver farvet kurve
svarer til én tilstand: starttilstanden \((4,0,0,0)\) (blå) falder
eksponentielt; intermediærtilstande (orange, grøn, rød) når et maksimum
og aftager; absorptionstilstanden MRCA (lilla) stiger monotont mod
\(1\).}

\end{figure}%

I Figure~\ref{fig-linje-dynamik} ses det tydeligt: sandsynlighedsmassen
bevæger sig hurtigt væk fra starttilstanden \((4,0,0,0)\) i løbet af de
første \(0{,}3\) coalescent-enheder, mens absorptionstilstanden (MRCA)
stiger støt mod \(1\). Den lange flade hale afspejler præcis det samme
som sojourn-tabellen viste den endelige coalescens fra \(2\) linjer til
\(1\) dominerer tidsmæssigt. Udover selve TMRCA er man i
populationsgenetik typisk interesseret i SFS og de individuelle
grenlængder. Her er der en vigtig pointe der let overses: grenlængderne
i de forskellige frekvensklasser er ikke uafhængige af hinanden. De er
alle funktioner af den samme underliggende genealogi, og det betyder at
de er statistisk korrelerede. Table~\ref{tbl-kovarians} viser
kovariansmatricen for \(n=4\).

{

\begin{longtable}[]{@{}lllll@{}}

\caption{\label{tbl-kovarians}Kovariansmatrix for SFS-grenlængder
(\(n=4\)). Singletons (1-ton) og doubletons (2-ton) er negativt
korrelerede (\(\text{Cov}=-0.222\)). Singletons og tripletons er
positivt korrelerede (\(\text{Cov}=0.889\)). Diagonal-elementerne er
varianserne: \(\text{Var}[L_1]=1.778\), \(\text{Var}[L_2]=2.333\),
\(\text{Var}[L_3]=0.889\). Naiv uafhængighedsantagelse undervurderer
usikkerheden i inference.}

\tabularnewline

\toprule\noalign{}
& 1\textquotesingle ton & 2\textquotesingle ton & 3\textquotesingle ton
& 4\textquotesingle ton \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1\textquotesingle ton & 1.7778 & -0.2222 & 0.8889 & 0.0 \\
2\textquotesingle ton & -0.2222 & 2.3333 & -0.4444 & 0.0 \\
3\textquotesingle ton & 0.8889 & -0.4444 & 0.8889 & 0.0 \\
4\textquotesingle ton & 0.0000 & 0.0000 & 0.0000 & 0.0 \\

\end{longtable}

}

Singletons og doubletons er negativt korrelerede
(\(\text{Cov} = -0{,}222\)): en genealogi med lange singleton-grene har
typisk kortere doubleton-grene. Singletons og tripletons er derimod
positivt korrelerede (\(\text{Cov} = 0{,}889\)). En model der antager
uafhængighed vil systematisk undervurdere usikkerheden i estimaterne.
Det er vigtigt at have med, når hele SFS-vektoren bruges til at estimere
\(\theta\) --- en simpel Poisson-approksimation der behandler
frekvensklasserne som uafhængige vil ikke give korrekte
konfidensintervaller. En anden vigtig egenskab ved coalescentmodellen
er, hvordan den skalerer med populationsstørrelsen. Det er ikke nok at
vide at \(\mathbb{E}[H]\) og \(N\) er proportionale man vil gerne vide
hvad der sker med usikkerheden. Figure~\ref{fig-skalering} viser begge
dele.

\begin{figure}[H]

\centering{

\includegraphics[width=8.19792in,height=4.04167in]{index_files/figure-latex/..-notebooks-01_coalescent_basics-fig-skalering-output-1.png}

}

\caption{\label{fig-skalering}\(\mathbb{E}[H]\) (blå) og
\(\text{Var}[H]\) (orange) som funktion af populationsstørrelse \(N\) i
koalescent-enheder. \(\mathbb{E}[H]\) skalerer lineært med \(N\), mens
\(\text{Var}[H]\) skalerer kvadratisk. En fordobling af \(N\) fordobler
den forventede heterozygositet men firedobler variansen, hvilket øger
usikkerheden på individuelle loci disproportionalt.}

\end{figure}%

I Figure~\ref{fig-skalering} ses det klart: \(\mathbb{E}[H]\) skalerer
lineært med \(N\), men \(\text{Var}[H]\) skalerer kvadratisk. En
fordobling af \(N\) firedobler variansen i TMRCA. Det er et vigtigt
budskab: usikkerheden på estimater fra individuelle loci er meget høj
for store populationer og man kan ikke reducere den ved blot at tilføje
flere individer man har brug for flere uafhængige loci.
Mutationsprocessen kobles på genealogien via Poisson-fordelte mutationer
på grenene. Fordelingen af antal segregerende sites per locus er dermed
en blanding af Poisson-fordelinger, vægtet af TMRCA-fordelingen.
Figure~\ref{fig-pmf-mutationer} viser, hvordan denne fordeling ser ud
for varierende kombinationer af \(N\) og \(\mu\).

\begin{figure}[H]

\centering{

\includegraphics[width=8.10417in,height=4.11458in]{index_files/figure-latex/..-notebooks-01_coalescent_basics-fig-pmf-mutationer-output-1.png}

}

\caption{\label{fig-pmf-mutationer}PMF for antal segregerende sites
\(S\) under varierende \(N\) og \(\mu\) beregnet via Poisson-blanding
over grenlængdefordelingen. Fordelingen er højreskæv. Lav \(N\mu\) (blå)
koncentrerer sandsynlighed ved \(S=0{-}2\); høj \(N\mu\) (grøn/rød)
skubber massen mod større \(S\)-værdier og flader fordelingen ud.}

\end{figure}%

Figure~\ref{fig-pmf-mutationer} viser at fordelingen er højreskæv og at
lav \(N\mu\) giver mange loci med nul mutationer. Det er den praktiske
konsekvens af at loci er korte og genealogier stokastiske. Et naturligt
spørgsmål er nu, hvad man vinder ved at øge stikprøvestørrelsen \(n\)
det vil sige ved at sekventere flere individer.
Table~\ref{tbl-n-sammenligning} viser \(\mathbb{E}[H]\),
\(\mathbb{E}[L]\) og forholdet mellem dem for \(n=2\) til \(10\).

{

\begin{longtable}[]{@{}llllll@{}}

\caption{\label{tbl-n-sammenligning}\(\mathbb{E}[H]\), \(\mathbb{E}[L]\)
og forholdet \(\mathbb{E}[L]/\mathbb{E}[H]\) som funktion af
prøvestørrelse \(n=2\) til \(10\). \(\mathbb{E}[H]\) konvergerer
asymptotisk mod \(2\); \(\mathbb{E}[L]\) vokser som
\(\sum_{k=1}^{n-1} 2/k\). Forholdet \(\mathbb{E}[L]/\mathbb{E}[H]\)
stiger fra \(2.0\) til \(3.6\), hvilket begrunder valget af \(n=4\) til
\(6\) som en god afvejning af informationsindhold og beregningstid.}

\tabularnewline

\toprule\noalign{}
& \$n\$ & \$\textbackslash mathbb\{E\}{[}H{]}\$ &
\$\textbackslash mathbb\{E\}{[}L{]}\$ &
\$\textbackslash mathbb\{E\}{[}L{]}/\textbackslash mathbb\{E\}{[}H{]}\$
& Singleton-andel \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 2 & 1.0000 & 2.0000 & 2.0000 & 1.0000 \\
1 & 3 & 1.3333 & 3.0000 & 2.2500 & 0.6667 \\
2 & 4 & 1.5000 & 3.6667 & 2.4444 & 0.5455 \\
3 & 5 & 1.6000 & 4.1667 & 2.6042 & 0.4800 \\
4 & 6 & 1.6667 & 4.5667 & 2.7400 & 0.4380 \\
5 & 7 & 1.7143 & 4.9000 & 2.8583 & 0.4082 \\
6 & 8 & 1.7500 & 5.1857 & 2.9633 & 0.3857 \\
7 & 9 & 1.7778 & 5.4357 & 3.0576 & 0.3679 \\
8 & 10 & 1.8000 & 5.6579 & 3.1433 & 0.3535 \\

\end{longtable}

}

Tallene i Table~\ref{tbl-n-sammenligning} fortæller en klar historie:
\(\mathbb{E}[H]\) nærmer sig hurtigt en grænseværdi og tilfører næsten
ingen ny information fra \(n=6\) og opefter. Det er den totale
grenelængde \(\mathbb{E}[L]\) der fortsætter med at vokse logaritmisk.
Figure~\ref{fig-nh-el-vækst} viser dette grafisk.

\begin{figure}[H]

\centering{

\includegraphics[width=8.21875in,height=4.04167in]{index_files/figure-latex/..-notebooks-01_coalescent_basics-fig-nh-el-vkst-output-1.png}

}

\caption{\label{fig-nh-el-vækst}\(\mathbb{E}[H]\) (blå) og
\(\mathbb{E}[L]\) (orange) som funktion af prøvestørrelse \(n=2\) til
\(10\). \(\mathbb{E}[H]\) konvergerer hurtigt mod \(2\)
coalescent-enheder; \(\mathbb{E}[L]\) vokser ubegrænset men langsommere
og langsommere. Det aftagende afkast begrunder valget af \(n=4\) som
standardstikprøvestørrelse i resten af analysen.}

\end{figure}%

\(\mathbb{E}[H]\) nærmer sig hurtigt en grænseværdi fra \(n=6\) og
opefter, mens \(\mathbb{E}[L]\) fortsætter opad. Det aftagende
marginalafkast i \(\mathbb{E}[H]\) betyder at antallet af uafhængige
loci typisk er vigtigere end antallet af individer per population. På
baggrund af dette vælges \(n=4\) til enkelt-populationsmodellen (giver 6
tilstande) og \(n=6\) til to-populations-modellerne (giver 21 tilstande)
som et kompromis mellem informationsindhold og tilstandsrummets
størrelse.

For at give et fuldt billede af coalescentprocessens tidsmæssige forløb
viser Figure~\ref{fig-aktive-linjer} det forventede antal aktive linjer
og sandsynlighedsfordelingen over linjetal som funktion af tid.

\begin{figure}[H]

\centering{

\includegraphics[width=8.21875in,height=4.0625in]{index_files/figure-latex/..-notebooks-01_coalescent_basics-fig-aktive-linjer-output-1.png}

}

\caption{\label{fig-aktive-linjer}Forventet antal aktive linjer (blå,
venstre akse) og sandsynlighedsfordeling over linjetal (orange konturer,
højre akse) over tid (\(n=4\)). Processen reducerer hurtigt fra \(4\)
til \(\approx 2\) aktive linjer i de første \(0.3\) coalescent-enheder,
men bruger lang tid på den endelige koalesens fra \(2\) til \(1\) linje,
som dominerer den samlede TMRCA.}

\end{figure}%

I Figure~\ref{fig-aktive-linjer} ses den karakteristiske form: processen
reducerer hurtigt fra 4 til ca. 2 aktive linjer i løbet af de første
\(0{,}3\) coalescent-enheder, men bruger derefter lang tid på den
endelige coalescent fra 2 til 1 linje. Det er visuelt den samme besked
som sojourn-tabellen og linje-dynamik-figuren --- men her ses det som en
kontinuert fordeling over tid, snarere end diskrete punktestimater.

Som afslutning på NB01-valideringen viser
Figure~\ref{fig-msprime-validering} en fuld sammenligning der inkluderer
både TMRCA-histogram og SFS-form, for at bekræfte at hele pipelinen fra
coalescentgraf til observerede data er korrekt implementeret.

\begin{figure}[H]

\centering{

\includegraphics[width=8.21875in,height=4.05208in]{index_files/figure-latex/..-notebooks-01_coalescent_basics-fig-msprime-validering-output-1.png}

}

\caption{\label{fig-msprime-validering}msprime-validering af
coalescenten (\(n=4\)). Venstre: histogram af simuleret TMRCA (blå) mod
analytisk fase-type PDF (orange kurve); den tætte overensstemmelse
bekræfter korrekt parametrisering. Højre: simuleret vs.~analytisk
SFS-form normaliseret som andel af total grenlængde; de to fordelinger
er identiske inden for Monte Carlo-støj.}

\end{figure}%

Valideringen bekræfter at phasic giver det samme resultat som msprime
over hele distributionen --- både TMRCA-histogrammet og SFS-formen
stemmer overens. Med modellen verificeret kan man gå videre til at
kalibrere selve inferensmetoden.

\section{Kalibrering af SVGD}\label{kalibrering-af-svgd}

\subsection{Prior-valg}\label{prior-valg}

Introduktionen forklarede idéen bag SVGD og opdateringsformlen. Her
undersøges hvad der sker i praksis under kontrollerede forhold, hvor de
sande parametre er kendte. Det centrale spørgsmål er: kan metoden
genfinde de sande parametre, og er usikkerhedsintervallerne troværdige?

Det første spørgsmål er valget af prior. Priorvalget har stor
indflydelse, særligt når data er begrænsede. For at forstå dette testes
seks different prior-strategier for sand \(\theta = 7\).
Figure~\ref{fig-priors} viser de seks priors som
sandsynlighedsfordelinger.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-02_svgd_inferens_basis-fig-priors-output-1.pdf}}

}

\caption{\label{fig-priors}De seks prior-fordelinger evalueret i
analysen plottet som PDF over \(\theta\). Fra venstre mod højre: Vag
Gaussisk (\(\mu=7\), \(\sigma=5\), blå), Korrekt Gaussisk (\(\mu=7\),
\(\sigma=0.5\), orange), Forkert Gaussisk (\(\mu=1\), \(\sigma=0.5\),
grøn), HalfCauchy (\(\gamma=2\), rød), LogGaussPrior (lilla) og
DataPrior via Wattersons estimator (brun). Den røde lodrette linje
markerer den sande \(\theta=7\).}

\end{figure}%

Figure~\ref{fig-konvergens-priors} viser hvad der konkret sker, når SVGD
køres med de seks priors over 300 iterationer --- for at se om de
konvergerer stabilt mod den sande parameterværdi.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-02_svgd_inferens_basis-fig-konvergens-priors-output-1.pdf}}

}

\caption{\label{fig-konvergens-priors}Konvergensplots for SVGD under
seks prior-strategier (sand \(\theta=7\), \(n=2000\), Adam(\(0.1\)), 20
partikler, 300 iterationer). Hver delplot viser posterior-mean (blå
linje) og \(\pm 1\) SD (grå skravering) over iterationer. DataPrior og
Korrekt Gaussisk konvergerer hurtigst og stablest mod \(\theta=7\);
Forkert Gaussisk viser tydelig bias.}

\end{figure}%

Figure~\ref{fig-konvergens-priors} viser de afgørende forskelle: med den
korrekte prior konvergerer partiklerne hurtigt og stabilt mod den sande
parameterværdi. Den forkerte prior trækker kraftigt i den forkerte
retning og bruger mange iterationer på at kæmpe sig fri --- ved et
begrænset antal iterationer ses biassen stadig tydeligt. Den vage prior
er langsom fordi gradienten er svag.

For at se de individuelle posterior credibility intervals viser
Figure~\ref{fig-ci-prior-forkert} den kollapte posterior med den
forkerte prior. Figure~\ref{fig-ci-prior-datap} viser den samme analyse
med DataPrior.

\begin{figure}[H]

\centering{

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-02_svgd_inferens_basis-fig-ci-prior-forkert-output-1.pdf}}

}

\subcaption{\label{fig-ci-prior-forkert-1}Posterior credibility interval
(CI) for Forkert Gaussisk prior (\(\mu=1\), \(\sigma=0.5\)). Blå streger
viser partikelpositioner; orange linje er posterior-mean; stiplet sort
linje er sand \(\theta=7\). Prioren trækker posterioren mod
\(\theta\approx 1\) og giver systematisk bias --- selv med \(n=2000\)
observationer overtrumfer den forkerte prior data.}

\centering{

\begin{verbatim}
<Figure size 600x300 with 0 Axes>
\end{verbatim}

}

\subcaption{\label{fig-ci-prior-forkert-2}}

}

\caption{\label{fig-ci-prior-forkert}}

\end{figure}%

I Figure~\ref{fig-ci-prior-forkert} ses det tydeligt: alle 20 partikler
er samlet tæt om \(\theta \approx 1\) i stedet for den sande
\(\theta=7\). Posterioren er kunstigt smal og centreret forkert.
DataPrior giver et helt andet billede.

\begin{figure}[H]

\centering{

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-02_svgd_inferens_basis-fig-ci-prior-datap-output-1.pdf}}

}

\subcaption{\label{fig-ci-prior-datap-1}Posterior credibility interval
(CI) for DataPrior. Blå streger viser partikelpositioner; orange linje
er posterior-mean; stiplet sort linje er sand \(\theta=7\). DataPrior
centreres automatisk via Wattersons \(\hat{\theta}_W\) fra data og giver
en af de laveste bias-estimater i sammenligningen.}

\centering{

\begin{verbatim}
<Figure size 600x300 with 0 Axes>
\end{verbatim}

}

\subcaption{\label{fig-ci-prior-datap-2}}

}

\caption{\label{fig-ci-prior-datap}}

\end{figure}%

I Figure~\ref{fig-ci-prior-datap} er partiklerne bredt fordelt om den
sande \(\theta=7\) med en naturlig posterior-bredde der afspejler den
faktiske usikkerhed. DataPrior centrerer sig automatisk via Wattersons
estimator fra data, hvilket er nøglen til dens robusthed.

Et vigtigt spørgsmål er, hvornår data tager over fra prioren.
Figure~\ref{fig-prior-dominans} viser posterior-mean som funktion af
prøvestørrelse \(n\) for alle prior-strategier, og afslører præcis
hvornår den forkerte prior ophører med at dominere.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-02_svgd_inferens_basis-fig-prior-dominans-output-1.pdf}}

}

\caption{\label{fig-prior-dominans}Posterior-mean \(\hat{\theta}\) som
funktion af prøvestørrelse \(n\) for de seks prior-strategier. Alle
kurver konvergerer mod sand \(\theta=7\) (stiplet sort linje) med
stigende \(n\). DataPrior (blå) og Korrekt Gaussisk (orange) er tættest
på sandhed allerede ved \(n=500\); Forkert Gaussisk (grøn) kræver
\(n>5000\) for at overvinde prior-bias.}

\end{figure}%

Figure~\ref{fig-prior-dominans} viser at den forkerte prior stadig
dominerer ved \(n=500\) --- man skal op i mange tusinde observationer,
inden data overvinder en smal, forkert prior. DataPrior og LogGaussPrior
rammer den sande \(\theta=7\) konsekvent fra de første hundrede
observationer. Det er den vigtigste praktiske konsekvens for
bavian-analysen: et forkert priorvalg kan ikke rettes op ved at bruge
mere data.

For at generalisere disse resultater til det parameterinterval der er
relevant for bavianer --- \(\theta\) fra ca. \(3\) til \(20\) --- er de
samme priors testet systematisk. Table~\ref{tbl-prior-bav} viser
resultaterne.

{

\begin{longtable}[]{@{}lllllll@{}}

\caption{\label{tbl-prior-bav}Prior-sensitivitet over bavian-realistiske
\(\theta\)-værdier (\(\theta\in{1, 3, 7}\), \(n=2000\), 20 partikler,
300 iterationer). DataPrior giver konsekvent lavest bias og std på tværs
af \(\theta\)-værdier. GaussPrior (bred) er ustabil ved lav
\(\theta=1.0\) (std \(=0.55\)). HalfCauchy er særlig velegnet som
migrationsrate-prior i to-ømodellen.}

\tabularnewline

\toprule\noalign{}
& Sand \$\textbackslash theta\$ & Prior &
\$\textbackslash hat\textbackslash theta\$ & Std & Bias & RelBias
\$\textbackslash\%\$ \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 3.0 & GaussPrior (bred) & 3.1957 & 0.55208 & 0.1957 & 6.52 \\
1 & 3.0 & GaussPrior (smal) & 3.0299 & 0.02954 & 0.0299 & 1.00 \\
2 & 3.0 & HalfCauchy & 3.2107 & 0.78047 & 0.2107 & 7.02 \\
3 & 3.0 & LogGaussPrior & 3.0190 & 0.04735 & 0.0190 & 0.63 \\
4 & 3.0 & DataPrior (MoM) & 3.0285 & 0.03601 & 0.0285 & 0.95 \\
5 & 7.0 & GaussPrior (bred) & 14.5162 & 9.11448 & 7.5162 & 107.37 \\
6 & 7.0 & GaussPrior (smal) & 6.9106 & 0.31771 & 0.0894 & 1.28 \\
7 & 7.0 & HalfCauchy & 6.7021 & 0.39858 & 0.2979 & 4.26 \\
8 & 7.0 & LogGaussPrior & 8.6158 & 7.07196 & 1.6158 & 23.08 \\
9 & 7.0 & DataPrior (MoM) & 6.9754 & 0.04060 & 0.0246 & 0.35 \\
10 & 15.0 & GaussPrior (bred) & 61.8478 & 33.36155 & 46.8478 & 312.32 \\
11 & 15.0 & GaussPrior (smal) & 17.5174 & 3.93865 & 2.5174 & 16.78 \\
12 & 15.0 & HalfCauchy & 13.8187 & 3.88778 & 1.1813 & 7.88 \\
13 & 15.0 & LogGaussPrior & 14.3367 & 1.27721 & 0.6633 & 4.42 \\
14 & 15.0 & DataPrior (MoM) & 15.1308 & 0.13779 & 0.1308 & 0.87 \\
15 & 20.0 & GaussPrior (bred) & 80.5180 & 41.81708 & 60.5180 & 302.59 \\
16 & 20.0 & GaussPrior (smal) & 21.7403 & 3.04301 & 1.7403 & 8.70 \\
17 & 20.0 & HalfCauchy & 39.2872 & 95.56430 & 19.2872 & 96.44 \\
18 & 20.0 & LogGaussPrior & 25.2708 & 16.35943 & 5.2708 & 26.35 \\
19 & 20.0 & DataPrior (MoM) & 20.0335 & 0.10541 & 0.0335 & 0.17 \\

\end{longtable}

}

DataPrior giver konsekvent lav bias. Den brede GaussPrior klarer sig
dårligt ved høje parameterværdier --- særligt ved \(\theta = 15\) er
bias over \(150\%\) og konfidensintervallet indeholder ikke den sande
værdi. DataPrior vælges som standard til coalescentparametre og
HalfCauchy til migrationsparametre.

\subsection{Optimizer og læringsrate}\label{optimizer-og-luxe6ringsrate}

Table~\ref{tbl-optimizer-sammenligning} sammenligner alle tilgængelige
optimizere systematisk, og Figure~\ref{fig-optimizer-konvergens} viser
konvergensforløbet side om side.

\begin{table}

\caption{\label{tbl-optimizer-sammenligning}Sammenligning af alle
phasic-optimizere med bedste prior fra Blok 1 (sand \(\theta=7\),
\(n=2000\), 20 partikler, 300 iterationer).}

\centering{

\begin{verbatim}
Adagrad($0.1$)                : mean=7.0215  std=0.04988

Sand theta = 7.0
\end{verbatim}

}

\end{table}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-02_svgd_inferens_basis-fig-optimizer-konvergens-output-1.pdf}}

}

\caption{\label{fig-optimizer-konvergens}Konvergensplots for alle
phasic-optimizere (sand \(\theta=7\), \(n=2000\), DataPrior, 20
partikler, 300 iterationer). Hvert delplot viser posterior-mean (blå
linje) og \(\pm 1\) SD (grå skravering) over iterationer. Adam(\(0.1\))
og Adam(\(0.25\)) konvergerer stabilt. Adamelia(\(0.5\)) svinger.
Adagrad(\(0.1\)) er stabilt men langsomt.}

\end{figure}%

Figure~\ref{fig-optimizer-konvergens} bekræfter rangeringen:
Adamelia(0.2) giver stabil og hurtig konvergens. Adam(0.1) er
sammenlignelig men lidt langsommere. Adagrad er stabil men klart
langsommere end de øvrige.

Udover valget af optimizer kan man også justere, hvordan læringsraten
ændrer sig over iterationer. En fast læringsrate kan give svingninger
sent i forløbet, mens en faldende læringsrate kan stabilisere
konvergensen men risikerer at stoppe for tidligt.
Table~\ref{tbl-lr-schedules} sammenligner fire strategier.

\begin{verbatim}
Sand $\theta$ = {true_theta[0]}
\end{verbatim}

{

\begin{longtable}[]{@{}lllllll@{}}

\caption{\label{tbl-lr-schedules}Sammenligning af læringsrate-schedules
(sand \(\theta=7\), \(n=2000\), DataPrior, 20 partikler, 300
iterationer). Exp(\(\tau=150\)) giver den laveste final std (\(0.059\))
og er konsekvent tæt på sand \(\theta\). Warmup-strategien giver
sammenlignelig præcision. Constant(\(0.005\)) er stabil men langsom at
konvergere. Ingen schedule giver systematisk bias.}

\tabularnewline

\toprule\noalign{}
& Schedule & \$\textbackslash hat\textbackslash theta\$ & Std &
CI\$\_\{95\}\$ lav & CI\$\_\{95\}\$ høj & Indeholder sand
\$\textbackslash theta\$ \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & Constant(\$0.02\$) & 6.8697 & 0.24009 & 6.399 & 7.340 & True \\
1 & Constant(\$0.005\$) & 6.8745 & 0.08289 & 6.712 & 7.037 & True \\
2 & Exp(\$\textbackslash tau=50\$) & 6.8764 & 0.09449 & 6.691 & 7.062 &
True \\
3 & Exp(\$\textbackslash tau=150\$) & 6.8677 & 0.05878 & 6.753 & 6.983 &
False \\
4 & Warmup(\$w=40\$, \$\textbackslash tau=100\$) & 6.8808 & 0.33840 &
6.218 & 7.544 & True \\
5 & Warmup(\$w=80\$, \$\textbackslash tau=200\$) & 6.8906 & 0.03168 &
6.828 & 6.953 & False \\
6 & AdaptiveStepSize & 7.7643 & 1.77723 & 4.281 & 11.248 & True \\
7 & Adam(\$0.1\$) & 6.8526 & 0.03888 & 6.776 & 6.929 & False \\
8 & Adam(\$0.25\$) & 6.8767 & 0.11395 & 6.653 & 7.100 & True \\
9 & Adam + Warmup & 6.8366 & 0.05851 & 6.722 & 6.951 & False \\
10 & Adamelia(\$0.2\$) & 6.8653 & 0.01855 & 6.829 & 6.902 & False \\

\end{longtable}

}

\subsection{Partikelkollaps}\label{partikelkollaps}

En peaked posterior, hvor alle partikler samler sig på ét punkt, er et
tegn på at SVGD ikke har konvergeret ordentligt.
Figure~\ref{fig-posterior-peaked-vs-flat} viser kontrasten.

\begin{figure}

\centering{

\begin{verbatim}
Peaked std: 1.07330
Flad std:   0.02616
\end{verbatim}

}

\caption{\label{fig-posterior-peaked-vs-flat}}

\end{figure}%

I Figure~\ref{fig-posterior-peaked-vs-flat} ses kontrasten tydeligt: den
kollapte konfiguration (forkert prior og lav læringsrate) giver std
\(= 1{,}07\) med alle partikler klumpet på ét punkt, mens den
velfungerende konfiguration (DataPrior og Adamelia(0.2)) giver std
\(= 0{,}026\) med partikler bredt fordelt om den sande \(\theta\).
Kurtosis-diagnostikken bruges til at opdage kollaps automatisk.
Figure~\ref{fig-posterior-form} viser at kurtosis stiger markant ved for
høje læringsrater.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-02_svgd_inferens_basis-fig-posterior-form-output-1.pdf}}

}

\caption{\label{fig-posterior-form}Posterior-form under varierende
optimizere. Adam(\(0.1\)) giver flad posterior (lav kurtosis).
Adam(\(2.0\)) giver peaked --- SVGD kollapset. Kurtosis \(>2\) bruges
som grænse.}

\end{figure}%

Figure~\ref{fig-posterior-form} viser at kurtosis er lav og stabil ved
de anbefalede indstillinger, men stiger kraftigt ved for høje
læringsrater eller for få partikler. En kurtosis over 2 bruges som
grænse for hvornår kollaps er opstået.

\subsection{Dækning og
grid-søgning}\label{duxe6kning-og-grid-suxf8gning}

Med den velfungerende konfiguration identificeret er næste spørgsmål om
konfidensintervallerne faktisk er troværdige. Det testes ved at køre
SVGD over 50 gentagelser med kendte sande parametre og tælle, hvor ofte
den sande værdi falder inden for intervallet. Figure~\ref{fig-coverage}
viser resultatet.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-02_svgd_inferens_basis-fig-coverage-output-1.pdf}}

}

\caption{\label{fig-coverage}Empirisk \(95\%\)-CI dækning som funktion
af prøvestørrelse \(n\) estimeret over \(50\) replikater (blå kurve).
Den nominelle dækning på \(0.95\) er vist som stiplet rød linje.
Dækningen er under \(0.95\) ved \(n<500\) og nærmer sig \(0.95\) ved
\(n\geq 1000\), men viser variabilitet på grund af Monte Carlo-støj i de
\(50\) replikater.}

\end{figure}%

Med korrekt prior og \(n=100\) observationer er den empiriske dækning
\(94\%\), tæt på de nominelle \(95\%\). Den falder til \(78\%\) ved
\(n=500\) og stabiliserer sig på \(80\%\) ved \(n=2000\). Dette er
konsistent med en generel egenskab ved variationel inferens: den har en
tendens til at undervurdere usikkerheden lidt, fordi den approksimerer
posterioren med en begrænset samling partikler. Med forkert prior er
dækningen kun \(14\%\) ved \(n=100\), hvilket er et alvorligt problem.
Konfidensintervaller bør fortolkes som omtrentlige, og med særlig
forsigtighed ved meget få data.

Valget af antal partikler og iterationer er bestemt via en systematisk
grid-søgning. Table~\ref{tbl-grid-svgd} viser resultatet for
enkelt-populationsmodellen.

{

\begin{longtable}[]{@{}llllll@{}}

\caption{\label{tbl-grid-svgd}Grid-søgning over antal partikler \(n_p\)
og iterationer \(n_{\text{iter}}\) med Adamelia(\(0.2\)) og sand
\(\theta=7\), \(n=3000\) observationer. Kombinationen \(n_p=20\),
\(n_{\text{iter}}=300\) giver std \(=0.013\) og bias \(=0.143\) på
\(22\) sekunder og vælges som standardkonfiguration. Øget partikelantal
over \(40\) giver ikke konsekvent forbedring.}

\tabularnewline

\toprule\noalign{}
& Particles & Iterations & Std & Bias & Tid (s) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 20 & 100 & 0.03784 & 0.1520 & 11.69 \\
1 & 20 & 200 & 0.02565 & 0.1491 & 15.03 \\
2 & 20 & 300 & 0.01284 & 0.1433 & 22.09 \\
3 & 20 & 500 & 0.02272 & 0.1511 & 40.94 \\
4 & 40 & 100 & 0.02413 & 0.1404 & 22.56 \\
5 & 40 & 200 & 0.03172 & 0.1465 & 24.75 \\
6 & 40 & 300 & 0.03010 & 0.1503 & 40.31 \\
7 & 40 & 500 & 0.02684 & 0.1417 & 75.09 \\
8 & 60 & 100 & 0.04621 & 0.1452 & 19.35 \\
9 & 60 & 200 & 0.02450 & 0.1555 & 35.75 \\
10 & 60 & 300 & 0.03446 & 0.1424 & 56.48 \\
11 & 60 & 500 & 0.02925 & 0.1486 & 99.46 \\
12 & 80 & 100 & 0.03770 & 0.1436 & 26.63 \\
13 & 80 & 200 & 0.04108 & 0.1511 & 45.44 \\
14 & 80 & 300 & 0.02112 & 0.1501 & 68.91 \\
15 & 80 & 500 & 0.02847 & 0.1350 & 118.16 \\
16 & 120 & 100 & 0.03829 & 0.1381 & 38.70 \\
17 & 120 & 200 & 0.02567 & 0.1441 & 72.38 \\
18 & 120 & 300 & 0.04694 & 0.1583 & 121.82 \\
19 & 120 & 500 & 0.04334 & 0.1470 & 209.56 \\

\end{longtable}

}

I Table~\ref{tbl-grid-svgd} ses det at 20 partikler og 300 iterationer
giver den bedste balance: std \(= 0{,}013\) på 22 sekunder. Øget
partikelantal over 40 giver ikke konsekvent forbedring --- det er ikke
antallet af partikler der begrænser præcisionen, men partikelspredningen
og antallet af observationer. En lignende grid-søgning for to-ø-modellen
(se Table~\ref{tbl-grid-bavian}) bekræfter den samme anbefaling.

En anden vigtig kalibrering er effekten af datamængde.
Table~\ref{tbl-nobs} viser hvordan std falder med stigende \(n\).

\begin{table}

\caption{\label{tbl-nobs}Effekt af antal observationer på SVGD-præcision
(sand \(\theta=7\), Adamelia(\(0.2\)), \(20\) partikler, \(500\)
iterationer). Std falder fra \(0.036\) ved \(n=500\) til \(0.014\) ved
\(n=10{,}000\), svarende til \(1/\sqrt{n}\)-skalering. Afkastet er
faldende over \(n=2000\) og yderligere data forbedrer kun præcisionen
marginalt.}

\centering{

\begin{verbatim}
Effekt af n_obs (Adamelia(0.2), 20 partikler, 500 iter):
 $n_{\text{obs}}$  $\hat\theta$     Std   Bias
              500        6.9072 0.03640 0.0928
             1000        7.1944 0.01991 0.1944
             2000        7.0622 0.03292 0.0622
             5000        7.0404 0.01630 0.0404
            10000        7.0800 0.01413 0.0800
\end{verbatim}

}

\end{table}%

Table~\ref{tbl-nobs} viser at std falder støt med stigende \(n\): fra
\(0{,}036\) ved \(n=500\) til \(0{,}014\) ved \(n=10{,}000\). Afkastet
er aftagende over \(n=2000\), hvilket begrunder at bavian-analyserne
bruger \(n_\text{obs} \approx 3000\) loci. Mere data forbedrer
præcisionen marginalt, men den bindende faktor er typisk biologisk
variation, ikke statistisk støj.

\subsection{Posterior predictive check og
standardkonfiguration}\label{posterior-predictive-check-og-standardkonfiguration}

Som afsluttende tjek af den valgte konfiguration udføres et posterior
predictive check: man simulerer data fra den estimerede model og
sammenligner med de observerede data. Hvis modellen er korrekt, bør de
simulerede data ligne de observerede. Figure~\ref{fig-ppc} viser
resultatet.

\begin{figure}[H]

\centering{

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-02_svgd_inferens_basis-fig-ppc-output-1.pdf}}

}

\subcaption{\label{fig-ppc-1}Posterior predictive check for standard
SVGD-konfiguration. Venstre: histogram af observerede TMRCA-tider (blå)
og model-PDF evalueret ved posterior-mean \(\hat{\theta}\) (orange
kurve); god overensstemmelse bekræfter modelfit. Højre: simulerede
TMRCA-histogrammer fra \(50\) posterior-samples (grå) med observerede
tider (blå) --- overlappet bekræfter at posterioren er kalibreret.}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-02_svgd_inferens_basis-fig-ppc-output-2.pdf}}

}

\subcaption{\label{fig-ppc-2}}

}

\caption{\label{fig-ppc}}

\end{figure}%

Figure~\ref{fig-ppc} viser en tæt overensstemmelse mellem observerede
data og model --- den teoretiske fordeling baseret på
posterior-gennemsnittet følger histogrammet over hele fordelingen. Det
estimerede posterior-gennemsnit er \(\hat{\theta}=7{,}02\) mod sand
\(\theta=7{,}0\), en relativ afvigelse på under \(0{,}3\%\). Det viser
at inferensproceduren kan genfinde den sande parameterværdi med høj
præcision.

Den endelige standardkonfiguration til alle efterfølgende analyser er
baseret på alle ovenstående tests og sammenfattet i
Table~\ref{tbl-standard-config}.

\begin{table}

\caption{\label{tbl-standard-config}Standard SVGD-konfiguration der
anvendes i alle efterfølgende notebooks (NB03--NB07) baseret på de
systematiske test i NB02. Optimizer: Adamelia(\(0.2\)); Prior: DataPrior
(Wattersons estimator); Partikler: \(20\); Iterationer (1 parameter):
\(300\).}

\centering{

\begin{verbatim}
==================================================
=== STANDARD SVGD-KONFIGURATION TIL NB03-NB07 ===
==================================================
Optimizer:              Adamelia($0.2$)
Prior (coalescent):     DataPrior (MoM)
Partikler (test):       20
Iterationer (1-param):  300
==================================================
\end{verbatim}

}

\end{table}%

Standardkonfigurationen bruges i alle efterfølgende analyser i
NB03--NB07. Den er ikke en global optimal løsning for alle mulige
problemer, men den bedste afvejning for bavian-realistiske parametre og
datamængder.

\section{Numerisk præcision og
beregningstid}\label{numerisk-pruxe6cision-og-beregningstid}

En praktisk vigtig egenskab ved phasic er om de grafbaserede beregninger
er numerisk stabile for de prøvestørrelser og parametre der bruges i
bavian-analysen. Hvis standard 64-bit floating-point aritmetik giver for
store fejl, ville det kræve langsom høj-præcisionsaritmetik (MPFR).
Table~\ref{tbl-præcision} sammenligner de to for \(n=2\) til \(17\).

{

\begin{longtable}[]{@{}lllllllll@{}}

\caption{\label{tbl-præcision}Numerisk præcision for Kingmans
coalescent: dobbelt-præcision (64-bit) vs.~MPFR 128-bit for \(n=2\) til
\(17\). Kolonnen ``\(\mathbb{E}[H]\) dobbelt'' og ``\(\mathbb{E}[H]\)
MPFR'' er identiske til mindst 6 decimaler. Den relative fejl er aldrig
over \(4\times 10^{-16}\), tæt på maskin-epsilon
(\(2.2\times 10^{-16}\)). Dobbelt-præcision er tilstrækkelig for alle
prøvestørrelser relevante for bavian-analysen (\(n\leq 6\)).}

\tabularnewline

\toprule\noalign{}
& \$n\$ & Hjørner & \$\textbackslash mathbb\{E\}{[}H{]}\$ dobbelt &
\$\textbackslash mathbb\{E\}{[}H{]}\$ MPFR &
\$\textbackslash mathbb\{E\}{[}H{]}\$ analytisk & Rel fejl
\$\textbackslash mathbb\{E\}{[}H{]}\$ & Abs fejl \$2.\$ mom. & Abs fejl
\$5.\$ mom. \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 2 & 3 & 1.000000 & 1.000000 & 1.000000 & 0.00e+00 & 0.00e+00 &
N/A \\
1 & 3 & 4 & 1.333333 & 1.333333 & 1.333333 & 0.00e+00 & 4.44e-16 &
N/A \\
2 & 4 & 6 & 1.500000 & 1.500000 & 1.500000 & 1.48e-16 & 0.00e+00 &
N/A \\
3 & 5 & 8 & 1.600000 & 1.600000 & 1.600000 & 1.39e-16 & 0.00e+00 &
2.84e-14 \\
4 & 6 & 12 & 1.666667 & 1.666667 & 1.666667 & 1.33e-16 & 0.00e+00 &
0.00e+00 \\
5 & 7 & 16 & 1.714286 & 1.714286 & 1.714286 & 0.00e+00 & 8.88e-16 &
5.68e-14 \\
6 & 8 & 23 & 1.750000 & 1.750000 & 1.750000 & 1.27e-16 & 8.88e-16 &
0.00e+00 \\
7 & 9 & 31 & 1.777778 & 1.777778 & 1.777778 & 1.25e-16 & 0.00e+00 &
5.68e-14 \\
8 & 10 & 43 & 1.800000 & 1.800000 & 1.800000 & 2.47e-16 & 8.88e-16 &
5.68e-14 \\
9 & 11 & 57 & 1.818182 & 1.818182 & 1.818182 & 1.22e-16 & 8.88e-16 &
0.00e+00 \\
10 & 12 & 78 & 1.833333 & 1.833333 & 1.833333 & 2.42e-16 & 8.88e-16 &
0.00e+00 \\
11 & 13 & 102 & 1.846154 & 1.846154 & 1.846154 & 3.61e-16 & 8.88e-16 &
1.14e-13 \\
12 & 14 & 136 & 1.857143 & 1.857143 & 1.857143 & 3.59e-16 & 0.00e+00 &
0.00e+00 \\
13 & 15 & 177 & 1.866667 & 1.866667 & 1.866667 & 1.19e-16 & 1.78e-15 &
5.68e-14 \\
14 & 16 & 232 & 1.875000 & 1.875000 & 1.875000 & 4.74e-16 & 1.78e-15 &
0.00e+00 \\
15 & 17 & 298 & 1.882353 & 1.882353 & 1.882353 & 1.18e-16 & 8.88e-16 &
0.00e+00 \\

\end{longtable}

}

Table~\ref{tbl-præcision} viser at den relative fejl i \(\mathbb{E}[H]\)
er under \(10^{-15}\) for alle prøvestørrelser op til \(n=17\) --- det
er tæt på grænsen for hvad computeren overhovedet kan skelne fra nul
(maskin-epsilon er \(\approx 2{,}2 \times 10^{-16}\)). Det er ikke
nødvendigt at aktivere MPFR høj-præcisionsaritmetik for de
prøvestørrelser der bruges i bavian-analysen.
Figure~\ref{fig-præcision-fejlvækst} viser fejlvæksten som funktion af
\(n\) for alle beregnede størrelser.

\begin{figure}[H]

\centering{

\includegraphics[width=6.125in,height=3.10417in]{index_files/figure-latex/..-notebooks-04_numerical_precision_and_scaling-fig-prcision-fejlvkst-output-1.png}

}

\caption{\label{fig-præcision-fejlvækst}Relativ præcisionsfejl i
\(\mathbb{E}[H]\) (blå) og \(2.\) moment (orange) som funktion af
prøvestørrelse \(n=2\) til \(17\). Begge kurver forbliver under
\(10^{-14}\) for alle \(n\), langt under den accepterede tolerance på
\(10^{-6}\). Den svage stigning med \(n\) skyldes akkumulering af
floating-point afrundingsfejl i matrixoperationerne, ikke strukturelle
fejl i phasic.}

\end{figure}%

Figure~\ref{fig-præcision-fejlvækst} bekræfter at fejlen er lav og
stabil over hele det relevante \(n\)-interval. Der er ingen tegn på
opbygning af numeriske fejl med stigende \(n\).

Den næste vigtige egenskab er beregningstid og hukommelsesforbrug. Det
er afgørende for den praktiske anvendelighed i bavian-analysen, hvor
SVGD kræver tusindvis af evaluationer af coalescentgrafen.
Table~\ref{tbl-profile} viser de målte beregningstider og RAM-forbrug.

{

\begin{longtable}[]{@{}llllllll@{}}

\caption{\label{tbl-profile}Profilering af beregningstid og RAM-forbrug
som funktion af prøvestørrelse \(n=2\) til \(15\). RAM-forbrug er under
\(7\) KB selv ved \(n=15\) (kolonnen ``RAM (KB)'').
\(\mathbb{E}[H]\)-beregning tager under \(0.3\) ms; \(10\) momenter
under \(0.06\) ms for alle \(n\). PDF-evaluering dominerer ved høj \(n\)
men er stadig under \(35\) ms. Grafkonstruktion er under \(0.02\)
sekunder for alle \(n\leq 15\).}

\tabularnewline

\toprule\noalign{}
& n & hjørner & Bygge-tid (s) &
\$\textbackslash mathbb\{E\}{[}H{]}\$-tid (ms) & 10 mom.-tid (ms) &
PDF-tid (ms) & Peak RAM (KB) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 2 & 3 & 0.0033 & 0.061 & 0.013 & 0.466 & 1034.0 \\
1 & 3 & 4 & 0.0030 & 0.322 & 0.016 & 0.533 & 1033.6 \\
2 & 4 & 6 & 0.0142 & 0.092 & 0.016 & 1.664 & 1034.3 \\
3 & 5 & 8 & 0.0039 & 0.159 & 0.016 & 1.262 & 1035.3 \\
4 & 6 & 12 & 0.0054 & 0.083 & 0.015 & 2.341 & 1037.1 \\
5 & 7 & 16 & 0.0032 & 0.095 & 0.022 & 2.079 & 1039.1 \\
6 & 8 & 23 & 0.0032 & 0.087 & 0.175 & 3.140 & 1043.9 \\
7 & 9 & 31 & 0.0039 & 0.096 & 0.019 & 4.737 & 1054.4 \\
8 & 10 & 43 & 0.0039 & 0.123 & 0.021 & 6.479 & 1068.6 \\
9 & 11 & 57 & 0.0044 & 0.138 & 0.033 & 9.444 & 1087.0 \\
10 & 12 & 78 & 0.0047 & 0.170 & 0.029 & 13.084 & 1114.9 \\
11 & 13 & 102 & 0.0114 & 0.219 & 0.038 & 19.004 & 1151.1 \\
12 & 14 & 136 & 0.0079 & 0.461 & 0.069 & 26.583 & 1203.5 \\
13 & 15 & 177 & 0.0082 & 0.345 & 0.062 & 34.329 & 1271.2 \\

\end{longtable}

}

Figure~\ref{fig-skalering-states} viser at tilstandsrummet vokser
polynomielt mens beregningstiden vokser meget moderat.

\begin{figure}[H]

\centering{

\includegraphics[width=10.30208in,height=4.13542in]{index_files/figure-latex/..-notebooks-04_numerical_precision_and_scaling-fig-skalering-states-output-1.png}

}

\caption{\label{fig-skalering-states}Beregningsmæssig skalering med
prøvestørrelse \(n\). Øverst venstre: tilstandsrumsudvækst fra \(3\)
tilstande (\(n=2\)) til \(177\) tilstande (\(n=15\)) vokser polynomielt
(blå punkter med rød regressionslinje). Øverst højre:
grafkonstruktionstid (blå) og \(\mathbb{E}[H]\)-beregningstid (orange)
stiger moderat. Nederst: RAM-forbrug (blå, venstre akse) og
PDF-beregningstid (orange, højre akse) viser at \(n=4\) til \(n=6\) er
en effektiv afvejning af tilstandsrumskapacitet og beregningstid.}

\end{figure}%

Figure~\ref{fig-skalering-states} viser at tilstandsrummet vokser
polynomielt fra 3 tilstande ved \(n=2\) til 177 ved \(n=15\), men at
beregningstiden og RAM-forbruget vokser meget moderat. Det bekræfter at
dobbelt-præcision er tilstrækkelig og at phasic er beregningsmæssigt
effektivt for de prøvestørrelser der bruges i bavian-analysen.

For to-ø modellen med bavian-realistiske parametre er der lavet en
separat grid-søgning for at finde den optimale kombination af partikler
og iterationer. Table~\ref{tbl-grid-bavian} viser resultaterne.

{

\begin{longtable}[]{@{}llllll@{}}

\caption{\label{tbl-grid-bavian}Grid-søgning over partikler og
iterationer for to-ø modellen med bavian-baseline parametre
(\(\theta_0=0.7\), \(\theta_1=1.0\), \(n=3000\)). Kombinationen \(20\)
partikler, \(300\) iterationer giver summed std \(=0.053\) og bias
\(=0.063\) på \(131\) sekunder og er den bedste afvejning af præcision
og beregningstid. \(40\) partikler og \(200\) iterationer (\(161\) sek.)
giver summed std \(=0.314\) --- væsentlig ringere trods højere
computertid, fordi to-ømodellens højere-dimensionelle parameterrum
kræver tilstrækkelig mange iterationer snarere end mange partikler.}

\tabularnewline

\toprule\noalign{}
& Particles & Iterations & std\_sum & bias\_sum & Tid\_s \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 20 & 200 & 0.06168 & 0.08982 & 89.25 \\
1 & 20 & 300 & 0.05288 & 0.06285 & 131.12 \\
2 & 20 & 400 & 0.30469 & 0.03424 & 174.58 \\
3 & 20 & 500 & 0.30646 & 0.03771 & 213.57 \\
4 & 40 & 200 & 0.31413 & 0.02545 & 161.11 \\
5 & 40 & 300 & 0.23378 & 0.06021 & 239.00 \\
6 & 40 & 400 & 0.09600 & 0.07316 & 325.68 \\
7 & 40 & 500 & 0.31366 & 0.03034 & 405.59 \\
8 & 60 & 200 & 0.08227 & 0.06517 & 244.05 \\
9 & 60 & 300 & 0.20577 & 0.05455 & 348.99 \\
10 & 60 & 400 & 0.31999 & 0.04031 & 460.47 \\
11 & 60 & 500 & 0.32549 & 0.03079 & 580.98 \\
12 & 80 & 200 & 0.11123 & 0.08194 & 312.04 \\
13 & 80 & 300 & 0.19702 & 0.05391 & 465.35 \\
14 & 80 & 400 & 0.10677 & 0.06983 & 619.48 \\
15 & 80 & 500 & 0.20256 & 0.06985 & 776.34 \\

\end{longtable}

}

Table~\ref{tbl-grid-bavian} viser at 20 partikler og 300 iterationer
giver den bedste balance for to-ø modellen: std\_sum \(= 0{,}053\) på
131 sekunder. Det er den samme anbefaling som for
enkelt-populationsmodellen, hvilket bekræfter at standardkonfigurationen
er robust.

\section{To-ø modellen: identificerbarhed og asymmetrisk
migration}\label{to-uxf8-modellen-identificerbarhed-og-asymmetrisk-migration}

Introduktionen forklarede to-ø modellen og tilstandsrummet. Her
undersøges de statistiske egenskaber: hvornår er parametrene
identificerbare, og hvad sker der ved grænsetilfælde?

Det centrale spørgsmål er, om man kan skelne coalescentraten
\(\theta_0\) fra migrationsraten \(\theta_1\). En vigtig observation er
at \(\mathbb{E}[\text{TMRCA}]\) som funktion af migrationsraten ikke er
monoton. Figure~\ref{fig-migration-tmrca} viser dette.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-migration-tmrca-output-1.pdf}}

}

\caption{\label{fig-migration-tmrca}\(\mathbb{E}[\text{TMRCA}]\)
(venstre) og \(\text{Var}[\text{TMRCA}]\) (højre) som funktion af
migrationsrate \(\theta_1\) på log-skala (\(\theta_0=0.7\), \(n=2\)).
Venstre: \(\mathbb{E}[\text{TMRCA}]\) er identisk ved \(\theta_1=0\)
(ingen migration; TMRCA bestemmes af \(\theta_0\) alene) og flader ud
ved \(\theta_1>2\) fordi høj migration effektivt slår de to øer sammen
til én panmiktisk population. Højre: Variansen er størst ved lav
migration og falder asymptotisk. Den flade
\(\mathbb{E}[\text{TMRCA}]\)-kurve ved høj \(\theta_1\) forklarer den
lave identifiability i høj-migrationsscenarierne.}

\end{figure}%

Figure~\ref{fig-migration-tmrca} viser noget afgørende: begge
yderpunkter --- ingen migration (\(\theta_1 \to 0\)) og fuldstændig
panmixi (\(\theta_1 \to \infty\)) --- giver præcis samme forventede
coalescenttid på \(2{,}857\). Det er kun ved moderate migrationsrater at
\(\mathbb{E}[\text{TMRCA}]\) skiller sig ud fra yderpunkterne. Det
betyder at data ikke kan afgøre om en given TMRCA-fordeling skyldes lav
eller høj migration uden information om coalescentraten --- og omvendt.

Konsekvensen ses direkte i de estimerede posteriors.
Figure~\ref{fig-pairwise-lav} viser pairwise-posterioren ved lav
migration.

\begin{figure}[H]

\centering{

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-pairwise-lav-output-1.pdf}}

}

\subcaption{\label{fig-pairwise-lav-1}Pairwise posterior for lav
migrationsscenarie (\(\theta_0=0.7\), \(\theta_1=0.2\), \(n=5000\)).
Diagonal: marginale histogrammer. Off-diagonal: joint scatter.
\(\theta_1=0.2\) er meget lav migration og genfindes præcist (std
\(=0.048\)) fordi lav migration giver en markant TMRCA-forlængelse.
Sande værdier er markeret med stiplede linjer.}

\centering{

\begin{verbatim}
<Figure size 900x400 with 0 Axes>
\end{verbatim}

}

\subcaption{\label{fig-pairwise-lav-2}}

}

\caption{\label{fig-pairwise-lav}}

\end{figure}%

Ved lav migration er posterioren bred og negativt korreleret.
Figure~\ref{fig-pairwise-moderat} viser det moderate scenarie.

\begin{figure}[H]

\centering{

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-pairwise-moderat-output-1.pdf}}

}

\subcaption{\label{fig-pairwise-moderat-1}Pairwise posterior for moderat
migrationsscenarie (\(\theta_0=0.7\), \(\theta_1=1.0\), \(n=5000\)).
Diagonal: marginale histogrammer. Off-diagonal: joint scatter.
\(\theta_1=1.0\) genfindes med std \(=0.330\) --- større usikkerhed end
ved lav migration fordi TMRCA er mindre sensitiv over for \(\theta_1\) i
dette interval. Sande værdier er markeret med stiplede linjer.}

\centering{

\begin{verbatim}
<Figure size 900x400 with 0 Axes>
\end{verbatim}

}

\subcaption{\label{fig-pairwise-moderat-2}}

}

\caption{\label{fig-pairwise-moderat}}

\end{figure}%

Ved moderat migration er posterioren smallere og parametre er
identificerbare. Figure~\ref{fig-pairwise-hoj} viser hvad der sker ved
høj migration.

\begin{figure}[H]

\centering{

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-pairwise-hoj-output-1.pdf}}

}

\subcaption{\label{fig-pairwise-hoj-1}Pairwise posterior for høj
migrationsscenarie (\(\theta_0=0.7\), \(\theta_1=5.0\), \(n=5000\)).
Diagonal: marginale histogrammer. Off-diagonal: joint scatter.
\(\theta_1=5.0\) estimeres med std \(=9.221\) --- meget høj migration er
næsten uidentificerbar fordi \(\mathbb{E}[\text{TMRCA}]\) er næsten
konstant ved \(\theta_1>2\). Sande værdier er markeret med stiplede
linjer.}

\centering{

\begin{verbatim}
<Figure size 900x400 with 0 Axes>
\end{verbatim}

}

\subcaption{\label{fig-pairwise-hoj-2}}

}

\caption{\label{fig-pairwise-hoj}}

\end{figure}%

Ved høj migration er posterioren igen bred og migrationsraten er
praktisk uidentificerbar. Det er ikke et numerisk problem --- det er den
statistiske virkelighed at de to situationer producerer næsten identiske
data. Table~\ref{tbl-identifiability} kvantificerer resultaterne
præcist.

{

\begin{longtable}[]{@{}llllllllll@{}}

\caption{\label{tbl-identifiability}SVGD-estimater for tre
migrationsscenarier med \(n=5000\) observationer. Sande parametre er
\(\theta_0=0.7\) og \(\theta_1\in{0.2, 1.0, 5.0}\). Koalescentraten
\(\theta_0\) estimeres konsekvent præcist (std \(0.017{-}0.079\)) uanset
migrationsscenarie. Migrationsraten \(\theta_1\) er identificerbar ved
lav (\(\hat{\theta}_1=0.194\pm 0.048\)) og moderat
(\(\hat{\theta}_1=0.974\pm 0.330\)) migration, men er næsten
uidentificerbar ved høj migration (\(\hat{\theta}_1=3.56\pm 9.22\))
fordi \(\mathbb{E}[\text{TMRCA}]\) flader ud.}

\tabularnewline

\toprule\noalign{}
& Scenarie & Sand \$\textbackslash theta\_0\$ & Sand
\$\textbackslash theta\_1\$ & Est. \$\textbackslash theta\_0\$ & Est.
\$\textbackslash theta\_1\$ & Std \$\textbackslash theta\_0\$ & Std
\$\textbackslash theta\_1\$ & Bias \$\textbackslash theta\_0\$ & Bias
\$\textbackslash theta\_1\$ \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & Lav migration & 0.7 & 0.2 & 0.712 & 0.194 & 0.0793 & 0.0480 & 0.012
& 0.006 \\
1 & Moderat migration & 0.7 & 1.0 & 0.685 & 0.974 & 0.0567 & 0.3297 &
0.015 & 0.026 \\
2 & Høj migration & 0.7 & 5.0 & 0.690 & 5.623 & 0.0548 & 2.7397 & 0.010
& 0.623 \\

\end{longtable}

}

Coalescentraten estimeres præcist i alle tre scenarier (std
\(0{,}057\)--\(0{,}079\)), uanset hvilket migrationsregime der er tale
om. Migrationsraten estimeres fint ved moderat migration
(\(\hat{\theta}_1 = 0{,}974 \pm 0{,}330\) mod sand \(1{,}0\)), men ved
høj migration er posterior-std \(9{,}221\) mod sand \(\theta_1 = 5{,}0\)
--- usikkerheden er større end selve estimatet. Migrationsparameteren
kan i praksis ikke bestemmes i dette scenarie. For bavian-analysen
betyder det at \(N_e\) er en pålidelig størrelse at rapportere i alle
scenarier, mens migrationsrater kun er meningsfulde at fortolke ved
moderate niveauer.

En naturlig sammenligning er med den klassiske method-of-moments (MoM)
estimator. Figure~\ref{fig-mom-vs-svgd} viser forholdet visuelt.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-mom-vs-svgd-output-1.pdf}}

}

\caption{\label{fig-mom-vs-svgd}\(\hat{\theta}_0\) (venstre) og
\(\hat{\theta}_1\) (højre) estimeret via MoM (blå) og SVGD (orange) som
funktion af prøvestørrelse \(n\) (sand \(\theta=[0.7, 1.0]\)).
MoM-estimatet for \(\theta_1\) er ustabilt ved \(n<1000\) med bias op
til \(73\%\). SVGD (orange) giver konsekvent bedre estimater for begge
parametre ved alle \(n\) og leverer usikkerhedskvantificering. Sande
værdier er vist med stiplede sorte linjer.}

\end{figure}%

Table~\ref{tbl-mom-bavian} kvantificerer sammenligningen over fem
bavian-realistiske parameterscenarier.

{

\begin{longtable}[]{@{}lllllllll@{}}

\caption{\label{tbl-mom-bavian}MoM vs.~SVGD over fem bavian-realistiske
parameterscenarier med \(n=3000\). MoM giver acceptable estimater for
\(\theta_0\) (bias \(<5%
\)) men systematisk høj bias for \(\theta_1\): ved \([0.7, 1.0]\)
estimerer MoM \(\hat{\theta}_1=0.965\) (god), men ved \([0.5, 5.0]\)
giver MoM \(\hat{\theta}_1=3.17\) mod sand \(5.0\) (bias \(37%
\)). SVGD giver bedre estimater i \(4/5\) scenarier og leverer posterior
med usikkerhedskvantificering som MoM mangler.}

\tabularnewline

\toprule\noalign{}
& Sand {[}t0, t1{]} & MoM t0 & MoM t1 & SVGD t0 mean & SVGD t0 std &
SVGD t1 mean & SVGD t1 std & MoM ok? \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & {[}0.3, 0.5{]} & 0.3001 & 0.7864 & 0.2896 & 0.03730 & 0.4739 &
0.14132 & Nej \\
1 & {[}0.7, 1.0{]} & 0.7089 & 0.9654 & 0.6916 & 0.07311 & 1.3300 &
0.31825 & Ja \\
2 & {[}1.5, 2.0{]} & 1.5391 & 2.4935 & 1.5229 & 0.11425 & 2.2749 &
0.37547 & Ja \\
3 & {[}0.5, 5.0{]} & 0.5043 & 3.1737 & 0.4386 & 0.10498 & 2.7585 &
1.79761 & Nej \\
4 & {[}2.0, 0.1{]} & 1.8489 & 0.0881 & 1.9562 & 0.00613 & 0.1037 &
0.00165 & Ja \\

\end{longtable}

}

Table~\ref{tbl-mom-bavian} viser at MoM systematisk overvurderer
migrationsraten i næsten alle scenarier. Ved
\([\theta_0, \theta_1] = [0{,}5, 5{,}0]\) giver MoM
\(\hat{\theta}_1 = 3{,}17\) mod sand \(5{,}0\) --- en bias på \(37\%\).
SVGD giver gennemgående bedre estimater for \(\theta_1\) og er desuden
den eneste metode der leverer en fuld posterior med
usikkerhedskvantificering. For Coalescentraten \(\theta_0\) er begge
metoder rimelige, men SVGD-intervallerne giver information om usikkerhed
som MoM ikke kan.

Valget af prior til migrationsparameteren har direkte konsekvenser for
inferensens kvalitet. Table~\ref{tbl-prior-migration} sammenligner
GaussPrior og HalfCauchyPrior til migrationsparametre.

{

\begin{longtable}[]{@{}llllll@{}}

\caption{\label{tbl-prior-migration}Sammenligning af GaussPrior(bred) og
HalfCauchyPrior til to-ø modellen (sand \(\theta=[0.7, 0.9]\),
\(n=3000\)). GaussPrior giver \(\hat{\theta}_1=0.967\pm 0.250\) og er
tæt på sandhed. HalfCauchyPrior er positiv-støttet og biologisk korrekt
for en migrationsrate, men giver her \(\hat{\theta}_0=2.155\pm 9.795\)
indikerende numerisk ustabilitet ved dette parameterrum.
GaussPrior(bred) anbefales til to-ømodellen; HalfCauchy bør bruges med
forsigtighed ved lav migration.}

\tabularnewline

\toprule\noalign{}
& Prior & \$\textbackslash theta\_0\$ mean & \$\textbackslash theta\_0\$
std & \$\textbackslash theta\_1\$ mean & \$\textbackslash theta\_1\$
std \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & GaussPrior (bred) & 0.6504 & 0.07299 & 0.9668 & 0.25004 \\
1 & HalfCauchy & 2.1553 & 9.79466 & 0.6410 & 0.39270 \\

\end{longtable}

}

msprime-valideringen bekræfter at implementeringen er korrekt. Den
relative afvigelse i \(\mathbb{E}[\text{TMRCA}]\) er \(0{,}73\%\).

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-two-island-msprime-val-output-1.pdf}}

}

\caption{\label{fig-two-island-msprime-val}msprime-validering af to-ø
modellen (\(\theta_0=0.7\), \(\theta_1=1.0\), ploidy\(=2\)). Venstre:
histogram af simulerede skalerede TMRCA-værdier (blå) sammenlignet med
phasic PDF (orange kurve). Højre: empirisk ECDF (blå trin) versus
analytisk CDF (orange kurve). Den gode overensstemmelse bekræfter at
to-ø grafen og msprime-simuleringen bruger samme parametriseringsskala.}

\end{figure}%

SVGD-inferens giver \(\hat{\theta}_0 = 0{,}695 \pm 0{,}052\) og
\(\hat{\theta}_1 = 0{,}827 \pm 0{,}141\) (sande værdier \(0{,}7\) og
\(1{,}0\)). Konvergensforløb, pairwise posterior og HDR-plot vises i
Figure~\ref{fig-two-island-msp-konvergens},
Figure~\ref{fig-two-island-msp-pairwise} og
Figure~\ref{fig-twoisland-hdr}.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-two-island-msp-konvergens-output-1.pdf}}

}

\caption{\label{fig-two-island-msp-konvergens}Konvergensplot for
SVGD-inferens på msprime-simulerede to-ø data. Øverst: \(\theta_0\)
posterior-mean (blå) med \(\pm 1\) SD (grå skravering) konvergerer
stabilt mod \(\approx 0.70\) inden for \(100\) iterationer. Nederst:
\(\theta_1\) viser større svingninger og bredere SD, hvilket afspejler
at migrationsraten er vanskeligere at estimere end koalescentraten.}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-two-island-msp-pairwise-output-1.pdf}}

}

\caption{\label{fig-two-island-msp-pairwise}Pairwise posterior for to-ø
SVGD-inferens på msprime-simulerede data. Diagonalen viser marginale
posterior-histogrammer for \(\theta_0\) (øverst) og \(\theta_1\)
(nederst). Off-diagonal scatter viser den joint posterior: den
elliptiske form afspejler en svag negativ korrelation mellem
\(\theta_0\) og \(\theta_1\). Sande parametre (\(\theta_0=0.7\),
\(\theta_1=1.0\)) er markeret med stiplede linjer.}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-twoisland-hdr-output-1.pdf}}

}

\caption{\label{fig-twoisland-hdr}Highest Density Region (HDR) plot for
to-ø model SVGD posterior. Det \(50\%\)-HDR (mørkere) og \(95\%\)-HDR
(lysere) viser joint posterior over \(\theta_0\) og \(\theta_1\). Den
elliptiske form afspejler den negative korrelation: ved lav
koalescentrate \(\theta_0\) er den estimerede migrationsrate
\(\theta_1\) tendentielt højere. Sande parametre (\(\theta_0=0.7\),
\(\theta_1=1.0\)) er markeret med kryds.}

\end{figure}%

Figure~\ref{fig-twoisland-hdr} viser den elliptiske form af den fælles
posterior, der afspejler den negative korrelation. \(95\%\)-HDR-regionen
er relativt smal for \(\theta_0\) men bred for \(\theta_1\) ---
konsistent med de tidligere identificerbarhedsresultater.

Et vigtigt biologisk spørgsmål er, om asymmetrisk migration --- to
separate rater \(m_{12} \neq m_{21}\) --- overhovedet kan identificeres.
Med \(n=2\) er svaret nej, som Figure~\ref{fig-asym-n2-pairwise} viser.

\begin{figure}[H]

\centering{

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-asym-n2-pairwise-output-1.pdf}}

}

\subcaption{\label{fig-asym-n2-pairwise-1}Pairwise posterior for
asymmetrisk to-ø model med \(n=2\) linjer og asymmetriske
migrationsrater (\(m_{12}=2.0\), \(m_{21}=0.3\)). De to migrationsrater
er stærkt sammenblandede: den joint posterior (scatter) viser at næsten
enhver kombination af \(m_{12}\) og \(m_{21}\) der summerer til en fast
total migrationsrate er konsistent med data. Med \(n=2\) er de to
retninger uidentificerbare.}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-asym-n2-pairwise-output-2.pdf}}

}

\subcaption{\label{fig-asym-n2-pairwise-2}}

}

\caption{\label{fig-asym-n2-pairwise}}

\end{figure}%

Med blot to prøver er de to rater fuldstændig sammenblandede --- mange
kombinationer af \(m_{12}\) og \(m_{21}\) er næsten lige sandsynlige.
Posteriorfordelingens form viser at data ikke indeholder nok information
til at skelne de to retninger. Det kræver mindst \(n=4\) prøver og mange
observationer. Figure~\ref{fig-asym4-pairwise} viser resultatet med
\(n=4\) og 5000 observationer.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-asym4-pairwise-output-1.pdf}}

}

\caption{\label{fig-asym4-pairwise}Pairwise posterior for asymmetrisk
to-ø model med \(n=4\) linjer (\(n_{\text{obs}}=5000\), asymmetriske
rater \(m_{12}=2.0\), \(m_{21}=0.3\)). Begge rater er identificerbare:
\(\hat{m}_{12}=2.015\pm 0.627\) (sand \(2.0\)) og
\(\hat{m}_{21}=0.285\pm 0.039\) (sand \(0.3\)). Korrelationen er positiv
men moderat. At øge \(n\) fra \(2\) til \(4\) er afgørende for at
identificere asymmetri.}

\end{figure}%

Med \(n=4\) er begge rater identificerbare.
Figure~\ref{fig-asym4-konvergens} viser konvergensforløbet.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-03_svgd_two_island-fig-asym4-konvergens-output-1.pdf}}

}

\caption{\label{fig-asym4-konvergens}Konvergensplot for asymmetrisk to-ø
model med \(n=4\) og \(n_{\text{obs}}=5000\). Blå linje: posterior-mean;
grå skravering: \(\pm 1\) SD. \(m_{12}\) (øverst) konvergerer stabilt;
\(m_{21}\) (nederst) er mere variabel men stabiliserer sig inden for
\(200\) iterationer. Final SD afspejler den sande posterior-usikkerhed
og ikke manglende konvergens.}

\end{figure}%

Figure~\ref{fig-asym4-konvergens} viser at begge parametre konvergerer
stabilt inden 400 iterationer. Den lave rate estimeres meget præcist:
\(\hat{m}_{21} = 0{,}285 \pm 0{,}039\) mod sand \(0{,}3\) (bias
\(1{,}5\%\)). Den høje rate er sværere:
\(\hat{m}_{12} = 2{,}015 \pm 0{,}627\) mod sand \(2{,}0\), med en
relativ posterior-std på \(31\%\). Det afspejler den generelle tendens
at høje parameterværdier er sværere at estimere præcist.

For at afslutte NB03 viser Table~\ref{tbl-to-oe-n4-states} de beregnede
forventede TMRCA-tider og varianser for to-ø modellen med \(n=4\) over
hele det bavian-realistiske parameterrum.

\begin{verbatim}
  Removed 29 file(s), preserved directory structure
To-ø model $n=4$: {graph_n4.vertices_length()} tilstande
\end{verbatim}

{

\begin{longtable}[]{@{}llllll@{}}

\caption{\label{tbl-to-oe-n4-states}To-ø modellen med \(n=4\):
tilstandsrum, \(E[\text{TMRCA}]\) og \(\text{Var}[\text{TMRCA}]\) for
bavian-realistiske parametre. \(n=4\) giver \(21\) tilstande mod \(6\)
ved \(n=2\) og forventet TMRCA \(4.389\) ved \(\theta_0=0.7\),
\(\theta_1=1.0\).}

\tabularnewline

\toprule\noalign{}
& \$\textbackslash theta\_0\$ & \$\textbackslash theta\_1\$ &
\$E{[}\textbackslash text\{TMRCA\}{]}\$ &
\$\textbackslash text\{Var\}{[}\textbackslash text\{TMRCA\}{]}\$ &
\$\textbackslash text\{Tilstande\}\$ \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 0.7 & 1.0 & 4.3905 & 11.1399 & 21 \\
1 & 0.7 & 0.2 & 4.5695 & 20.4754 & 21 \\
2 & 0.7 & 5.0 & 4.3100 & 9.6314 & 21 \\
3 & 1.5 & 2.0 & 2.0517 & 2.4578 & 21 \\
4 & 0.3 & 0.5 & 10.2155 & 59.0891 & 21 \\

\end{longtable}

}

Table~\ref{tbl-to-oe-n4-states} viser at momenterne er numerisk stabile
for alle testede parameterkombinationer, og at MPFR ikke er nødvendigt.
Det bekræfter at standardkonfigurationen er tilstrækkelig for hele det
bavian-realistiske parameterrum.

\section{Flaskehalse og IM-modellen}\label{flaskehalse-og-im-modellen}

Introduktionen viste SFS under tidsinhomogene modeller og forklarede
IM-modellen konceptuelt. Her undersøges de numeriske egenskaber og hvad
man konkret kan identificere i data.

Et af de mest intuitive spørgsmål er, hvad en flaskehals gør ved
coalescentprocessen. Figure~\ref{fig-bottleneck-cdf} viser effekten af
flaskehalse af varierende dybde på TMRCA-fordelingen.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-05_time_inhomogeneous-fig-bottleneck-cdf-output-1.pdf}}

}

\caption{\label{fig-bottleneck-cdf}CDF og PDF for Kingmans coalescent
under varierende flaskehals-dybde
\(f=N/N_{\text{bottle}}\in\{1, 2, 5, 10, 20\}\). Venstre: CDF viser at
en dyb flaskehals (\(f=20\), mørk blå) fremrykker koalescenttiderne
markant --- CDF stiger stejlt tidligt. Højre: PDF viser den tilhørende
tæthed. En moderat flaskehals (\(f=2\), lysegrøn) ændrer næsten ikke
TMRCA-fordelingen; konstant population (\(f=1\), blå) er referencen
(stiplet).}

\end{figure}%

Figure~\ref{fig-bottleneck-cdf} viser et overraskende resultat: en
moderat flaskehals ændrer meget lidt ved den forventede TMRCA.
Forklaringen er at mange genealogiske linjer allerede har fundet fælles
forfædre inden flaskehalsen. Kun de linjer der overlever op til
flaskehalsen mærker den accelererede coalescent. Det kræver en faktor 20
reduktion i populationsstørrelse, før CDF-formen ændrer sig mærkbart.
SFS-formen er til gengæld mere følsom over for demografiske ændringer,
som Figure~\ref{fig-sfs-bottleneck} viser.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-05_time_inhomogeneous-fig-sfs-bottleneck-output-1.pdf}}

}

\caption{\label{fig-sfs-bottleneck}SFS-formen som funktion af
flaskehals-tidspunkt \(t_{\text{start}}\in\{0.1, 0.3, 0.5, 0.8\}\) ved
fast dybde \(f=10\) og \(n=4\). Forventet grenlængde per frekvensklasse
(blå: singletons, orange: doubletons, grøn: tripletons) normaliseret som
andel. En tidlig flaskehals (\(t_{\text{start}}=0.1\), lys farve) øger
singleton-andelen fordi de nylige externe grene rammes af flaskehalsen
tidligst; sen flaskehals (\(t_{\text{start}}=0.8\), mørk) ændrer næsten
ikke SFS-formen.}

\end{figure}%

Figure~\ref{fig-sfs-bottleneck} viser at SFS-formen ændrer sig mere
markant end TMRCA ved selv moderate flaskehalse --- særligt
singleton-andelen er følsom. Det motiverer at bruge SFS frem for TMRCA
alene til demografisk inferens.

For at give et bredere overblik over hvilke demografiske mønstre der er
identificerbare i data, sammenligner Figure~\ref{fig-multiepoch} fem
scenarier.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-05_time_inhomogeneous-fig-multiepoch-output-1.pdf}}

}

\caption{\label{fig-multiepoch}CDF og PDF for fem demografiske scenarier
med \(n=4\). Konstant population (blå) er referencekoalescent.
Ekspansion (\(N\) øges, orange): CDF stiger stejlt tidligt fordi linjer
koalescerer hurtigt i den fortidige store population. Kontraktion (\(N\)
mindskes, grøn): CDF er fladere og TMRCA trækkes ud. Flaskehals+recovery
(rød): CDF kombinerer tidlig ekspansion og sen kontraktion. Trinvis
vækst (lilla): CDF viser et knæk ved det demografiske skift. Disse
mønstre er udgangspunktet for IM-modellen og SVGD-inferens.}

\end{figure}%

Figure~\ref{fig-multiepoch} viser de karakteristiske mønstre:
kontraktion giver en stejl CDF tidligt, ekspansion giver den fladeste
CDF, og en flaskehals med genopretning viser et knæk i PDF'en ved
epoke-grænsen. Netop disse mønstre er hvad man leder efter i
bavian-genomdataene.

En relateret størrelse er sandsynligheden for at et givet locus ikke har
oplevet rekombination --- dvs. at alle positioner i locus'et deler den
samme genealogi. Det er relevant for valget af locus-længde i analysen.
Figure~\ref{fig-laplace} viser disse sandsynligheder via
Laplace-transformationen af TMRCA-fordelingen.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-05_time_inhomogeneous-fig-laplace-output-1.pdf}}

}

\caption{\label{fig-laplace}Sandsynlighed
\(P(\text{ingen rekombination})\) --- svarende til
Laplace-transformationen af TMRCA-fordelingen --- som funktion af
rekombinationsrate \(\rho\) for tre populationsstørrelser (\(N=0.5\)
blå, \(N=1.0\) orange, \(N=3.0\) grøn). Store populationer (grøn) har
lavere sandsynlighed for fælles topologi over et locus fordi lange
TMRCA-tider øger rekombinationsrisikoen. Kurven aftagende på log-skala
bekræfter eksponentiel struktur.}

\end{figure}%

Figure~\ref{fig-laplace} viser at store populationer har lavere
sandsynlighed for ingen rekombination ved en given \(\rho\), fordi de
lange TMRCA-tider øger chancen for rekombination undervejs. Kurven
aftager eksponentielt, konsistent med den forventede
\(e^{-\rho \cdot \mathbb{E}[T]}\)-sammenhæng.

For IM-modellen er det særligt interessant at se, hvordan
split-tidspunktet påvirker \(\mathbb{E}[\text{TMRCA}]\).
Figure~\ref{fig-im-tmrca} viser dette.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-05_time_inhomogeneous-fig-im-tmrca-output-1.pdf}}

}

\caption{\label{fig-im-tmrca}\(\mathbb{E}[\text{TMRCA}]\) for
IM-modellen som funktion af split-tidspunkt \(t_s\) (coalescent-enheder,
\(\theta_0=0.5\), \(\theta_1=1.0\)). Blå kurve: IM-model beregnet via
phasic; orange stiplet linje: to-ø model uden split
(\(\mathbb{E}[\text{TMRCA}]=2.0\)); grøn stiplet linje: panmiktisk
ancestral population (\(\mathbb{E}[\text{TMRCA}]=1.0\)). Et tidligt
split (\(t_s=0.1\)) giver \(\mathbb{E}[\text{TMRCA}]=1.178\) fordi
linjerne hurtigt når den fælles ancestrale pulje; ved sent split
(\(t_s=5.0\)) nærmer IM-modellen sig to-ø grænsen (\(2.386\)).}

\end{figure}%

\begin{verbatim}
To-ø uden split:         E[TMRCA] = 2.0000
Ancestral (panmiktisk):  E[TMRCA] = 1.0000
IM-model ved t_s=0.1:   E[TMRCA] = 1.1781
IM-model ved t_s=5.0:   E[TMRCA] = 2.3857
\end{verbatim}

Figure~\ref{fig-im-tmrca} viser den forventede TMRCA som funktion af
split-tidspunktet \(t_s\). Ved tidligt split (\(t_s = 0{,}1\)) er
\(\mathbb{E}[\text{TMRCA}] = 1{,}178\) --- linjerne når hurtigt den
fælles ancestrale pulje. Den fuldt panmiktiske ancestrale population
giver \(\mathbb{E}[\text{TMRCA}] = 1{,}000\), og to-ø modellen uden
split giver \(2{,}000\). Ved sent split (\(t_s = 5{,}0\)) nærmer
IM-modellen sig to-ø-grænsen med \(\mathbb{E}[\text{TMRCA}] = 2{,}386\).
Denne kurve er vigtig for bavian-analysen: den fortæller hvad
split-tidspunktet konkret betyder for de observerede genealogiske
mønstre.

Figure~\ref{fig-im-epoch-conv} viser et komplet SVGD-konvergensforløb
for IM-modellen. Modellen har 11 tilstande og 6 frie parametre.

\begin{figure}

\centering{

\begin{verbatim}
IM-model tilstande: 11
Parametre: 6
E[TMRCA]: 8.3609
Var[TMRCA]: 87218577791.3540
\end{verbatim}

}

\caption{\label{fig-im-epoch-conv}}

\end{figure}%

Figure~\ref{fig-im-epoch-conv} viser at coalescentraten konvergerer
hurtigt, mens switch-raten og migrationsraten er bredere og kræver flere
iterationer. IM-modellens 6 parametre er sværere at estimere simultant
end enkelt-populations-modellens 1 parameter, men der er ingen tegn på
partikelkollaps eller numerisk instabilitet.

\section{Joint probability-inferens}\label{joint-probability-inferens}

Introduktionen forklarede ARG-modellen og tilstandsrummet. Frem for kun
at bruge TMRCA-tider er det muligt at bruge hele mutationsmønstret per
locus --- antallet af singletons, doubletons og tripletons simultant.
Figure~\ref{fig-joint-graf} viser grafen der bruges til disse
beregninger.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-joint-graf-output-1.pdf}}

}

\caption{\label{fig-joint-graf}Graf-repræsentation af coalescent til
joint probability-inferens (\(n=4\), \(\mu=1.0\),
tot\_reward\_limit\(=3\)). Knuderne (cirklerne) repræsenterer tilstande
i absorptionsprocessen; kanterne viser mulige overgange med tilhørende
rater. De grå tilstande er transiente (koalescent-tilstande); den
markerede tilstand er den absorberende MRCA. Mutationsovergange er
inkluderet som reward-overgange der akkumulerer det observerede site
frequency spectrum.}

\end{figure}%

Figure~\ref{fig-joint-graf} viser at joint probability-grafen er en
udvidelse af coalescentgrafen, hvor mutationsovergange er tilføjet som
reward-overgange der akkumulerer det observerede site frequency
spectrum. Den centrale tekniske parameter er \texttt{tot\_reward\_limit}
som styrer, hvor mange mutationer der maksimalt regnes med per locus.
Table~\ref{tbl-reward-compare} viser sammenhængen mellem limit, deficit
og tabelstørrelse.

{

\begin{longtable}[]{@{}llll@{}}

\caption{\label{tbl-reward-compare}Sammenligning af deficit og
tabelstørrelse som funktion af \texttt{tot\_reward\_limit} ved
\(\mu=1.0\) og sand \(\theta=7\). Limit\(=2\): deficit\(=1.23%
\), tabelstørrelse\(=27\). Limit\(=3\): deficit\(=0.21%
\), tabelstørrelse\(=64\). Limit\(=4\): deficit\(=0.04%
\), tabelstørrelse\(=125\). Limit\(=5\): deficit\(=0.007%
\), tabelstørrelse\(=216\). Limit\(=3\) er den anbefalede afvejning med
deficit under \(0.5%
\) og moderat beregningstid.}

\tabularnewline

\toprule\noalign{}
& limit & reward\_limit deficit & reward\_limit tabelstørrelse \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 2 & 0.01230 & 27 \\
1 & 3 & 0.00211 & 64 \\
2 & 4 & 0.00037 & 125 \\
3 & 5 & 0.00007 & 216 \\

\end{longtable}

}

Deficit er den andel af sandsynlighedsmasse der mistes ved at afskære
lave sandsynligheder. Table~\ref{tbl-deficit-guide} viser hvilke
kombinationer af \(\mu\) og limit der giver deficit under \(5\%\).

{

\begin{longtable}[]{@{}lllll@{}}

\caption{\label{tbl-deficit-guide}Anbefalede \(\mu\)-tot\_reward\_limit
kombinationer med deficit under \(5%
\). \(\mu=0.5\) giver deficit under \(0.03%
\) ved limit\(=2\) og er meget effektiv. \(\mu=1.0\) med limit\(=3\)
giver deficit\(=0.21%
\) og vælges som standardkonfiguration for bavian-analysen. \(\mu=1.5\)
og limit\(=3\) er akkurat acceptabelt (deficit\(=2.44%
\)). \(\mu\geq 2.0\) er uegnet til joint probability-inferens med
moderate reward limits.}

\tabularnewline

\toprule\noalign{}
& \$\textbackslash mu\$ & limit & Deficit & OK \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 0.5 & 2 & 0.0003 & Ja \\
1 & 0.5 & 3 & 0.0000 & Ja \\
2 & 0.5 & 4 & 0.0000 & Ja \\
3 & 0.5 & 5 & 0.0000 & Ja \\
4 & 0.5 & 7 & 0.0000 & Ja \\
5 & 1.0 & 2 & 0.0123 & Ja \\
6 & 1.0 & 3 & 0.0021 & Ja \\
7 & 1.0 & 4 & 0.0004 & Ja \\
8 & 1.0 & 5 & 0.0001 & Ja \\
9 & 1.0 & 7 & 0.0000 & Ja \\
10 & 1.5 & 2 & 0.0768 & Nej \\
11 & 1.5 & 3 & 0.0244 & Ja \\
12 & 1.5 & 4 & 0.0077 & Ja \\
13 & 1.5 & 5 & 0.0025 & Ja \\
14 & 1.5 & 7 & 0.0003 & Ja \\
15 & 2.0 & 2 & 0.2139 & Nej \\
16 & 2.0 & 3 & 0.0989 & Nej \\
17 & 2.0 & 4 & 0.0448 & Ja \\
18 & 2.0 & 5 & 0.0202 & Ja \\
19 & 2.0 & 7 & 0.0043 & Ja \\
20 & 3.0 & 2 & 0.5561 & Nej \\
21 & 3.0 & 3 & 0.3881 & Nej \\
22 & 3.0 & 4 & 0.2617 & Nej \\
23 & 3.0 & 5 & 0.1728 & Nej \\
24 & 3.0 & 7 & 0.0731 & Nej \\
25 & 5.0 & 2 & 0.9028 & Nej \\
26 & 5.0 & 3 & 0.8302 & Nej \\
27 & 5.0 & 4 & 0.7489 & Nej \\
28 & 5.0 & 5 & 0.6648 & Nej \\
29 & 5.0 & 7 & 0.5050 & Nej \\

\end{longtable}

}

Table~\ref{tbl-deficit-guide} viser at \(\mu = 1{,}0\) og
\texttt{tot\_reward\_limit=3} giver deficit \(= 0{,}21\%\) og en
tabelstørrelse på 64 poster. Det er acceptabelt for bavian-analysen ---
under den naturlige grænse på \(5\%\). Figure~\ref{fig-deficit} viser
deficit-kurverne visuelt for alle testede \(\mu\)-værdier og limits.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-deficit-output-1.pdf}}

}

\caption{\label{fig-deficit}Deficit som funktion af
\texttt{tot\_reward\_limit} (x-akse) og mutationsrate
\(\mu\in\{0.5, 1.0, 1.5, 2.0\}\) (farvede kurver). Venstre delplot
(log-skala deficit): \(\mu=0.5\) (blå) falder hurtigt under
\(5\%\)-grænsen (rød stiplet linje) allerede ved limit\(=2\);
\(\mu=1.0\) (orange) ved limit\(=3\); \(\mu=1.5\) (grøn) ved
limit\(=4\); \(\mu=2.0\) (rød) kræver limit\(=4{-}5\). Højre delplot:
tilsvarende tabelstørrelse vokser kubisk med limit, fra \(27\)
(limit\(=2\)) til \(216\) (limit\(=5\)). Motiverer valget \(\mu=1.0\) og
limit\(=3\) som standardkonfiguration.}

\end{figure}%

Figure~\ref{fig-deficit} viser at deficit falder hurtigt med stigende
limit og at \(\mu = 0{,}5\) kræver meget lavt limit for acceptabel
dækning, mens \(\mu = 2{,}0\) kræver limit på mindst 5--7. For
bavian-analysen med \(\mu = 0{,}9 \times 10^{-8}\) er limit=3
tilstrækkeligt.

Figure~\ref{fig-heatmap-joint} viser den faktiske joint
sandsynlighedstabel --- sandsynligheden for alle kombinationer af
singletons og doubletons per locus --- for \(\theta \in \{2, 7, 20\}\).

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-heatmap-joint-output-1.pdf}}

}

\caption{\label{fig-heatmap-joint}Joint sandsynlighedstabel for
\(1\)-ton (x-akse) vs.~\(2\)-ton mutationer (y-akse) per træ, for
\(\theta\in\{2, 7, 20\}\) med \(\mu=1.0\) og limit\(=4\). Lav
\(\theta=2\) (venstre): sandsynlighed koncentreret i hjørnet \((0,0)\)
--- de fleste træer har ingen mutationer. Moderat \(\theta=7\)
(midterste): sandsynlighed spredt over \((0{-}3, 0{-}2)\). Høj
\(\theta=20\) (højre): sandsynlighed spredt over et større interval;
\(>50\%\) af massen er ved \(\geq 3\) singletons. Den skæve form
afspejler at singletons altid er hyppigere end doubletons.}

\end{figure}%

Figure~\ref{fig-heatmap-joint} viser den karakteristiske form: ved lav
\(\theta\) er sandsynlighed koncentreret i hjørnet \((0, 0)\) --- de
fleste loci har ingen mutationer. Ved \(\theta=7\) er sandsynlighed
spredt over \((0{-}3, 0{-}2)\). Ved \(\theta=20\) er massen spredt over
et endnu større interval. Denne koncentrationsændring er netop det
signal joint probability-inferens forsøger at udnytte.

Det centrale spørgsmål er nu om joint SFS giver bedre estimater end ren
TMRCA-inferens. Figure~\ref{fig-joint-vs-tmrca} sammenligner de to
tilgange direkte.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-joint-vs-tmrca-output-1.pdf}}

}

\caption{\label{fig-joint-vs-tmrca}Posterior mean og std for joint SFS
vs.~TMRCA-inferens over theta i \{2, 5, 10, 20\} med mu=1.0 og
N\_obs=1000. TMRCA-inferens giver konsekvent lavere posterior-std end
joint SFS ved disse parametre. Joint SFS er ikke bedre end TMRCA ved
mu=1.0 og reward\_limit=3.}

\end{figure}%

Figure~\ref{fig-joint-vs-tmrca} viser at TMRCA-inferens konsekvent giver
lavere posterior-std end joint SFS ved disse parameterværdier og
observationsantal. Det skyldes at joint SFS tabellen ved \(\mu=1{,}0\)
og limit=3 ikke er stor nok til at udnytte al information i høje
\(\theta\)-scenarier. Multi-feature SFS, der kombinerer singleton-,
doubleton- og tripleton-grenlængder simultant via
reward-transformationer, giver derimod gevinst ved moderate
\(\theta\)-værdier. Table~\ref{tbl-multifeature-gain} kvantificerer
gevinsten præcist.

{

\begin{longtable}[]{@{}lllll@{}}

\caption{\label{tbl-multifeature-gain}Gevinst ved multi-feature SFS
vs.~TMRCA som funktion af \(\theta\) med \(n_{\text{obs}}=2000\) og
Adam(\(0.1\)). Multi-feature SFS giver gevinst ved \(\theta=2\) (\(21.4%
\) reduktion i std: \(0.010\to 0.008\)) og \(\theta=5\) (\(54.6%
\): \(0.041\to 0.019\)) og \(\theta=10\) (\(64.2%
\): \(0.390\to 0.140\)). Ved \(\theta=20\) er multi-feature inferior
(\(-182.9%
\): std stiger fra \(0.981\) til \(2.774\)) fordi det høje \(\theta\)
kræver højere reward\_limit end brugt her.}

\tabularnewline

\toprule\noalign{}
& \$\textbackslash theta\$ & std TMRCA & std Multi & Gevinst
(\$\textbackslash\%\$) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 2 & 0.01029 & 0.00809 & 21.4 \\
1 & 5 & 0.04093 & 0.01859 & 54.6 \\
2 & 10 & 0.38965 & 0.13953 & 64.2 \\
3 & 20 & 0.98059 & 2.77416 & -182.9 \\

\end{longtable}

}

Table~\ref{tbl-multifeature-gain} viser at gevinsten er \(21{,}4\%\) ved
\(\theta=2\), \(54{,}6\%\) ved \(\theta=5\) og \(64{,}2\%\) ved
\(\theta=10\). Ved \(\theta=20\) er multi-feature inferior
(\(-182{,}9\%\)) fordi det høje \(\theta\) kræver en højere
\texttt{tot\_reward\_limit} end den anvendte konfiguration. Gevinsten er
størst i det parameterinterval der er relevant for bavianer
(\(\theta \approx 3{-}10\)), hvilket motiverer brugen af multi-feature i
NB07.

Figure~\ref{fig-ss-joint} viser forholdet mellem joint SFS og TMRCA over
stigende datamængder, for at give en idé om, hvornår de to metoder
nærmer sig hinanden.

\begin{verbatim}
n= 3000: Joint=6.832+/-0.1774  TMRCA=7.175+/-0.1052

   n  Joint mean  Joint std  TMRCA mean  TMRCA std  Indeholder sand (J)  Indeholder sand (T)
  50       8.154     1.7196       6.819     0.5039                 True                 True
 100       8.081     1.3609       6.408     0.1770                 True                False
 250       7.157     1.1306       6.897     0.4285                 True                 True
 500       6.529     0.3211       7.176     0.0788                 True                False
1000       6.791     0.5659       6.910     0.0427                 True                False
3000       6.832     0.1774       7.175     0.1052                 True                 True
\end{verbatim}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-ss-joint-output-2.pdf}}

}

\caption{\label{fig-ss-joint}Joint SFS-inferens (blå) vs.~TMRCA-inferens
(orange) som funktion af prøvestørrelse \(n\) for sand \(\theta=7\)
(\(\mu=1.0\), \(20\) partikler, \(300\) iterationer). Posterior-std
(lodret akse) falder for begge metoder med stigende \(n\). TMRCA er
konsekvent mere præcis (lavere std) end joint SFS ved alle
\(n\leq 3000\): ved \(n=3000\) er std\(_{\text{TMRCA}}=0.105\)
vs.~std\(_{\text{joint}}=0.177\). Begge metoder dækker sand \(\theta\) i
\(3/6\) testede stikprøvestørrelser.}

\end{figure}%

Figure~\ref{fig-ss-joint} viser at ved \(n=3000\) er
std\(_\text{joint} = 0{,}177\) og std\(_\text{TMRCA} = 0{,}105\). TMRCA
er altså konsekvent mere præcis, men joint SFS forbedres hurtigere med
datamængden. Som validering af hele joint probability-pipelinen
estimeres parametrene på msprime-simulerede data med known parametre.
Figure~\ref{fig-joint-msprime-svgd} viser resultatet.

\begin{verbatim}
Parameter  Fixed          MAP        Mean       SD         HPD 95% lo   HPD 95% hi  
0          No             6.977      8.805      9.674      5.342        10.59       
1          Yes            1          NA         NA         NA           NA          

Particles: 40, Iterations: 400
\end{verbatim}

\begin{figure}[H]

\centering{

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-joint-msprime-svgd-output-2.pdf}}

}

\subcaption{\label{fig-joint-msprime-svgd-1}Posterior credibility
interval for SVGD-inferens på joint SFS fra msprime-simulerede data
(\(\mu=1.0\), tot\_reward\_limit\(=3\), \(40\) partikler, \(400\)
iterationer). Blå streger viser partikelpositioner; orange linje er
posterior-mean \(\hat{\theta}=8.805\) (sand \(\theta=7.0\)); stiplet
sort er sand \(\theta\). Den brede posterior (SD \(=9.674\)) ved dette
parameterrum indikerer at joint SFS-inferens kræver større
\(n_{\text{obs}}\) end TMRCA-inferens for tilsvarende præcision.}

\centering{

\begin{verbatim}
<Figure size 1000x400 with 0 Axes>
\end{verbatim}

}

\subcaption{\label{fig-joint-msprime-svgd-2}}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-joint-msprime-svgd-output-4.pdf}}

}

\subcaption{\label{fig-joint-msprime-svgd-3}}

\centering{

\begin{verbatim}
<Figure size 1000x400 with 0 Axes>
\end{verbatim}

}

\subcaption{\label{fig-joint-msprime-svgd-4}}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-joint-msprime-svgd-output-6.pdf}}

}

\subcaption{\label{fig-joint-msprime-svgd-5}}

\centering{

\begin{verbatim}
<Figure size 1000x400 with 0 Axes>
\end{verbatim}

}

\subcaption{\label{fig-joint-msprime-svgd-6}}

}

\caption{\label{fig-joint-msprime-svgd}}

\end{figure}%

\subsection{To-locus ARG-modellen}\label{to-locus-arg-modellen}

Introduktionen viste tilstandsrummet for ARG-modellen. Her vises
inferensresultaterne.

\begin{figure}[H]

\centering{

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-arg-pairwise-output-1.pdf}}

}

\subcaption{\label{fig-arg-pairwise-1}Pairwise posterior for to-locus
ARG-model (\(n=2\), \(n_{\text{obs}}=2000\), \(40\) partikler, \(400\)
iterationer). Diagonal: marginale posterior-histogrammer for
\(\theta_0\) (øverst) og \(\theta_1=\rho\) (nederst). Off-diagonal:
joint scatter. \(\hat{\theta}_0=2.986\pm 0.688\) (sand \(3.0\)) og
\(\hat{\rho}=0.575\pm 0.533\) (sand \(0.5\)). Lav korrelation mellem de
to parametre. Rekombinationsraten har høj posterior-SD fordi den er
vanskelig at skelne fra koalescent-variation ved moderate \(\rho\).}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{index_files/mediabag/index_files/figure-latex/..-notebooks-06_joint_probability_inferens-fig-arg-pairwise-output-2.pdf}}

}

\subcaption{\label{fig-arg-pairwise-2}}

}

\caption{\label{fig-arg-pairwise}}

\end{figure}%

Coalescentraten \(\theta_0 = 2{,}986 \pm 0{,}688\) estimeres præcist
(sand \(3{,}0\), bias \(< 1\%\)). Rekombinationsraten
\(\theta_1 = 0{,}575 \pm 0{,}533\) har en bredere posterior (sand
\(0{,}5\)), fordi rekombinationssignalet er svagt ved lave rater.

\subsection{Sensitivitet over for
mutationsraten}\label{sensitivitet-over-for-mutationsraten}

Table~\ref{tbl-mu-bias} viser hvad der sker ved forkert \(\mu\).

{

\begin{longtable}[]{@{}lllll@{}}

\caption{\label{tbl-mu-bias}Systematisk bias ved forkert mutationsrate
\(\mu\) i joint-inferens (sand \(\theta=7.0\), sand \(\mu=1.0\),
\(n_{\text{obs}}=2000\)). Forkert \(\mu=0.3\) giver
\(\hat{\theta}=0.663\) (faktor \(\sim 10\) underskud). Forkert
\(\mu=2.5\) giver \(\hat{\theta}=36.4\) (faktor \(\sim 5\) overskud).
Biasset er systematisk og forsvinder ikke med mere data. Biasset er
superlineært --- en fordobling af \(\mu\) giver mere end en fordobling
af \(\hat{\theta}\) --- og motiverer en sensitivitetsanalyse over
\(\mu=0.9\times 10^{-8}\) i bavian-analysen.}

\tabularnewline

\toprule\noalign{}
& \$\textbackslash mu\$\_sand & \$\textbackslash mu\_fittet &
\$\textbackslash theta\$\_mean & \$\textbackslash theta\$\_std \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & 1.0 & 0.3 & 0.6626 & 0.01312 \\
1 & 1.0 & 0.7 & 3.3673 & 0.55794 \\
2 & 1.0 & 1.0 & 7.2938 & 0.50730 \\
3 & 1.0 & 1.5 & 14.9936 & 1.38223 \\
4 & 1.0 & 2.5 & 36.4355 & 4.86948 \\

\end{longtable}

}

Table~\ref{tbl-mu-bias} viser at halvering af \(\mu\) fra \(1{,}0\) til
\(0{,}3\) giver \(\hat{\theta} = 0{,}663\) mod sand \(7{,}0\) --- en
fejl med faktor \(\approx 10\). Fordobling til \(\mu = 2{,}5\) giver
\(\hat{\theta} = 36{,}4\) --- en faktor \(\approx 5\) overskud. Biasset
er superlineært og forsvinder ikke med mere data. Da mutationsraten
\(\mu = 0{,}9 \times 10^{-8}\) for bavianer er forbundet med usikkerhed,
rapporteres en sensitivitetsanalyse over
\(\mu \in \{0{,}7, 0{,}9, 1{,}1\} \times 10^{-8}\) i NB07A og NB07B.

Som afrunding af NB06-valideringen viser Table~\ref{tbl-datapri-joint}
en sammenligning af DataPrior og en manuel GaussPrior for joint
probability-inferens, for at bekræfte at priorvalget ikke påvirker
resultatet unødigt.

{

\begin{longtable}[]{@{}llllll@{}}

\caption{\label{tbl-datapri-joint}DataPrior vs.~Manuel GaussPrior til
joint probability SVGD (sand \(\theta=7\), \(\mu=1.0\),
\(n_{\text{obs}}=1000\)). GaussPrior manuelt sat til
\(\mathcal{N}(7, 1)\) giver \(\hat{\theta}=7.039\) med std \(=0.307\) og
bias \(=0.039\) (relativ bias \(0.56%
\)). DataPrior sættes automatisk via Wattersons estimator fra data og
giver \(\hat{\theta}=6.966\) med std \(=0.063\) og bias \(=0.034\)
(relativ bias \(0.49%
\)). DataPrior giver lavere std og er at foretrække fordi den undgår
manuel prior-specificering.}

\tabularnewline

\toprule\noalign{}
& Prior & \$\textbackslash theta\_7.0907595162593555\$ &
\$\textbackslash theta\_0.10928475744218108\$ & Bias & RelBias
\$\textbackslash\%\$ \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0 & GaussPrior manuel & 7.0393 & 0.30724 & 0.0393 & 0.56 \\
1 & DataPrior auto & 6.9660 & 0.06302 & 0.0340 & 0.49 \\

\end{longtable}

}

\chapter{Diskussion}\label{diskussion}

I dette speciale har jeg undersøgt, om fase-type fordelinger,
grafbaserede algoritmer og Bayesiansk inferens via SVGD kan bruges til
at lave inferens på bavian-genomdata. Overordnet set viser resultaterne,
at metoden fungerer, men også at der er en række forhold, som er vigtige
at være opmærksomme på, når resultaterne fortolkes. I det følgende
diskuteres først metodernes validitet, derefter de biologiske resultater
og til sidst de begrænsninger der er ved analyserne.

\section{Metodernes validitet og
kalibrering}\label{metodernes-validitet-og-kalibrering}

Et naturligt udgangspunkt er spørgsmålet om, hvorvidt SVGD-inferensen
faktisk virker som tilsigtet. Resultaterne fra NB02 og NB03 viser, at
den generelt gør det, men de viser også, at valget af prior kan have
stor betydning. Den brede GaussPrior fungerer godt ved moderate værdier
af (\(\theta\)), men ved (\(\theta = 15\)) opstår en betydelig bias.
Dette skyldes sandsynligvis, at en Gaussisk prior også tillader negative
værdier, selvom sådanne værdier ikke giver biologisk mening for en
coalescentrate. Når parameterområdet bliver tilstrækkeligt bredt, kan
prioren derfor påvirke inferensen i en uhensigtsmæssig retning.
DataPrior undgår i høj grad dette problem, fordi den bruger information
fra data til at centrere prioren før SVGD køres. Det forklarer, hvorfor
den gennemgående giver mindre bias i simuleringerne. Et andet vigtigt
metodisk valg er brugen af Wattersons estimator (\(\hat{\theta}_W\)) som
forbindelse mellem de observerede allele counts og phasics interne
parameterisering. Fremgangsmåden består i først at estimere
(\(\hat{\theta}_W\)) ud fra de observerede segregerende sites og
derefter bruge denne værdi som input til den efterfølgende inferens. De
rapporterede konfidensintervaller beskriver derfor usikkerheden i
SVGD-estimaterne givet den estimerede værdi af (\(\hat{\theta}_W\)), men
de inkluderer ikke usikkerheden i selve Wattersons estimator. Denne
usikkerhed kan være betydelig, særligt i populationer med få samples.
For eksempel er der kun otte haploide samples for \emph{P. ursinus} og
her må man forvente en forholdsvis stor samplingvariation. De
rapporterede intervaller bør derfor fortolkes som et underestimat af den
samlede usikkerhed. En mere komplet analyse ville integrere over
usikkerheden i (\(\hat{\theta}_W\)), men det ligger uden for rammerne af
den metode, der er anvendt her.

Valideringen mod msprime i NB01 og NB03 giver samtidig stor tillid til
den underliggende implementering. De analytiske beregninger i phasic
stemmer meget tæt overens med resultaterne fra de uafhængige
simuleringer og de observerede afvigelser ligger under 2 \%, hvilket er
inden for den variation, man forventer ved 3000 simuleringer. Særligt
sammenfaldet mellem den analytiske fase-type fordeling og
TMRCA-fordelingen fra msprime er vigtigt. De to kurver følger hinanden
næsten perfekt gennem hele fordelingen, selvom de bygger på vidt
forskellige beregningsmetoder. Hvor phasic beregner fordelingerne
analytisk ved hjælp af matrixeksponentialer, bygger msprime på gentagne
stokastiske simuleringer af genealogier. At de to tilgange giver
praktisk talt identiske resultater, styrker derfor tilliden til både
implementeringen og den matematiske model. Identificerbarheds-analysen i
NB03 er central for forståelsen af de mere komplekse modeller, der
senere anvendes i NB07B. Resultaterne viser, at coalescentraten
(\(\theta_0\)) generelt kan estimeres både præcist og uden nævneværdig
bias på tværs af de undersøgte migrationsscenarier. Situationen er
anderledes for migrationsraten (\(\theta_1\)), som kun kan identificeres
pålideligt ved moderate migrationsniveauer. Når migrationen bliver høj,
begynder de to populationer i praksis at opføre sig som en samlet
population og det bliver vanskeligt at adskille effekten af migration
fra effekten af coalescentraten. Dette ses tydeligt i de estimerede
posteriorfordelinger, hvor der opstår en markant negativ korrelation
mellem de to parametre. Statistisk betyder det, at flere forskellige
parameterkombinationer kan forklare de samme observerede data næsten
lige godt. En høj coalescentrate kombineret med lav migration kan
eksempelvis give et meget lignende mønster som en lav coalescentrate
kombineret med høj migration. Begge scenarier producerer relativt korte
TMRCA-tider og dermed lignende SFS. Problemet skyldes derfor ikke mangel
på data eller utilstrækkelig inferens, men er en grundlæggende egenskab
ved to-ø modellen. Som beskrevet af (\textbf{hobolth2024?}) er dette et
velkendt identificerbarhedsproblem, som ikke nødvendigvis forsvinder,
selv hvis man observerer flere data.

\subsection{Genetisk variation og effektiv
populationsstørrelse}\label{genetisk-variation-og-effektiv-populationsstuxf8rrelse}

Estimaterne af den effektive populationsstørrelse (\(N_e\)), baseret på
nukleotiddiversiteten (\(\pi\)), varierer fra omkring \(14.000\) for
\emph{P. papio} til omkring \(82.000\) for \emph{P. cynocephalus}.
Overordnet stemmer dette mønster godt overens med tidligere studier.
(\textbf{Rogers2019?}) viste med PSMC-analyser, at de fem arter uden for
\emph{P. papio} deler en relativt ens demografisk historie tilbage til
cirka \(1,4\) millioner år siden, hvorefter deres udviklingsforløb
gradvist begynder at divergere. De høje niveauer af genetisk variation i
\emph{P. cynocephalus} og \emph{P. anubis} passer godt med dette billede
og antyder, at disse arter fortsat har relativt store effektive
populationsstørrelser, selvom tidligere studier også har dokumenteret
tilbagegange i nyere tid. Blandt de seks arter skiller \emph{P. papio}
sig tydeligt ud. Det estimerede (\(N_e\)) på omkring \(14.000\) er
væsentligt lavere end hos de øvrige arter og samtidig observeres en
positiv Tajimas (\(D\))-værdi på \(1,02\). Begge observationer peger i
retning af et underskud af sjældne varianter, hvilket ofte ses efter en
populationsnedgang eller flaskehals. Dette stemmer godt overens med
resultaterne fra Rogers et al.~(2019), som fandt tegn på en
længerevarende reduktion i populationsstørrelsen hos \emph{P. papio}
begyndende for omtrent \(400.000\) år siden. De nuværende analyser
understøtter derfor fortolkningen af, at \emph{P. papio} har gennemgået
en mere markant demografisk tilbagegang end de øvrige bavianarter. Det
kan naturligvis ikke udelukkes, at den relativt begrænsede
stikprøvestørrelse bidrager til usikkerheden i estimaterne. For \emph{P.
papio} er analysen baseret på \(24\) haploide samples, hvilket giver
større samplingvariation end for de bedst repræsenterede arter.
Alligevel peger både nukleotiddiversiteten og Wattersons estimator i
samme retning, hvilket gør en reel demografisk forklaring mere
sandsynlig end en rent statistisk forklaring. De negative Tajimas
(\(D\))-værdier for \emph{P. cynocephalus} (\(D=-0,59\)) og \emph{P.
anubis} (\(D=-0,64\)) er særligt interessante. Negative værdier opstår
typisk, når der er et overskud af sjældne varianter i forhold til den
neutrale forventning. En mulig forklaring er historisk populationsvækst,
hvor mange mutationer er opstået relativt nyligt og derfor endnu ikke
har nået høje frekvenser i populationen. Denne fortolkning stemmer godt
overens med de demografiske mønstre, som Rogers et al.~(2019)
observerede for begge arter. Samtidig er populationsvækst ikke den
eneste mulige forklaring. Positive selektionshændelser kan skabe
lignende signaler, ligesom admixture mellem tidligere adskilte
populationer kan øge antallet af sjældne varianter. {Sørensen et al.}
(2023) dokumenterede omfattende admixture i både \emph{P. cynocephalus}
og \emph{P. anubis}, mens Vilgalys et al.~(2022) fandt tegn på selektion
mod admixture-ancestry i Amboseli-populationen. Det er derfor vanskeligt
at tilskrive de observerede Tajimas (\(D\))-værdier en enkelt biologisk
årsag. Mest sandsynligt afspejler signalet en kombination af demografisk
historie, genflow og selektion. SFS understøtter denne fortolkning.
\emph{P. cynocephalus} og \emph{P. anubis} har begge en høj andel af
singletons sammenlignet med den neutrale forventning, mens \emph{P.
papio} viser det modsatte mønster med relativt færre singletons og flere
varianter ved intermediære frekvenser. Dette er præcis den forskel, man
forventer mellem populationer med henholdsvis historisk vækst og
historisk tilbagegang. De øvrige arter ligger generelt tættere på den
neutrale forventning, selvom der stadig ses mindre afvigelser. For
\emph{P. kindae} er resultaterne særligt interessante. Arten har en
svagt positiv Tajimas (\(D\))-værdi på \(0,30\), hvilket umiddelbart kan
virke overraskende i lyset af tidligere studier, der beskriver arten som
en hybridpopulation med bidrag fra både den nordlige og sydlige
bavian-klade. Hybridisering forventes ofte at introducere ny genetisk
variation og dermed skabe et mere negativt Tajimas (\(D\)). En mulig
forklaring er, at den efterfølgende demografiske udvikling har haft
større betydning for det nuværende signal end selve
hybridiseringsbegivenheden. Dette er også i overensstemmelse med Rogers
et al.~(2019), som fandt tegn på stigende populationsstørrelse omkring
samme periode.

\subsection{\texorpdfstring{To-ø modellen og genflow mellem \emph{P.
cynocephalus} og \emph{P.
kindae}}{To-ø modellen og genflow mellem P. cynocephalus og P. kindae}}\label{to-uxf8-modellen-og-genflow-mellem-p.-cynocephalus-og-p.-kindae}

Resultaterne fra to-ø modellen peger på, at der har været genflow mellem
\emph{P. cynocephalus} og \emph{P. kindae}. Konfidensintervallet for
migrationsraten (\(\theta_1\)) overlapper ikke nul, hvilket indikerer,
at en model med migration passer bedre til data end en model med
fuldstændig isolation. Dette stemmer godt overens med tidligere
genetiske studier. {Sørensen et al.} (2023) viste blandt andet, at
\emph{P. kindae} genetisk ligger tættere på \emph{P. cynocephalus} end
på nogen anden bavianart og at Kinda-bavianer bærer ancestry fra den
sydlige klade, herunder gule bavianer. De nuværende resultater
understøtter derfor billedet af, at de to populationer historisk ikke
har været fuldstændigt adskilt. Når den asymmetriske model anvendes,
bliver billedet mere nuanceret. Her overlapper konfidensintervallerne
for (\(m_{12}\)) og (\(m_{21}\)) i høj grad hinanden og resultaterne
giver derfor ikke grundlag for at konkludere, at genflowet har været
stærkere i den ene retning end i den anden. Det er interessant, fordi
{Sørensen et al.} (2023) fandt evidens for mandsdomineret genflow fra
yellow og olive bavianer ind i Kinda-bavianernes område gennem det, de
beskriver som nuclear swamping. Hvis dette historiske genflow
hovedsageligt er foregået fra \emph{P. cynocephalus} mod \emph{P.
kindae}, kunne man forvente, at en asymmetrisk model ville opfange
signalet. At dette ikke sker, behøver dog ikke betyde, at asymmetrisk
genflow ikke har fundet sted. En mulig forklaring er, at genflowet over
lange tidsperioder har været mere balanceret, end de nyere
admixture-signaler umiddelbart antyder. En anden mulighed er, at
datamængden ganske enkelt ikke er stor nok til at adskille de to
migrationsrater med tilstrækkelig præcision. Resultaterne fra NB03
viste, at inferens af asymmetriske migrationsrater kræver relativt store
datamængder og tilstrækkeligt mange samples. Når analysen her er baseret
på et kromosom, er det sandsynligt, at den statistiske styrke ikke er
tilstrækkelig til sikkert at skelne mellem de to retninger. Resultatet
bør derfor fortolkes som mangel på statistisk evidens for asymmetri
snarere end evidens for symmetrisk migration.

\subsection{\texorpdfstring{IM-modellen og split-tidspunktet for
\emph{P. anubis} og \emph{P.
cynocephalus}}{IM-modellen og split-tidspunktet for P. anubis og P. cynocephalus}}\label{im-modellen-og-split-tidspunktet-for-p.-anubis-og-p.-cynocephalus}

IM-modellen blev anvendt til samtidig at estimere split-tidspunktet
mellem \emph{P. anubis} og \emph{P. cynocephalus} samt graden af
migration efter populationsopdelingen. Resultaterne viser, at
konfidensintervallet for migrationsraten ikke overlapper nul, hvilket
peger på fortsat genflow efter splitpunktet. Dette er i god
overensstemmelse med den eksisterende litteratur. Rogers et al.~(2019)
fandt tegn på historisk admixture mellem de to arter og de moderne
hybridzoner i blandt andet Amboseli og Tarangire dokumenterer, at
genetisk udveksling fortsat forekommer. Derudover viste Vilgalys et
al.~(2022), at der foregår aktiv selektion mod admixture-ancestry i
Amboseli-populationen. Samlet set passer de nuværende resultater derfor
godt ind i det eksisterende billede af to arter, der har været delvist
adskilte, men stadig genetisk forbundne. Fortolkningen af
split-tidspunktet er derimod mere usikker. Konfidensintervallet for
switch-raten er relativt bredt og samtidig bygger modellen på den
forenklede antagelse, at begge populationer har haft konstant effektiv
populationsstørrelse siden splitpunktet. Tidligere studier viser
imidlertid, at bavianpopulationernes størrelse har varieret betydeligt
gennem tiden. Når modellen ikke kan beskrive disse ændringer eksplicit,
vil noget af variationen i stedet blive absorberet af de parametre, der
faktisk estimeres. Det betyder, at det estimerede split-tidspunkt
snarere bør opfattes som et gennemsnitligt historisk signal end som et
præcist tidspunkt for artsadskillelsen. En mere realistisk model ville
tillade populationsstørrelsen at ændre sig gennem tiden. Inden for
fase-type rammen er dette principielt muligt ved hjælp af tidsinhomogene
modeller og epoch-baserede beskrivelser af demografien. Sådanne modeller
ville sandsynligvis give en mere detaljeret beskrivelse af
populationshistorien, men de ville samtidig introducere flere parametre
og dermed stille større krav til datamængden. Posteriorfordelingerne
afslører desuden et identificerbarhedsproblem, der minder om det, der
blev observeret i to-ø modellen. Der ses en tydelig negativ korrelation
mellem coalescentraten og switch-raten, hvilket betyder, at flere
forskellige kombinationer af split-tidspunkt og migration kan forklare
de samme data næsten lige godt. Et tidligt split efterfulgt af langvarig
migration kan for eksempel skabe et meget lignende genetisk signal som
et senere split kombineret med kortere migrationsperioder. Dette gør det
vanskeligt at estimere de to processer uafhængigt af hinanden og
illustrerer en generel udfordring ved inferens i tidsinhomogene
coalescentmodeller.

\section{Begrænsninger ved
analysen}\label{begruxe6nsninger-ved-analysen}

Selvom resultaterne overordnet er rigtige og stemmer godt overens med
tidligere studier, er der en række begrænsninger, som bør tages i
betragtning ved fortolkningen. Den mest oplagte begrænsning er, at alle
analyser er baseret på kromosom 20 alene. Et enkelt kromosom
repræsenterer kun en lille del af genomet og dermed også kun et
begrænset udsnit af artens samlede genealogiske historie. Tilfældige
udsving i mutationer, rekombination og genetisk drift kan derfor få
større betydning, end hvis hele genomet var blevet analyseret.
Sammenlignet med de helgenomstudier, der ligger til grund for meget af
den eksisterende litteratur, er datagrundlaget her væsentligt mindre.
Dette gælder især for arter med få samples, hvor variationen mellem
forskellige genomregioner potentielt kan påvirke resultaterne
betydeligt. En anden vigtig begrænsning er stikprøvestørrelsen. For
flere af arterne er analyserne baseret på relativt få individer.
\emph{P. ursinus} er eksempelvis repræsenteret af blot fire diploide
individer fra én lokalitet i Zambia. Det giver kun et begrænset indblik
i den genetiske variation hos en art, der er udbredt over store dele af
det sydlige Afrika. Tidligere studier har vist betydelig genetisk
variation mellem forskellige geografiske populationer og det er derfor
usikkert, hvor repræsentative de estimerede parametre er for arten som
helhed. En tilsvarende problemstilling gælder for \emph{P. papio}, hvor
alle individer stammer fra en lokalitet i Senegal. En tredje begrænsning
vedrører antagelsen om neutralitet. Hele den anvendte coalescentramme
bygger på, at de analyserede genetiske varianter udvikler sig neutralt.
I virkeligheden ved man, at selektion spiller en rolle i flere
bavianpopulationer. Vilgalys et al.~(2022) dokumenterede eksempelvis
selektion mod admixture-ancestry, og andre studier har fundet tegn på
selektion i forbindelse med hybridisering. Hvis selektion påvirker dele
af genomet, kan dette ændre de genealogiske mønstre og dermed også
påvirke estimaterne af populationsparametre. De estimerede værdier bør
derfor fortolkes som effektive demografiske parametre under de
observerede evolutionsprocesser snarere end som perfekte beskrivelser af
den underliggende populationshistorie.

En fjerde begrænsning er antagelsen om, at hver art kan beskrives som en
enkelt panmiktisk population. Denne antagelse er praktisk nødvendig for
de anvendte modeller, men den er næppe fuldt ud realistisk. Sorensen et
al.~(2023) viste, at flere bavianarter indeholder betydelig intern
populationsstruktur. For eksempel adskiller eastern og western yellow
baboons sig genetisk fra hinanden, selvom de begge klassificeres som
\emph{P. cynocephalus}. Når individer fra forskellige geografiske
områder samles i en analyse, behandles de som medlemmer af samme
population, selvom de i virkeligheden kan have haft delvist adskilte
evolutionære historier. Denne forenkling kan påvirke de estimerede
parametre. Populationsstruktur øger ofte den observerede genetiske
variation, fordi forskellige delpopulationer akkumulerer mutationer
uafhængigt af hinanden. Hvis denne struktur ignoreres, kan variationen
fejlagtigt fortolkes som tegn på en større effektiv
populationsstørrelse. Tajimas (\(D\)) er særligt følsom over for denne
problematik, da populationsstruktur typisk skaber et overskud af
varianter ved intermediære frekvenser og dermed mere positive
(\(D\))-værdier. Det betyder, at de positive værdier observeret for
blandt andet \emph{P. hamadryas} og \emph{P. papio} ikke nødvendigvis
udelukkende skyldes demografisk tilbagegang, men også kan afspejle
underliggende populationsstruktur, som ikke modelleres eksplicit. En
femte begrænsning vedrører mutationsraten. Omregningen fra (\(\theta\))
til effektiv populationsstørrelse afhænger direkte af den antagne
mutationsrate (\(\mu\)) og generationstiden (\(g\)). I denne analyse
anvendes de værdier, der også benyttes af Sorensen et al.~(2023), nemlig
(\(\mu = 0{,}9 \times 10^{-8}\)) mutationer per site per generation og
en generationstid på \(11\) år. Selvom disse værdier er velbegrundede,
er de ikke kendt præcist. Små ændringer i mutationsraten kan have stor
betydning for de resulterende (\(N_e\))-estimater. Sensitivitetsanalysen
i NB06 viste eksempelvis, at en fordobling eller halvering af
mutationsraten fører til tilsvarende ændringer i de estimerede
populationsstørrelser. Denne usikkerhed adskiller sig fra den
statistiske usikkerhed, der afspejles i konfidensintervallerne. Selv
hvis man havde uendeligt mange genetiske data, ville usikkerheden
omkring (\(\mu\)) og (\(g\)) stadig være til stede. De rapporterede
(\(N_e\))-estimater bør derfor forstås som betingede på de valgte
biologiske parametre og ikke som eksakte størrelser.

\section{Fase-type metoden i relation til eksisterende
metoder}\label{fase-type-metoden-i-relation-til-eksisterende-metoder}

Det er også relevant at sætte den anvendte metode ind i en bredere
populationsgenetisk sammenhæng. De mest udbredte metoder til demografisk
inferens i nyere genomstudier er coalescent-HMM-baserede tilgange som
PSMC (Li and Durbin 2011) og MSMC2 (Schiffels and Durbin 2014). Disse
metoder er blevet anvendt i flere af de centrale studier af bavianers
demografiske historie, herunder Rogers et al.~(2019) og Sorensen et
al.~(2023). Deres store styrke er, at de kan rekonstruere ændringer i
populationsstørrelse gennem tid og dermed beskrive komplekse
demografiske forløb over hundredtusinder eller millioner af år. Til
gengæld har disse metoder også begrænsninger. Resultaterne præsenteres
typisk som punktestimater eller rekonstruerede kurver, og det kan være
vanskeligt at kvantificere den fulde usikkerhed omkring estimaterne.
Desuden bliver modeller med migration og populationsstruktur hurtigt
beregningsmæssigt komplekse. Tidligere sammenligninger af
coalescent-HMM-metoder har vist, at de generelt fungerer godt til at
beskrive flaskehalse og ændringer i populationsstørrelse, men at mere
komplekse scenarier med migration kan være vanskeligere at inferere
præcist. Fase-type tilgangen repræsenterer på flere måder en anden
filosofi. I stedet for at beskrive demografien som en kontinuert
funktion af tid fokuserer metoden på relativt simple modeller med et
begrænset antal parametre. Til gengæld kan sandsynlighedsfordelinger og
likelihoods beregnes analytisk, hvilket giver direkte adgang til
posteriorfordelinger og troværdighedsintervaller. Det gør det muligt
ikke blot at estimere parameteres mest sandsynlige værdi, men også at
kvantificere usikkerheden omkring dem på en naturlig Bayesiansk måde. En
væsentlig styrke ved fase-type rammen er netop denne analytiske tilgang.
Hvor mange moderne populationsgenetiske metoder er afhængige af
omfattende simulering eller MCMC-sampling, kan sandsynlighederne her
beregnes direkte ved hjælp af matrixeksponentialer. Det reducerer
risikoen for konvergensproblemer og gør beregningerne mere
reproducerbare. Samtidig giver det mulighed for at undersøge modeller
med migration og populationsstruktur uden nødvendigvis at skulle
simulere store mængder genealogisk data. Omvendt kommer denne styrke med
en pris. Metoden er bedst egnet til relativt simple modeller, hvor
antallet af parametre er begrænset. Efterhånden som modellerne bliver
mere realistiske og inkluderer tidsvarierende populationsstørrelser,
flere populationer eller komplekse migrationsmønstre, vokser modelrummet
hurtigt. I sådanne situationer kan mere fleksible metoder som PSMC (Li
and Durbin 2011), MSMC2 (Schiffels and Durbin 2014) eller ARG-baserede
tilgange være bedre egnede, selvom de ofte er beregningsmæssigt dyrere.
Resultaterne i dette speciale peger derfor ikke på, at fase-type metoder
skal erstatte eksisterende tilgange. Snarere bør de ses som et
supplement. Metoden er særligt velegnet, når man ønsker at undersøge
specifikke biologiske hypoteser om populationsstørrelse, migration eller
split-tidspunkter inden for en veldefineret modelramme, samtidig med at
man ønsker en fuld Bayesiansk beskrivelse af usikkerheden.

\section{Perspektiver og fremtidigt
arbejde}\label{perspektiver-og-fremtidigt-arbejde}

Resultaterne viser, at fase-type fordelinger kombineret med SVGD kan
bruges til at udtrække biologisk meningsfuld information fra
bavian-genomdata. Samtidig peger analyserne på flere oplagte retninger
for fremtidigt arbejde. Den mest umiddelbare udvidelse vil være at
anvende hele genomet frem for kun kromosom 20. Et helgenom indeholder
langt flere segregerende sites og dermed væsentligt mere information om
populationernes historie. Flere data vil ikke nødvendigvis løse alle
identificerbarhedsproblemer, men de vil reducere den statistiske
usikkerhed og gøre det muligt at estimere parametre med større
præcision. En anden oplagt mulighed er at udvide modellerne, så
populationsstørrelser kan ændre sig gennem tiden. De fleste resultater i
den eksisterende litteratur viser, at bavianpopulationer har gennemgået
markante demografiske ændringer over de seneste millioner af år.
Antagelsen om konstant (\(N_e\)) er derfor en forenkling. Tidsinhomogene
modeller med flere epoker ville kunne beskrive disse processer mere
realistisk og potentielt give mere præcise estimater af både migration
og split-tidspunkter. Det vil også være relevant at inkludere
rekombination mere eksplicit i inferensen. Rekombination skaber
variation i genealogier langs genomet og indeholder derfor vigtig
information om populationshistorien. ARG-modellen, som blev undersøgt i
NB06, repræsenterer et naturligt næste skridt i denne retning. Ved at
kombinere fase-type metoder med information fra rekombination kan man
potentielt opnå en mere detaljeret rekonstruktion af historiske
migrations- og splitbegivenheder. Endelig vil en mere systematisk
undersøgelse af usikkerheden omkring mutationsrate og generationstid
være værdifuld. Som vist i NB06 har disse biologiske parametre direkte
indflydelse på de estimerede populationsstørrelser. En fremtidig analyse
kunne derfor behandle (\(\mu\)) og (\(g\)) som usikre størrelser frem
for faste konstanter og undersøge, hvordan denne usikkerhed påvirker de
endelige demografiske konklusioner. Samlet set viser dette speciale, at
fase-type metoder og Bayesiansk inferens udgør et lovende værktøj til
populationsgenetiske analyser. Metoden reproducerer kendte teoretiske
resultater, giver biologisk plausible estimater på virkelige genomdata
og gør det muligt at kvantificere usikkerhed på en systematisk måde.
Samtidig illustrerer analyserne de udfordringer, der opstår, når
komplekse demografiske processer skal beskrives med relativt simple
modeller. Netop balancen mellem matematisk håndterbarhed og biologisk
realisme vil sandsynligvis være et centralt tema i den videre udvikling
af fase-type baserede metoder til populationsgenetisk inferens.

\chapter{Konklusion}\label{konklusion}

\chapter{References}\label{references}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-BladtNielsen2017}
Bladt, Mogens, and Bo Friis Nielsen. 2017. \emph{Matrix-Exponential
Distributions in Applied Probability}. Vol. 81. Probability Theory and
Stochastic Modelling. Springer.
\url{https://doi.org/10.1007/978-1-4939-7049-0}.

\bibitem[\citeproctext]{ref-hobolth2021}
Hobolth, Asger, Mogens Bladt, and Lars Nørvang Andersen. 2021.
{``Multivariate Phase-Type Theory for the Site Frequency Spectrum.''}
\emph{Preprint / arXiv}, ahead of print.
https://doi.org/\url{https://doi.org/10.48550/arXiv.2101.04941}.

\bibitem[\citeproctext]{ref-Hobolth2024}
Hobolth, Asger, Iker Rivas-González, Mogens Bladt, and Andreas Futschik.
2024. {``Phase-Type Distributions in Mathematical Population Genetics:
An Emerging Framework.''} \emph{Theoretical Population Biology} 157:
14--32. https://doi.org/\url{https://doi.org/10.1016/j.tpb.2024.03.001}.

\bibitem[\citeproctext]{ref-Hobolth2018}
Hobolth, Asger, Arno Siri-Jegousse, and Mogens Bladt. 2018.
{``Phase-Type Distributions in Population Genetics.''} \emph{arXiv
Preprint arXiv:1806.01416}, ahead of print.
https://doi.org/\url{https://doi.org/10.1016/j.tpb.2019.02.001}.

\bibitem[\citeproctext]{ref-hobolth2019}
Hobolth, Asger, Arno Siri-Jégousse, and Mogens Bladt. 2019.
\emph{Lecture Notes: Phase-Type Distributions in Population Genetics}.

\bibitem[\citeproctext]{ref-jordan2018papio}
{Jordan, Vallmer E., Jerilyn A. Walker, Thomas O. Beckstrom, Cody J.
Steely, Cullen L. McDaniel, et al.} 2018. {``A Computational
Reconstruction of Papio Phylogeny Using Alu Insertion Polymorphisms.''}
\emph{Mobile DNA} 9: 13.
https://doi.org/\url{https://doi.org/10.1186/s13100-018-0118-3}.

\bibitem[\citeproctext]{ref-kelleher2016msprime}
Kelleher, Jerome, Alison M Etheridge, and Gilean McVean. 2016.
{``Efficient Coalescent Simulation and Genealogical Analysis for Large
Sample Sizes.''} \emph{PLOS Computational Biology} 12 (5): e1004842.
https://doi.org/\url{https://doi.org/10.1371/journal.pcbi.1004842}.

\bibitem[\citeproctext]{ref-Kingman1982}
Kingman, John F. C. 1982. {``The Coalescent.''} \emph{Stochastic
Processes and Their Applications} 13 (3): 235--48.
\url{https://doi.org/10.1016/0304-4149(82)90011-4}.

\bibitem[\citeproctext]{ref-kopp2023}
Kopp, Gisela H., Riashna Sithaldeen, Franziska Trede, Franziska
Grathwol, Christian Roos, and Dietmar Zinner. 2023. {``A Comprehensive
Overview of Baboon Phylogenetic History.''} \emph{Genes} 14: 614.
\url{https://doi.org/10.3390/genes14030614}.

\bibitem[\citeproctext]{ref-li2011psmc}
Li, Heng, and Richard Durbin. 2011. {``Inference of Human Population
History from Individual Whole-Genome Sequences.''} \emph{Nature} 475
(7357): 493--96.
https://doi.org/\url{https://doi.org/10.1038/nature10231}.

\bibitem[\citeproctext]{ref-liu2016svgd}
Liu, Qiang, and Dilin Wang. 2016. {``Stein Variational Gradient Descent:
A General Purpose Bayesian Inference Algorithm.''} \emph{Advances in
Neural Information Processing Systems} 29.
\url{https://arxiv.org/abs/1608.04471}.

\bibitem[\citeproctext]{ref-phasic}
Munch, Kasper. 2026. \emph{Phasic: A Library for Modelling and Inference
on Markov Jump Processes}. V. latest. Released.
\url{https://munch-group.org/phasic/}.

\bibitem[\citeproctext]{ref-rogers2019}
{Rogers, Jeffrey, Muthuswamy Raveendran, et al.} 2019. {``The
Comparative Genomics and Complex Population History of Papio Baboons.''}
\emph{Science Advances} 5 (1): eaau6947.
https://doi.org/\url{https://doi.org/10.1126/sciadv.aau6947}.

\bibitem[\citeproctext]{ref-Roikjer2022}
Røikjer, Tobias, Asger Hobolth, and Kasper Munch. 2022. {``Graph-Based
Algorithms for Phase-Type Distributions.''} \emph{Statistics and
Computing} 32: 103.
https://doi.org/\url{https://doi.org/10.1007/s11222-022-10174-3}.

\bibitem[\citeproctext]{ref-schiffels2014msmc}
Schiffels, Stephan, and Richard Durbin. 2014. {``Inferring Human
Population Size and Separation History from Multiple Genome
Sequences.''} \emph{Nature Genetics} 46 (8): 919--25.
https://doi.org/\url{https://doi.org/10.1038/ng.3015}.

\bibitem[\citeproctext]{ref-sorensen2023}
{Sørensen, Erik F. et al.} 2023. {``Genome-Wide Coancestry Reveals
Details of Ancient and Recent Male-Driven Reticulation in Baboons.''}
\emph{Science} 380: eabn8153.
https://doi.org/\url{https://doi.org/10.1126/science.abn8153}.

\bibitem[\citeproctext]{ref-tajima1989}
Tajima, Fumio. 1989. {``Statistical Method for Testing the Neutral
Mutation Hypothesis by {DNA} Polymorphism.''} \emph{Genetics} 123 (3):
585--95.
https://doi.org/\url{https://doi.org/10.1093/genetics/123.3.585}.

\bibitem[\citeproctext]{ref-vilgalys2022}
{Vilgalys, Tauras P., Arielle S. Fogel, Jordan A. Anderson, et al.}
2022. {``Selection Against Admixture and Gene Regulatory Divergence in a
Long-Term Primate Field Study.''} \emph{Science} 377 (6606): 635--41.
https://doi.org/\url{https://doi.org/10.1126/science.abm4917}.

\bibitem[\citeproctext]{ref-wakeley2009coalescent}
Wakeley, John. 2009. \emph{Coalescent Theory: An Introduction}. Roberts
\& Company Publishers.

\bibitem[\citeproctext]{ref-watterson1975}
Watterson, G. A. 1975. {``On the Number of Segregating Sites in
Genetical Models Without Recombination.''} \emph{Theoretical Population
Biology} 7 (2): 256--76.
https://doi.org/\url{https://doi.org/10.1016/0040-5809(75)90020-9}.

\end{CSLReferences}

\chapter{Appendiks}\label{appendiks}

\section{Data Availability}\label{data-availability}

Alle notebooks, kode og resultater til dette speciale er tilgængelige på
GitHub. Analyserne er fuldt reproducerbare via \emph{phasic}-biblioteket
og de otte Jupyter notebooks der er navngivet kronologisk og kører
sekventielt.

\section{Brug af Generativ Kunstig
Intelligens}\label{brug-af-generativ-kunstig-intelligens}

I overensstemmelse med Aarhus Universitets retningslinjer oplyser jeg
hermed min brug af AI-værktøjer under udarbejdelsen af dette speciale.
Alle analyser, fortolkninger og videnskabelige bidrag er mine egne.
\textbf{Claude (Anthropic)} blev brugt til kodereview, fejlsøgning i
Python-notebooks og strukturering af Quarto-dokumentet.


\backmatter


\end{document}
