# SLURM environment variables for job (generated by slurm-code)
export SLURM_JOB_ID='28677580'
export SLURM_JOB_NAME='sc-emma-giraf'
export SLURM_JOB_PARTITION='short'
export SLURM_JOB_ACCOUNT='emma_giraf'
export SLURM_JOB_NUM_NODES='1'
export SLURM_CPUS_ON_NODE='1'
export SLURM_JOB_NODELIST='cn-1040'
export SLURM_TIMELIMIT='09:00:00'
export SLURM_SUBMIT_DIR='/faststorage/project/emma_giraf/people/emmachristensen/emma-giraf'
export SLURM_MEM_PER_CPU=8192
export SLURM_CPUS_PER_TASK='1'
export SLURM_NTASKS='1'
