[workspace]
authors = ["emmachristensen <emma14@live.dk>"]
channels = ["conda-forge", "bioconda", "munch-group"]
name = "emma-giraf"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
git = "*"
gh = "*"
pip = "*"
git-lfs = "*"
nodejs = "*"
seaborn = "*"
pytables = "*"
scipy = "*"
statsmodels = "*"
ipykernel = "*"
jupyter = "*"
nbconvert = "*"
vscodenb = "*"
r-rsvg = "*"
sgkit = "*"
tskit = ">=1.0.2,<2"
bio2zarr = "*"
bcftools = "*"
geneinfo = "*"
quarto = ">=1.7.33,<2"
nbformat = "*"
nbdime = "*"
jsonschema = ">=4.26.0,<5"
referencing = ">=0.37.0,<0.38"
phasic = ">=0.26.37,<0.27"
msprime = ">=1.4.1,<2"


[tasks.init]
cmd = "python ./scripts/rename.py && git remote set-url \"origin\" git@github.com:munch-group/$(basename $(git rev-parse --show-toplevel))"

[tasks.docs]
cmd = "./scripts/docs-run-notebooks.sh && git add -u notebooks"
description = "Run documentation notebooks"

[tasks.clean]
cmd = "git clean -id"
description = "Removes untracked files and directories but respects your .gitignores"

[tasks.commit]
depends-on = ["docs"]
cmd = "./scripts/git-commit.sh"
description = "Commits with message made by Claude"
