<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-05-27">
<meta name="keywords" content="Coalescent theory, Phase-type distributions, SVGD, Population genetics, Papio">

<title>Fase-type fordelinger og Bayesiansk inferens i populationsgenetik</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8ffd5f67044e5306d9846f29df41dda5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta name="citation_title" content="Fase-type fordelinger og Bayesiansk inferens i populationsgenetik">
<meta name="citation_abstract" content="- Dette speciale udvikler en ramme for Bayesiansk demografisk inferens baseret på eksakte fase-type beregninger kombineret med Stein Variational Gradient Descent (SVGD). Coalescentmodeller for enkelt-populationer, to-ø modellen og Isolation with Migration (IM)-modellen implementeres via phasic-biblioteket og valideres analytisk og med msprime-simulationer. Metoderne anvendes på helgenomsekvenseringsdata fra seks bavian-populationer (*Papio* spp.) til estimering af effektive populationsstørrelser, migrationsrater og split-tidspunkter.
">
<meta name="citation_keywords" content="Coalescent theory,Phase-type distributions,SVGD,Population genetics,Papio">
<meta name="citation_author" content="Emma Christensen">
<meta name="citation_author" content="Kasper Munch">
<meta name="citation_author" content="Kasper Urup Kjeldsen">
<meta name="citation_publication_date" content="2026-05-27">
<meta name="citation_cover_date" content="2026-05-27">
<meta name="citation_year" content="2026">
<meta name="citation_online_date" content="2026-05-27">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Phase-type distributions in mathematical population genetics: An emerging framework;,citation_author=Asger Hobolth;,citation_author=Iker Rivas-González;,citation_author=Mogens Bladt;,citation_author=Andreas Futschik;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_doi=https://doi.org/10.1016/j.tpb.2024.03.001;,citation_volume=157;,citation_journal_title=Theoretical Population Biology;">
<meta name="citation_reference" content="citation_title=Lecture notes: Phase-type distributions in population genetics;,citation_author=Asger Hobolth;,citation_author=Arno Siri-Jégousse;,citation_author=Mogens Bladt;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_publisher=Aarhus University; University of Copenhagen;">
<meta name="citation_reference" content="citation_title=Multivariate phase-type theory for the site frequency spectrum;,citation_author=Asger Hobolth;,citation_author=Mogens Bladt;,citation_author=Lars Nørvang Andersen;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_doi=https://doi.org/10.48550/arXiv.2101.04941;,citation_journal_title=Preprint / arXiv;">
<meta name="citation_reference" content="citation_title=Phase-type distributions in population genetics;,citation_author=Asger Hobolth;,citation_author=Arno Siri-Jegousse;,citation_author=Mogens Bladt;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_doi=https://doi.org/10.1016/j.tpb.2019.02.001;,citation_journal_title=arXiv preprint arXiv:1806.01416;">
<meta name="citation_reference" content="citation_title=Graph-based algorithms for phase-type distributions;,citation_author=Tobias Røikjer;,citation_author=Asger Hobolth;,citation_author=Kasper Munch;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_doi=10.1007/s11222-022-10174-3;,citation_volume=32;,citation_journal_title=Statistics and Computing;">
<meta name="citation_reference" content="citation_title=Finite markov chains;,citation_author=John G. Kemeny;,citation_author=J. Laurie Snell;,citation_publication_date=1976;,citation_cover_date=1976;,citation_year=1976;">
<meta name="citation_reference" content="citation_title=Phasic: A library for modelling and inference on markov jump processes;,citation_author=Kasper Munch;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_fulltext_html_url=https://munch-group.org/phasic/;">
<meta name="citation_reference" content="citation_title=Inferring whole-genome histories in large population datasets;,citation_author=Jerome Kelleher;,citation_author=Yan Wong;,citation_author=Anthony W. Wohns;,citation_author=Chaimaa Fadil;,citation_author=Patrick K. Albers;,citation_author=Gil McVean;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_doi=10.1038/s41588-019-0483-y;,citation_journal_title=Nature Genetics;">
<meta name="citation_reference" content="citation_title=Genome-wide coancestry reveals details of ancient and recent male-driven reticulation in baboons;,citation_author=Erik F. Sørensen;,citation_author=others;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_doi=10.1126/science.abn8153;,citation_volume=380;,citation_journal_title=Science;">
<meta name="citation_reference" content="citation_title=The comparative genomics and complex population history of papio baboons;,citation_author=Jeffrey Rogers;,citation_author=Muthuswamy Raveendran;,citation_author=others;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_issue=1;,citation_doi=10.1126/sciadv.aau6947;,citation_volume=5;,citation_journal_title=Science Advances;">
<meta name="citation_reference" content="citation_title=Selection against admixture and gene regulatory divergence in a long-term primate field study;,citation_author=Tauras P. Vilgalys;,citation_author=Arielle S. Fogel;,citation_author=Jordan A. Anderson;,citation_author=others;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_issue=6606;,citation_doi=10.1126/science.abm4917;,citation_volume=377;,citation_journal_title=Science;">
<meta name="citation_reference" content="citation_title=Inference of population history using coalescent HMMs: Review and outlook;,citation_author=Jeffrey P. Spence;,citation_author=Matthias Steinrücken;,citation_author=Jonathan Terhorst;,citation_author=Yun S. Song;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_doi=https://doi.org/10.1016/j.gde.2018.07.002;,citation_journal_title=arXiv preprint arXiv:1807.02763;">
<meta name="citation_reference" content="citation_title=Negative selection on baboon admixture is strongest on chromosome x;,citation_author=Erik Fogh Sørensen;,citation_author=Garrett Hellenthal;,citation_author=Kasper Munch;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_doi=https://doi.org/10.1101/2024.12.18.629079;,citation_journal_title=bioRxiv / preprint;">
<meta name="citation_reference" content="citation_title=Further evidence for phenotypic signatures of hybridization in descendant baboon populations;,citation_author=Rebecca R. Ackermann;,citation_author=Lauren Schroeder;,citation_author=Jeffrey Rogers;,citation_author=James M. Cheverud;,citation_publication_date=2014;,citation_cover_date=2014;,citation_year=2014;,citation_doi=https://doi.org/10.1016/j.jhevol.2014.05.004https://doi.org/10.1016/j.jhevol.2014.05.004;,citation_volume=76;,citation_journal_title=Journal of Human Evolution;,citation_publisher=Elsevier;">
<meta name="citation_reference" content="citation_title=Genetic ancestry predicts male-female affiliation in a natural baboon hybrid zone;,citation_author=Arielle S. Fogel;,citation_author=Emily M. McLean;,citation_author=Jacob B. Gordon;,citation_author=Elizabeth A. Archie;,citation_author=Jenny Tung;,citation_author=Susan C. Alberts;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_doi=10.1016/j.anbehav.2021.07.009;,citation_volume=180;,citation_journal_title=Animal Behaviour;">
<meta name="citation_reference" content="citation_title=A computational reconstruction of papio phylogeny using alu insertion polymorphisms;,citation_author=Vallmer E. Jordan;,citation_author=Jerilyn A. Walker;,citation_author=Thomas O. Beckstrom;,citation_author=Cody J. Steely;,citation_author=Cullen L. McDaniel;,citation_author=others;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_doi=10.1186/s13100-018-0118-3;,citation_volume=9;,citation_journal_title=Mobile DNA;">
<meta name="citation_reference" content="citation_title=A comprehensive overview of baboon phylogenetic history;,citation_author=Gisela H. Kopp;,citation_author=Riashna Sithaldeen;,citation_author=Franziska Trede;,citation_author=Franziska Grathwol;,citation_author=Christian Roos;,citation_author=Dietmar Zinner;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_doi=10.3390/genes14030614;,citation_volume=14;,citation_journal_title=Genes;">
<meta name="citation_reference" content="citation_title=Coalescent theory: An introduction;,citation_author=John Wakeley;,citation_publication_date=2009;,citation_cover_date=2009;,citation_year=2009;">
<meta name="citation_reference" content="citation_title=Matrix-exponential distributions in applied probability;,citation_author=Mogens Bladt;,citation_author=Bo Friis Nielsen;,citation_publication_date=2017;,citation_cover_date=2017;,citation_year=2017;,citation_fulltext_html_url=https://doi.org/10.1007/978-1-4939-7049-0;,citation_doi=10.1007/978-1-4939-7049-0;,citation_volume=81;,citation_series_title=Probability theory and stochastic modelling;">
<meta name="citation_reference" content="citation_title=Matrix-geometric solutions in stochastic models: An algorithmic approach;,citation_author=Marcel F. Neuts;,citation_publication_date=1981;,citation_cover_date=1981;,citation_year=1981;">
<meta name="citation_reference" content="citation_title=The coalescent;,citation_author=John F. C. Kingman;,citation_publication_date=1982;,citation_cover_date=1982;,citation_year=1982;,citation_fulltext_html_url=https://doi.org/10.1016/0304-4149(82)90011-4;,citation_issue=3;,citation_doi=10.1016/0304-4149(82)90011-4;,citation_volume=13;,citation_journal_title=Stochastic Processes and Their Applications;">
<meta name="citation_reference" content="citation_title=Stein variational gradient descent: A general purpose bayesian inference algorithm;,citation_author=Qiang Liu;,citation_author=Dilin Wang;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;,citation_fulltext_html_url=https://arxiv.org/abs/1608.04471;,citation_volume=29;,citation_journal_title=Advances in Neural Information Processing Systems;">
</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Fase-type fordelinger og Bayesiansk inferens i populationsgenetik</h1>
            <p class="subtitle lead">Koalescentmodeller for enkelt-populationer, to-ø og IM-modellen anvendt på Papio spp.</p>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Authors</div>
          <div class="quarto-title-meta-heading">Affiliations</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Emma Christensen <a href="mailto:au692591@uni.au.dk" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Aarhus University
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Kasper Munch </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Aarhus University, Denmark
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Kasper Urup Kjeldsen </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Aarhus University, Denmark
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
                <div>
            <div class="quarto-title-meta-heading">Published</div>
            <div class="quarto-title-meta-contents">
              <p class="date">May 27, 2026</p>
            </div>
          </div>
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      <div class="quarto-alternate-formats"><div class="quarto-title-meta-heading">Other Formats</div><div class="quarto-title-meta-contents"><p><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></p></div></div></div>
    </div>

    <div>
      <div class="abstract">
        <div class="block-title">Abstract</div>
        <ul>
        <li>Dette speciale udvikler en ramme for Bayesiansk demografisk inferens baseret på eksakte fase-type beregninger kombineret med Stein Variational Gradient Descent (SVGD). Coalescentmodeller for enkelt-populationer, to-ø modellen og Isolation with Migration (IM)-modellen implementeres via phasic-biblioteket og valideres analytisk og med msprime-simulationer. Metoderne anvendes på helgenomsekvenseringsdata fra seks bavian-populationer (<em>Papio</em> spp.) til estimering af effektive populationsstørrelser, migrationsrater og split-tidspunkter.</li>
        </ul>
      </div>
    </div>

    <div>
      <div class="keywords">
        <div class="block-title">Keywords</div>
        <p>Coalescent theory, Phase-type distributions, SVGD, Population genetics, Papio</p>
      </div>
    </div>

    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduktion" id="toc-introduktion" class="nav-link active" data-scroll-target="#introduktion">Introduktion</a>
  <ul class="collapse">
  <li><a href="#coalescent-som-fase-type-fordeling" id="toc-coalescent-som-fase-type-fordeling" class="nav-link" data-scroll-target="#coalescent-som-fase-type-fordeling">Coalescent som fase-type fordeling</a></li>
  <li><a href="#reward-transformationer-sfs-og-kovariansstrukturen" id="toc-reward-transformationer-sfs-og-kovariansstrukturen" class="nav-link" data-scroll-target="#reward-transformationer-sfs-og-kovariansstrukturen">Reward-transformationer, SFS og kovariansstrukturen</a></li>
  <li><a href="#populationsstruktur-time-inhomogeneity-og-im-modellen" id="toc-populationsstruktur-time-inhomogeneity-og-im-modellen" class="nav-link" data-scroll-target="#populationsstruktur-time-inhomogeneity-og-im-modellen">Populationsstruktur, time-inhomogeneity og IM-modellen</a></li>
  <li><a href="#ancestral-recombination-graph-og-joint-probability-inferens" id="toc-ancestral-recombination-graph-og-joint-probability-inferens" class="nav-link" data-scroll-target="#ancestral-recombination-graph-og-joint-probability-inferens">Ancestral Recombination Graph og joint probability-inferens</a></li>
  <li><a href="#bayesiansk-inferens-med-svgd" id="toc-bayesiansk-inferens-med-svgd" class="nav-link" data-scroll-target="#bayesiansk-inferens-med-svgd">Bayesiansk inferens med SVGD</a></li>
  <li><a href="#bavianer-som-modelsystem" id="toc-bavianer-som-modelsystem" class="nav-link" data-scroll-target="#bavianer-som-modelsystem">Bavianer som modelsystem</a></li>
  </ul></li>
  <li><a href="#metode" id="toc-metode" class="nav-link" data-scroll-target="#metode">Metode</a>
  <ul class="collapse">
  <li><a href="#coalescentmodellen-implementering-og-validering" id="toc-coalescentmodellen-implementering-og-validering" class="nav-link" data-scroll-target="#coalescentmodellen-implementering-og-validering">Coalescentmodellen: implementering og validering</a></li>
  <li><a href="#svgd-prior-optimizer-og-standardkonfiguration" id="toc-svgd-prior-optimizer-og-standardkonfiguration" class="nav-link" data-scroll-target="#svgd-prior-optimizer-og-standardkonfiguration">SVGD: prior, optimizer og standardkonfiguration</a></li>
  <li><a href="#to-ø-modellen-im-modellen-og-msprime-validering" id="toc-to-ø-modellen-im-modellen-og-msprime-validering" class="nav-link" data-scroll-target="#to-ø-modellen-im-modellen-og-msprime-validering">To-ø modellen, IM-modellen og msprime-validering</a></li>
  <li><a href="#time-inhomogeneous-coalescent-og-joint-probability" id="toc-time-inhomogeneous-coalescent-og-joint-probability" class="nav-link" data-scroll-target="#time-inhomogeneous-coalescent-og-joint-probability">Time-inhomogeneous coalescent og joint probability</a></li>
  </ul></li>
  <li><a href="#resultater" id="toc-resultater" class="nav-link" data-scroll-target="#resultater">Resultater</a>
  <ul class="collapse">
  <li><a href="#coalescentens-analytiske-egenskaber-og-skalering" id="toc-coalescentens-analytiske-egenskaber-og-skalering" class="nav-link" data-scroll-target="#coalescentens-analytiske-egenskaber-og-skalering">Coalescent’ens analytiske egenskaber og skalering</a></li>
  <li><a href="#svgd-validering" id="toc-svgd-validering" class="nav-link" data-scroll-target="#svgd-validering">SVGD-validering</a></li>
  <li><a href="#to-ø-modellen-identifiability-asymmetri-og-demografisk-signal" id="toc-to-ø-modellen-identifiability-asymmetri-og-demografisk-signal" class="nav-link" data-scroll-target="#to-ø-modellen-identifiability-asymmetri-og-demografisk-signal">To-ø modellen: identifiability, asymmetri og demografisk signal</a></li>
  <li><a href="#joint-probability-inferens-informationsindhold-og-grænser" id="toc-joint-probability-inferens-informationsindhold-og-grænser" class="nav-link" data-scroll-target="#joint-probability-inferens-informationsindhold-og-grænser">Joint probability-inferens: informationsindhold og grænser</a></li>
  </ul></li>
  <li><a href="#diskussion" id="toc-diskussion" class="nav-link" data-scroll-target="#diskussion">Diskussion</a></li>
  <li><a href="#konklusion" id="toc-konklusion" class="nav-link" data-scroll-target="#konklusion">Konklusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#appendiks" id="toc-appendiks" class="nav-link" data-scroll-target="#appendiks">Appendiks</a>
  <ul class="collapse">
  <li><a href="#data-availability" id="toc-data-availability" class="nav-link" data-scroll-target="#data-availability">Data Availability</a></li>
  <li><a href="#brug-af-generativ-kunstig-intelligens" id="toc-brug-af-generativ-kunstig-intelligens" class="nav-link" data-scroll-target="#brug-af-generativ-kunstig-intelligens">Brug af Generativ Kunstig Intelligens</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<!-- Italics are "grayed out" to make the example use stand out from dummy content. To make them black, just remove the last line in header_extra.tex: "\renewcommand\emph[1]{\oldemph{\color{gray}#1}}" -->
<section id="introduktion" class="level1">
<h1>Introduktion</h1>
<p>Hvordan kan man rekonstruere en populations evolutionære historie fra DNA-sekvenser? Det er det centrale spørgsmål i demografisk inferens, og svaret kræver matematiske modeller der forbinder observerede genetiske mønstre med de underliggende processer: genetisk drift, mutation, rekombination og migration. Dette speciale undersøger, hvordan coalescent-teorien formuleret som fase-type fordelinger giver en eksakt analytisk ramme til dette formål, og hvordan Bayesiansk inferens via Stein Variational Gradient Descent (SVGD) kan bruges til at estimere demografiske parametre fra genomdata.</p>
<p>Det matematiske fundament er Markov-processer. En stokastisk proces <span class="math inline">\(\{X_t\}_{t \geq 0}\)</span> er en Markov-proces hvis den fremtidige udvikling kun afhænger af den nuværende tilstand og ikke af processens tidligere forløb, <span class="math inline">\(P(X_{t+s} = j \mid X_u, u \leq t) = P(X_{t+s} = j \mid X_t)\)</span>. En kontinuert Markov-kæde (CTMC) er karakteriseret ved et diskret tilstandsrum og kontinuert tid, hvor processen befinder sig i tilstand <span class="math inline">\(i\)</span> i en eksponentielt fordelt ventetid med rate <span class="math inline">\(\lambda_i\)</span> og springer til tilstand <span class="math inline">\(j \neq i\)</span> med sandsynlighed <span class="math inline">\(p_{ij}\)</span>. Overgangene samles i intensitetsmatricen <span class="math inline">\(\mathbf{Q}\)</span> med indgange <span class="math inline">\(Q_{ij} = \lambda_i p_{ij}\)</span> for <span class="math inline">\(i \neq j\)</span> og <span class="math inline">\(Q_{ii} = -\lambda_i\)</span> og sandsynlighedsfordelingen over tilstande til tid <span class="math inline">\(t\)</span> er givet ved matrixeksponentialet <span class="math inline">\(\mathbf{P}(t) = e^{\mathbf{Q}t}\)</span> <span class="citation" data-cites="kemeny1976">(<a href="#ref-kemeny1976" role="doc-biblioref">Kemeny and Snell 1976</a>)</span>. En absorptions-Markov-kæde opdeler tilstandsrummet i transiente tilstande <span class="math inline">\(\mathcal{T}\)</span> og absorberende tilstande <span class="math inline">\(\mathcal{A}\)</span> og den centrale størrelse <span class="math inline">\(\mathbf{U} = (-\mathbf{S})^{-1}\)</span> Green-matricen giver den forventede opholdstid i hvert transient tilstand <span class="citation" data-cites="BladtNielsen2017">(<a href="#ref-BladtNielsen2017" role="doc-biblioref">Bladt and Nielsen 2017</a>)</span>.</p>
<section id="coalescent-som-fase-type-fordeling" class="level2">
<h2 class="anchored" data-anchor-id="coalescent-som-fase-type-fordeling">Coalescent som fase-type fordeling</h2>
<p>Coalescent-teorien beskriver de genealogiske relationer mellem DNA-sekvenser ved at følge genetiske linjer bagud i tid til fælles forfædre <span class="citation" data-cites="wakeley2009coalescent">(<a href="#ref-wakeley2009coalescent" role="doc-biblioref">Wakeley 2009</a>)</span>. Udgangspunktet er Wright-Fisher-modellen: en diploid population af konstant størrelse <span class="math inline">\(N\)</span> individer, hvor sandsynligheden for at to linjer deler forfader i samme generation er <span class="math inline">\(1/(2N)\)</span>. I grænsen <span class="math inline">\(N \to \infty\)</span> med tidsskalering <span class="math inline">\(t \to t/(2N)\)</span> generationer konvergerer de diskrete slægtsskabsprocesser til Kingmans coalescent <span class="citation" data-cites="Kingman1982">(<a href="#ref-Kingman1982" role="doc-biblioref">Kingman 1982</a>)</span>, en kontinuert Markov-kæde baglæns i tid. Med <span class="math inline">\(k\)</span> aktive linjer sker den næste coalescence event med rate <span class="math inline">\(\binom{k}{2} = k(k-1)/2\)</span> og processen absorberes i MRCA-tilstanden (Most Recent Common Ancestor) når alle linjer er smeltet sammen. For en stikprøve af størrelse <span class="math inline">\(n\)</span> repræsenteres tilstanden ved vektoren <span class="math inline">\(\mathbf{a} = (a_1, a_2, \ldots, a_n)\)</span>, hvor <span class="math inline">\(a_i\)</span> angiver antallet af linjer med præcis <span class="math inline">\(i\)</span> efterkommere i samplet.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/01_coalescent_basics.ipynb" data-notebook-title="Notebook 1: coalescent som fase-type fordeling" data-notebook-cellid="cell-fig-graf">
<div id="cell-fig-graf" class="cell">
<div class="cell-output cell-output-display" data-execution_count="3">
<div id="fig-graf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-graf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-01_coalescent_basics-fig-graf-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Tilstandsrum for coalescent med n=4 prøver. Tilstandsvektoren (s_1,s_2,s_3,s_4) tæller linjer med 1, 2, 3 og 4 efterkommere. Starttilstanden 4,0,0,0) er fire singletons og absorptionstilstanden (0,0,0,1) er MRCA."><img src="index_files/figure-html/..-notebooks-01_coalescent_basics-fig-graf-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-graf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Tilstandsrum for coalescent med <span class="math inline">\(n=4\)</span> prøver. Tilstandsvektoren (<span class="math inline">\(s_1,s_2,s_3,s_4\)</span>) tæller linjer med <span class="math inline">\(1, 2, 3\)</span> og <span class="math inline">\(4\)</span> efterkommere. Starttilstanden <span class="math inline">\(4,0,0,0)\)</span> er fire singletons og absorptionstilstanden <span class="math inline">\((0,0,0,1)\)</span> er MRCA.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Coalescentens centrale analytiske egenskaber er givet ved <span class="math inline">\(\mathbb{E}[H] = 2(1 - 1/n)\)</span> og <span class="math inline">\(\text{Var}[H] = 4\sum_{k=2}^{n} 1/[k^2(k-1)^2]\)</span>, hvor <span class="math inline">\(H\)</span> er den totale træhøjde (TMRCA). Den forventede sojourn-tid i fasen med <span class="math inline">\(k\)</span> linjer er <span class="math inline">\(2/[k(k-1)]\)</span> og fasen med <span class="math inline">\(k = 2\)</span> udgør <span class="math inline">\(67\%\)</span> af den forventede TMRCA for <span class="math inline">\(n=4\)</span> coalescenten bruger altså det meste af sin tid med blot to tilbageværende linjer. Forventet antal aktive linjer falder hurtigt tidligt men langsomt i de sene stadier, som <a href="#fig-aktive-linjer" class="quarto-xref">Figure&nbsp;2</a> illustrerer.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/01_coalescent_basics.ipynb" data-notebook-title="Notebook 1: coalescent som fase-type fordeling" data-notebook-cellid="cell-fig-aktive-linjer">
<div id="cell-fig-aktive-linjer" class="cell">
<div class="cell-output cell-output-display">
<div id="fig-aktive-linjer" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-aktive-linjer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-01_coalescent_basics-fig-aktive-linjer-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: Forventet antal aktive linjer og fordeling per linje-type over tid (n=4). Processen reducerer hurtigt fra 4 til ~2 linjer men bruger lang tid på det sidste skridt mod MRCA."><img src="index_files/figure-html/..-notebooks-01_coalescent_basics-fig-aktive-linjer-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-aktive-linjer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Forventet antal aktive linjer og fordeling per linje-type over tid (n=4). Processen reducerer hurtigt fra 4 til ~2 linjer men bruger lang tid på det sidste skridt mod MRCA.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Variansen skalerer kvadratisk med den effektive populationsstørrelse <span class="math inline">\(N_e\)</span>: en fordobling af <span class="math inline">\(N_e\)</span> fordobler <span class="math inline">\(\mathbb{E}[H]\)</span> men firedobler <span class="math inline">\(\text{Var}[H]\)</span>. For bavian-realistiske <span class="math inline">\(N_e \in \{5.000, \ldots, 200.000\}\)</span> med <span class="math inline">\(g = 11\)</span> år og <span class="math inline">\(\mu = 0{,}9 \times 10^{-8}\)</span> giver dette forventede TMRCA-værdier på <span class="math inline">\(36.000\)</span>–<span class="math inline">\(2.890.000\)</span> år med standardafvigelser af samme størrelsesorden, hvilket afspejler den store stokastiske variabilitet der er en egenskab ved den genealogiske proces.</p>
<p>Kingmans coalescent er eksakt en fase-type fordeling <span class="math inline">\(\tau \sim \text{PH}(\alpha, \mathbf{S})\)</span>, hvor absorptionstiden <span class="math inline">\(\tau\)</span> er TMRCA, <span class="math inline">\(\alpha = (1, 0, \ldots, 0)\)</span> er starttilstanden og <span class="math inline">\(\mathbf{S}\)</span> er sub-intensitetsmatricen <span class="citation" data-cites="BladtNielsen2017">(<a href="#ref-BladtNielsen2017" role="doc-biblioref">Bladt and Nielsen 2017</a>)</span>. Fordelingsfunktion, tæthedsfunktion og alle momenter udtrykkes via matrixoperationer: <span class="math inline">\(F(t) = 1 - \alpha e^{\mathbf{S}t}\mathbf{e}\)</span>, <span class="math inline">\(f(t) = \alpha e^{\mathbf{S}t}\mathbf{s}\)</span>, og <span class="math inline">\(\mathbb{E}[\tau^n] = n!\,\alpha(-\mathbf{S})^{-n}\mathbf{e}\)</span>. Sub-intensitetsmatricen <span class="math inline">\(\mathbf{S}\)</span> indeholder coalescence rater <span class="math inline">\(-\binom{k}{2}\)</span> på diagonalen og overgange til tilstande med færre linjer på off-diagonalen og for <span class="math inline">\(n = 4\)</span> er matricen <span class="math display">\[
\mathbf{S} =
\begin{pmatrix}
-6 &amp; 6 &amp; 0 &amp; 0 \\
0 &amp; -3 &amp; 1 &amp; 2 \\
0 &amp; 0 &amp; -1 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; -1
\end{pmatrix}.
\]</span></p>
<p>Alle centrale størrelser er dermed tilgængelige analytisk uden simulering og fase-type teorien er implementeret i <em>phasic</em>-biblioteket <span class="citation" data-cites="phasic">(<a href="#ref-phasic" role="doc-biblioref">Munch 2026</a>)</span>, der repræsenterer Markov jump-processer som grafer frem for matricer. Brugerdefinerede modeller specificeres via en simpel callback-funktion, og grafbaserede algoritmer implementeret direkte i C med Python API udfører alle beregninger. Symbolske elimineringsspor caches og genbruges på tværs af parametriserede modeller, hvilket giver størrelsesordener hurtigere beregning end matrixbaserede tilgange for store, sparsomme tilstandsrum.</p>
</section>
<section id="reward-transformationer-sfs-og-kovariansstrukturen" class="level2">
<h2 class="anchored" data-anchor-id="reward-transformationer-sfs-og-kovariansstrukturen">Reward-transformationer, SFS og kovariansstrukturen</h2>
<p>Reward-transformationer forbinder coalescent-modellen med observerede genetiske data <span class="citation" data-cites="hobolth2019 hobolth2021">(<a href="#ref-hobolth2019" role="doc-biblioref">Hobolth et al. 2019</a>, <a href="#ref-hobolth2021" role="doc-biblioref">2021</a>)</span>. En reward-funktion <span class="math inline">\(r: \mathcal{T} \to \mathbb{R}_+\)</span> tildeler en ikke-negativ vægt til hvert transient tilstand og den akkumulerede reward <span class="math inline">\(Y = \int_0^\tau r(X_t) dt\)</span> er igen fase-type fordelt med forventning <span class="math inline">\(\mathbb{E}[Y] = \alpha(-\mathbf{S})^{-1}\mathbf{r}\)</span>. Ved at lade <span class="math inline">\(\mathbf{r}_k\)</span> tælle antallet af linjer med præcis <span class="math inline">\(k\)</span> efterkommere beregnes Site Frequency Spectrum (SFS) direkte: den forventede grenlængde for frekvensklasse <span class="math inline">\(k\)</span> er <span class="math inline">\(\mathbb{E}[B_k] = \alpha(-\mathbf{S})^{-1}\mathbf{r}_k\)</span> og det forventede antal <span class="math inline">\(k\)</span>-ton mutationer under infinite-sites modellen er <span class="math inline">\(\mathbb{E}[\xi_k] = \theta \cdot \mathbb{E}[B_k]\)</span>, hvor <span class="math inline">\(\theta = 4N_e\mu\)</span> er Wattersons parameter for diploide populationer <span class="citation" data-cites="Hobolth2024">(<a href="#ref-Hobolth2024" role="doc-biblioref">Hobolth et al. 2024</a>)</span>. For <span class="math inline">\(n = 4\)</span> er <span class="math inline">\((\mathbb{E}[B_1], \mathbb{E}[B_2], \mathbb{E}[B_3]) = (2{,}000, 1{,}000, 0{,}667)\)</span> og singletons udgør <span class="math inline">\(54{,}5\%\)</span> af grenlængden, et mønster der afspejler at de fleste mutationer opstår på korte ydre grene sent i genealogien.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/01_coalescent_basics.ipynb" data-notebook-title="Notebook 1: coalescent som fase-type fordeling" data-notebook-cellid="cell-fig-sfs">
<div id="cell-fig-sfs" class="cell">
<div class="cell-output cell-output-display">
<div id="fig-sfs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sfs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-01_coalescent_basics-fig-sfs-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;3: Site Frequency Spectrum for n=4. Forventet grenlængde per frekvensklasse beregnet via reward-transformation."><img src="index_files/figure-html/..-notebooks-01_coalescent_basics-fig-sfs-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sfs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Site Frequency Spectrum for n=4. Forventet grenlængde per frekvensklasse beregnet via reward-transformation.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Den multivariate fase-type ramme giver desuden adgang til kovariansstrukturen i SFS, <span class="math inline">\(\text{Cov}(B_i, B_j) = \alpha(-\mathbf{S})^{-1}\Delta(\mathbf{r}_i)(-\mathbf{S})^{-1}\mathbf{r}_j + \alpha(-\mathbf{S})^{-1}\Delta(\mathbf{r}_j)(-\mathbf{S})^{-1}\mathbf{r}_i - \mathbb{E}[B_i]\mathbb{E}[B_j]\)</span>, hvor <span class="math inline">\(\Delta(\mathbf{r})\)</span> er diagonalmatricen med reward-vektoren på diagonalen. Singletons og doubletons er negativt korrelerede (<span class="math inline">\(\text{Cov}(B_1, B_2) = -0{,}222\)</span>) fordi de konkurrerer om grenlængde-budgettet, mens singletons og tripletons er positivt korrelerede (<span class="math inline">\(\text{Cov}(B_1, B_3) = +0{,}889\)</span>) fordi begge akkumuleres tidligt i coalescenten. Denne kovariansstruktur har direkte konsekvenser for inferens: en naiv antagelse om uafhængighed mellem SFS-komponenter undervurderer usikkerheden på demografiske estimater og er en af de primære motivationer for at bruge joint probability-inferens frem for marginal SFS. Under infinite-sites modellen er det samlede antal segregerende sites <span class="math inline">\(S\)</span> diskret fase-type fordelt, og joint-sandsynligheder for specifikke SFS-mønstre er eksakt beregneligt via diskrete fase-type metoder <span class="citation" data-cites="Neuts1981 Hobolth2024">(<a href="#ref-Neuts1981" role="doc-biblioref">Neuts 1981</a>; <a href="#ref-Hobolth2024" role="doc-biblioref">Hobolth et al. 2024</a>)</span>. PMF for antal segregerende sites er højreskæv med stor sandsynlighed for få mutationer per locus under bavian-parametre er <span class="math inline">\(P(S = 0) \approx 0{,}85\)</span> og fordelingen nærmer sig Poisson ved høj <span class="math inline">\(N_e\)</span> og <span class="math inline">\(\mu\)</span>.</p>
</section>
<section id="populationsstruktur-time-inhomogeneity-og-im-modellen" class="level2">
<h2 class="anchored" data-anchor-id="populationsstruktur-time-inhomogeneity-og-im-modellen">Populationsstruktur, time-inhomogeneity og IM-modellen</h2>
<p>Den klassiske coalescent antager en homogen, panmiktisk population, men populationer er i praksis opdelt i subpopulationer med begrænset migration. I den strukturerede coalescent kan genealogiske linjer skifte subpopulation bagud i tid <span class="citation" data-cites="wakeley2009coalescent">(<a href="#ref-wakeley2009coalescent" role="doc-biblioref">Wakeley 2009</a>)</span>, og coalescence-tiderne for sekvenser fra samme versus forskellige populationer afspejler graden af isolation. Den simpleste strukturerede model er <strong>to-ø modellen</strong>: to populationer af størrelse <span class="math inline">\(N\)</span> udveksler migration med rate <span class="math inline">\(m\)</span> per generation og coalescence er kun mulig inden for samme population. I coalescent-enheder parameteriseres modellen ved <span class="math inline">\(\theta_0 = 4N\mu\)</span> (coalescence rate) og <span class="math inline">\(\theta_1 = 2Nm\)</span> (migrationsrate) og et centralt problem er parameter-confounding: <span class="math inline">\(\mathbb{E}[\text{TMRCA}]\)</span> er identisk ved <span class="math inline">\(\theta_1 \to 0\)</span> og <span class="math inline">\(\theta_1 \to \infty\)</span> fordi linjer der migrerer hurtigt opfører sig som en panmiktisk population. Som <a href="#fig-migration-tmrca" class="quarto-xref">Figure&nbsp;4</a> viser, er variansen maksimal ved meget lav migration fordi coalescence-tiden afhænger af sjældne migrationsbegivenheder der fluktuerer stærkt. Dette identifiability-problem viser sig direkte i SVGD-posterior: for <span class="math inline">\(\theta_1 &lt; 0{,}5\)</span> er den parvise posterior bred og negativt korreleret, og parametrene er i praksis ikke adskillelige. Asymmetrisk migration <span class="math inline">\(m_{12} \neq m_{21}\)</span> er ikke identifiable fra <span class="math inline">\(n=2\)</span> observationer summen <span class="math inline">\(m_{12} + m_{21}\)</span> er identifiable men ikke de individuelle retninger og <span class="math inline">\(n \geq 4\)</span> er nødvendigt for at adskille de to retninger <span class="citation" data-cites="Hobolth2024">(<a href="#ref-Hobolth2024" role="doc-biblioref">Hobolth et al. 2024</a>)</span>.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/03_svgd_two_island.ipynb" data-notebook-title="Notebook 3: Identifiability og inferens i to-ø modellen" data-notebook-cellid="cell-fig-migration-tmrca">
<div id="cell-fig-migration-tmrca" class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Maks varians ved theta1 = 0.010
E[TMRCA] ved theta1-&gt;0   = 2.8571
E[TMRCA] ved theta1-&gt;100 = 2.8571
Standard koalescent E[H] = 1.4286</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-migration-tmrca" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-migration-tmrca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-migration-tmrca-output-2.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;4: E[TMRCA] og Var[TMRCA] som funktion af migrationsrate theta1 (log-skala, n=2). Venstre: E[TMRCA] er identisk ved theta1 nær nul og theta1 nær uendelig (begge 2.857) og afviger fra standard-koalescent E[H]=1.429. Højre: maksimal varians opstår ved meget lav migration (theta1=0.010) ikke ved moderat migration som forventet."><img src="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-migration-tmrca-output-2.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-migration-tmrca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: E[TMRCA] og Var[TMRCA] som funktion af migrationsrate theta1 (log-skala, n=2). Venstre: E[TMRCA] er identisk ved theta1 nær nul og theta1 nær uendelig (begge 2.857) og afviger fra standard-koalescent E[H]=1.429. Højre: maksimal varians opstår ved meget lav migration (theta1=0.010) ikke ved moderat migration som forventet.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Coalescence raten <span class="math inline">\(\lambda_k(t) = \binom{k}{2}/N(t)\)</span> varierer med tid når <span class="math inline">\(N(t)\)</span> ikke er konstant. En time-inhomogeneous coalescent modellerer denne variation ved at opdele historien i epoker med stykvist konstant <span class="math inline">\(N_e\)</span> og time-inhomogeneity kombineres direkte med fase-type rammen via <em>add_epoch</em> der skifter til en ny callback-funktion ved et fast split-tidspunkt. Populationsflaskehalse viser sig i TMRCA-fordelingen som en bule ved det tidspunkt flaskehalsen opstod som vist i <a href="#fig-bottleneck-cdf" class="quarto-xref">Figure&nbsp;5</a> ændrer en moderat flaskehals (<span class="math inline">\(f = 2\)</span>–<span class="math inline">\(10\)</span>) næsten ikke <span class="math inline">\(\mathbb{E}[\text{TMRCA}]\)</span> fordi de fleste linjer allerede er coalesced inden flaskehalsen. Det er flaskehalstidspunktet snarere end dybden der er diagnostisk: en tidlig flaskehals øger alle SFS-komponenter markant, mens en sen flaskehals har minimal effekt. Fem demografiske scenarier er vist i <a href="#fig-multiepoch" class="quarto-xref">Figure&nbsp;6</a>.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/05_time_inhomogeneous.ipynb" data-notebook-title="Notebook 5: Tidsinhomogen coalescent og inferens" data-notebook-cellid="cell-fig-bottleneck-cdf">
<div id="cell-fig-bottleneck-cdf" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-bottleneck-cdf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bottleneck-cdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-bottleneck-cdf-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;5: CDF og PDF for Kingmans coalescent under varierende flaskehals-dybde (f=N/N_bottle). En moderat flaskehals (f=2 til f=10) ændrer næsten ikke E[TMRCA] som forbliver 1.5 coalescentenheder. Kun en ekstrem flaskehals (f=50) reducerer E[TMRCA] mærkbart til 1.0. PDF viser en karakteristisk bule i flaskehalsperioden [0.5, 0.9] der vokser med dybden."><img src="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-bottleneck-cdf-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bottleneck-cdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: CDF og PDF for Kingmans coalescent under varierende flaskehals-dybde (f=N/N_bottle). En moderat flaskehals (f=2 til f=10) ændrer næsten ikke E[TMRCA] som forbliver 1.5 coalescentenheder. Kun en ekstrem flaskehals (f=50) reducerer E[TMRCA] mærkbart til 1.0. PDF viser en karakteristisk bule i flaskehalsperioden [0.5, 0.9] der vokser med dybden.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> Dybde f=N/N_b  N_bottle  E[TMRCA]
           1.0      1.00    1.5000
           2.0      0.50    1.5000
           5.0      0.20    1.5000
          10.0      0.10    1.4992
          50.0      0.02    1.0033</code></pre>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/05_time_inhomogeneous.ipynb" data-notebook-title="Notebook 5: Tidsinhomogen coalescent og inferens" data-notebook-cellid="cell-fig-multiepoch">
<div id="cell-fig-multiepoch" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-multiepoch" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-multiepoch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-multiepoch-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;6: CDF og PDF for fem demografiske scenarier: konstant, ekspansion, kontraktion, flaskehals+recovery og trinvis vækst. Ekspansion giver en stejl CDF tidligt fordi den nuværende population er lille. Kontraktion giver den fladeste CDF. Flaskehals+recovery viser en S-form med knæk ved epoch-grænser. Demografisk historie former TMRCA-fordelingen tydeligt."><img src="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-multiepoch-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-multiepoch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: CDF og PDF for fem demografiske scenarier: konstant, ekspansion, kontraktion, flaskehals+recovery og trinvis vækst. Ekspansion giver en stejl CDF tidligt fordi den nuværende population er lille. Kontraktion giver den fladeste CDF. Flaskehals+recovery viser en S-form med knæk ved epoch-grænser. Demografisk historie former TMRCA-fordelingen tydeligt.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>IM-modellen</strong> (Isolation with Migration) kombinerer populationsstruktur med time-inhomogeneity: to separate populationer med migration eksisterer i perioden <span class="math inline">\([0, t_s]\)</span> og herefter smeltes til en ancestral population ved split-tidspunktet <span class="math inline">\(t_s\)</span>. IM-modellen giver systematisk højere forventet TMRCA end to-ø uden split, fordi linjer der overlever til <span class="math inline">\(t_s\)</span> derefter coalescer i den ancestrale population med rate <span class="math inline">\(1/\theta_a\)</span> og <a href="#fig-im-tmrca" class="quarto-xref">Figure&nbsp;7</a> viser at <span class="math inline">\(\mathbb{E}[\text{TMRCA}]\)</span> falder monotont med stigende <span class="math inline">\(t_s\)</span>.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/05_time_inhomogeneous.ipynb" data-notebook-title="Notebook 5: Tidsinhomogen coalescent og inferens" data-notebook-cellid="cell-fig-im-tmrca">
<div id="cell-fig-im-tmrca" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div id="fig-im-tmrca" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-im-tmrca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-im-tmrca-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;7: E[TMRCA] for IM-modellen som funktion af split-tidspunkt t_s (coalescentenheder). IM-modellen giver konsekvent højere E[TMRCA] end to-ø uden split (stiplet linje ved 2.857). Effekten er størst ved kort split-tidspunkt (E[TMRCA]=6.5 ved t_s=0.1) fordi migrationsperioden er for kort til at linjerne coalescerer inden splittet og de er herefter tvunget til at vente i den ancestrale population."><img src="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-im-tmrca-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-im-tmrca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: E[TMRCA] for IM-modellen som funktion af split-tidspunkt t_s (coalescentenheder). IM-modellen giver konsekvent højere E[TMRCA] end to-ø uden split (stiplet linje ved 2.857). Effekten er størst ved kort split-tidspunkt (E[TMRCA]=6.5 ved t_s=0.1) fordi migrationsperioden er for kort til at linjerne coalescerer inden splittet og de er herefter tvunget til at vente i den ancestrale population.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>To-ø uden split:  E[TMRCA] = 2.8571
IM-model ved t_s=0.1:   E[TMRCA] = 6.5259
IM-model ved t_s=5.0:   E[TMRCA] = 4.4719</code></pre>
</div>
</div>
</div>
</section>
<section id="ancestral-recombination-graph-og-joint-probability-inferens" class="level2">
<h2 class="anchored" data-anchor-id="ancestral-recombination-graph-og-joint-probability-inferens">Ancestral Recombination Graph og joint probability-inferens</h2>
<p>For to loci med rekombinationsrate <span class="math inline">\(\rho/2\)</span> per locus beskrives genealogien ved Ancestral Recombination Graph (ARG) <span class="citation" data-cites="hobolth2021">(<a href="#ref-hobolth2021" role="doc-biblioref">Hobolth et al. 2021</a>)</span>. Tilstanden beskrives ved triplet <span class="math inline">\((K_{ab}, K_a, K_b)\)</span> antallet af linjer med ancestral materiale i begge, kun locus <span class="math inline">\(a\)</span>, og kun locus <span class="math inline">\(b\)</span> og overgange sker via coalescence og rekombination med samlet intensitetsmatrix <span class="math inline">\(\mathbf{Q} = \mathbf{Q}^c + \frac{\rho}{2}\mathbf{Q}^r\)</span> <span class="citation" data-cites="Hobolth2018 hobolth2021">(<a href="#ref-Hobolth2018" role="doc-biblioref">Hobolth et al. 2018</a>, <a href="#ref-hobolth2021" role="doc-biblioref">2021</a>)</span>. Laplace-transformationen <span class="math inline">\(\psi(\omega) = \alpha(\omega\mathbf{I} - \mathbf{S})^{-1}\mathbf{t}\)</span> giver sandsynligheden for at to loci deler samme genealogi, og P(ingen rekombination) falder monotont med rekombinationsraten og er lavere for store populationer fordi coalescenten tager lang tid og rekombination har mere tid at operere (<a href="#fig-laplace" class="quarto-xref">Figure&nbsp;8</a>).</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/05_time_inhomogeneous.ipynb" data-notebook-title="Notebook 5: Tidsinhomogen coalescent og inferens" data-notebook-cellid="cell-fig-laplace">
<div id="cell-fig-laplace" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-laplace" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-laplace-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-laplace-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;8: P(ingen rekombination) som funktion af rekombinationsrate rho for tre populationsstørrelser (N=0.5, 1.0, 3.0). Store populationer har lavere sandsynlighed for fælles genealogi fordi koalescenten tager lang tid og rekombination har mere tid at operere. Log-log plottet viser at kurven ikke er en ren potenslov."><img src="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-laplace-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-laplace-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: P(ingen rekombination) som funktion af rekombinationsrate rho for tre populationsstørrelser (N=0.5, 1.0, 3.0). Store populationer har lavere sandsynlighed for fælles genealogi fordi koalescenten tager lang tid og rekombination har mere tid at operere. Log-log plottet viser at kurven ikke er en ren potenslov.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Joint probability-inferens udnytter diskrete observationer specifikke kombinationer af <span class="math inline">\(k\)</span>-ton mutationer frem for kontinuerte TMRCA-tider. Via <em>joint_prob_graph</em> konstrueres en udvidet graf der tracker alle kombinationer op til en øvre grænse <em>tot_reward_limit</em>, og deficit er andelen af sandsynlighedsmasse der ikke er repræsenteret i tabellen. For mu=1.0 og limit=3 er deficit 0,66% acceptabelt til inferens mens mu=2.0 kræver limit=7. <a href="#fig-heatmap-joint" class="quarto-xref">Figure&nbsp;9</a> viser at joint-sandsynlighedstabellets form ændrer sig systematisk med <span class="math inline">\(\theta\)</span>: lav <span class="math inline">\(\theta\)</span> giver koncentration i hjørnet ved få mutationer, mens høj <span class="math inline">\(\theta\)</span> giver en bredere og mere jævn fordeling og denne form-ændring indeholder information om <span class="math inline">\(\theta\)</span> ud over de marginale frekvenser. To-locus joint-observationer indeholder desuden information om rekombinationsraten: coalescence rate og rekombinationsrate estimeres simultant fra joint ARG-observationer med lav korrelation i pairwise posterior, i kontrast til to-ø modellens stærke confounding af <span class="math inline">\(\theta_0\)</span> og <span class="math inline">\(\theta_1\)</span> (<a href="#fig-arg-pairwise" class="quarto-xref">Figure&nbsp;10</a>).</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/06_joint_probability_inferens.ipynb" data-notebook-title="Notebook 6: Inferens via joint sandsynligheder og diskrete SFS-observationer" data-notebook-cellid="cell-fig-heatmap-joint">
<div id="cell-fig-heatmap-joint" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-heatmap-joint" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heatmap-joint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-heatmap-joint-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;9: Joint sandsynlighedstabel (1-ton vs.&nbsp;2-ton mutationer) for theta i {2, 7, 20} med mu=1.0 og limit=4. Lav theta giver koncentration i hjørnet ved få mutationer. Høj theta giver en bredere og mere jævn fordeling. Tabellens form ændrer sig systematisk med theta og indeholder information ud over de marginale frekvenser."><img src="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-heatmap-joint-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-heatmap-joint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Joint sandsynlighedstabel (1-ton vs.&nbsp;2-ton mutationer) for theta i {2, 7, 20} med mu=1.0 og limit=4. Lav theta giver koncentration i hjørnet ved få mutationer. Høj theta giver en bredere og mere jævn fordeling. Tabellens form ændrer sig systematisk med theta og indeholder information ud over de marginale frekvenser.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/06_joint_probability_inferens.ipynb" data-notebook-title="Notebook 6: Inferens via joint sandsynligheder og diskrete SFS-observationer" data-notebook-cellid="cell-fig-arg-pairwise">
<div class="cell">
<div id="fig-arg-pairwise" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-arg-pairwise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<div id="fig-arg-pairwise-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-arg-pairwise-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-arg-pairwise-output-1.svg" class="lightbox" data-gallery="fig-arg-pairwise" title="Figure&nbsp;10&nbsp;(a): Pairwise posterior for to-locus ARG-model: coalescensrate theta0=2.986 pm 0.688 (sand 3.0) og rekombinationsrate theta1=0.575 pm 0.533 (sand 0.5). Lav korrelation i pairwise posterior bekræfter at de to parametre er identificerbare fra joint two-locus observationer."><img src="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-arg-pairwise-output-1.svg" class="img-fluid figure-img" data-ref-parent="fig-arg-pairwise"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-arg-pairwise-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Pairwise posterior for to-locus ARG-model: coalescensrate theta0=2.986 pm 0.688 (sand 3.0) og rekombinationsrate theta1=0.575 pm 0.533 (sand 0.5). Lav korrelation i pairwise posterior bekræfter at de to parametre er identificerbare fra joint two-locus observationer.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div id="fig-arg-pairwise-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-arg-pairwise-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-arg-pairwise-output-2.svg" class="lightbox" data-gallery="fig-arg-pairwise" title="Figure&nbsp;10&nbsp;(b): "><img src="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-arg-pairwise-output-2.svg" id="fig-arg-pairwise-2" class="img-fluid figure-img" data-ref-parent="fig-arg-pairwise"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-arg-pairwise-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b)
</figcaption>
</figure>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-arg-pairwise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="bayesiansk-inferens-med-svgd" class="level2">
<h2 class="anchored" data-anchor-id="bayesiansk-inferens-med-svgd">Bayesiansk inferens med SVGD</h2>
<p>Demografisk inferens fra genomdata kan inddeles i tre klasser. PSMC og SMC++ <span class="citation" data-cites="spence2018 kelleher2019">(<a href="#ref-spence2018" role="doc-biblioref">Spence et al. 2018</a>; <a href="#ref-kelleher2019" role="doc-biblioref">Kelleher et al. 2019</a>)</span> udnytter heterozygositetsmønstre til demografisk rekonstruktion men er begrænset til en population og estimerer ikke migrationsrater direkte. Simuleringsbaserede metoder som fastsimcoal2 anvender SFS via komposit-likelihood men kræver mange simuleringer og beregningstung bootstrapping til usikkerhedskvantificering. En fælles begrænsning er fraværet af en eksakt analytisk ramme der kombinerer direkte adgang til sandsynlighedstætheder med fuld Bayesiansk usikkerhedskvantificering.</p>
<p>I dette speciale anvendes Stein Variational Gradient Descent (SVGD) <span class="citation" data-cites="liu2016svgd">(<a href="#ref-liu2016svgd" role="doc-biblioref">Liu and Wang 2016</a>)</span>, en partikelbaseret variationel inferensmetode der repræsenterer posterioren <span class="math inline">\(p(\theta \mid \mathbf{data})\)</span> med <span class="math inline">\(M\)</span> partikler opdateret iterativt: <span class="math display">\[
{\theta}^{(m)} \leftarrow \theta^{(m)}
+ \epsilon\,\phi^*\!\bigl({\theta}^{(m)}\bigr), \qquad
\phi^*(\theta) = \frac{1}{M}\sum_{j=1}^M \Bigl[
k\!\bigl(\theta^{(j)}, \theta\bigr)
\nabla \log p\!\bigl(\theta^{(j)} \mid \mathbf{x}\bigr)
+ \nabla k\!\bigl(\theta^{(j)}, \theta\bigr)
\Bigr],
\]</span></p>
<p>hvor <span class="math inline">\(k(\cdot, \cdot)\)</span> er en RBF-kernel. Det første led trækker partiklerne mod høj posterior-tæthed, og det andet led forhindrer partikelkollaps og bevarer diversitet. Log-posterioren er <span class="math inline">\(\log p(\theta \mid \mathbf{t}) = \sum_i \log f(t_i;\theta) + \log \pi(\theta)\)</span>, hvor <span class="math inline">\(f(t;\theta) = \alpha\exp(\mathbf{S}(\theta)t)(-\mathbf{S})\mathbf{e}\)</span> er den analytisk beregnede fase-type PDF eksakt, ikke approksimativ. I kombination med phasics eksakte likelihood er SVGD fundamentalt forskelligt fra simulationsbaserede metoder og giver fuld posterior frem for et punktestimat.</p>
</section>
<section id="bavianer-som-modelsystem" class="level2">
<h2 class="anchored" data-anchor-id="bavianer-som-modelsystem">Bavianer som modelsystem</h2>
<p>Bavianer (<em>Papio</em> spp.) er en gruppe af seks nært beslægtede primater udbredt i store dele af Afrika <span class="citation" data-cites="rogers2019">(<a href="#ref-rogers2019" role="doc-biblioref"><span class="nocase">Rogers et al.</span> 2019</a>)</span>. Slægten opdeles i en nordlig kladde bestående af <em>P. hamadryas</em>, <em>P. anubis</em> og <em>P. papio</em> og en sydlig kladde bestående af <em>P. kindae</em>, <em>P. cynocephalus</em> og <em>P. ursinus</em>, der divergerede fra en fælles stamfader for mere end 1 million år siden <span class="citation" data-cites="rogers2019 vilgalys2022 kopp2023">(<a href="#ref-rogers2019" role="doc-biblioref"><span class="nocase">Rogers et al.</span> 2019</a>; <a href="#ref-vilgalys2022" role="doc-biblioref"><span class="nocase">Vilgalys et al.</span> 2022</a>; <a href="#ref-kopp2023" role="doc-biblioref">Kopp et al. 2023</a>)</span>. På trods af geografisk adskillelse producerer flere arter fertile hybrider i kontaktzoner <span class="citation" data-cites="sorensen2023 jordan2018papio Ackermann2014">(<a href="#ref-sorensen2023" role="doc-biblioref"><span class="nocase">Erik F. Sørensen et al.</span> 2023</a>; <a href="#ref-jordan2018papio" role="doc-biblioref"><span class="nocase">Jordan et al.</span> 2018</a>; <a href="#ref-Ackermann2014" role="doc-biblioref">Ackermann et al. 2014</a>)</span> og <span class="citation" data-cites="rogers2019"><span class="nocase">Rogers et al.</span> (<a href="#ref-rogers2019" role="doc-biblioref">2019</a>)</span> dokumenterede multiple episoder af admixture og introgression på tværs af alle seks arter. <span class="citation" data-cites="sorensen2023"><span class="nocase">Erik F. Sørensen et al.</span> (<a href="#ref-sorensen2023" role="doc-biblioref">2023</a>)</span> udvidede analysen til 225 vilde bavianer fra 19 lokaliteter og dokumenterede tre-vejs admixture i western yellow-populationerne <span class="citation" data-cites="fogel2021">(<a href="#ref-fogel2021" role="doc-biblioref">Fogel et al. 2021</a>)</span> samt at selektion mod introgresserede varianter er stærkest på X-kromosomet med op til syv gange højere selektionstryk sammenlignet med autosomer <span class="citation" data-cites="sorensen2023_selection">(<a href="#ref-sorensen2023_selection" role="doc-biblioref">Erik Fogh Sørensen et al. 2023</a>)</span>.</p>
<div id="fig-Kort" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-Kort-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="illustrations/Kort.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;11: Nuværende udbredelse af de seks Papio-arter samt placeringen af tre veldokumenterede hybridzoner: x1 (P. hamadryas/P. anubis), x2 (P. cynocephalus/P. anubis) og x3 (P. kindae/P. ursinus). Billede fra @rogers2019."><img src="illustrations/Kort.png" class="img-fluid figure-img" style="width:50.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-Kort-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Nuværende udbredelse af de seks <em>Papio</em>-arter samt placeringen af tre veldokumenterede hybridzoner: x1 (<em>P. hamadryas</em>/<em>P. anubis</em>), x2 (<em>P. cynocephalus</em>/<em>P. anubis</em>) og x3 (<em>P. kindae</em>/<em>P. ursinus</em>). Billede fra <span class="citation" data-cites="rogers2019"><span class="nocase">Rogers et al.</span> (<a href="#ref-rogers2019" role="doc-biblioref">2019</a>)</span>.
</figcaption>
</figure>
</div>
<div id="fig-PSMC" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-PSMC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="illustrations/PSMC.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figure&nbsp;12: Rekonstruktion af demografisk historie for de seks bavianarter via PSMC. Alle populationer viser et fald i N_e de seneste 100.000 år samt population-specifikke flaskehalse. Modificeret fra @rogers2019."><img src="illustrations/PSMC.png" class="img-fluid figure-img" style="width:65.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-PSMC-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Rekonstruktion af demografisk historie for de seks bavianarter via PSMC. Alle populationer viser et fald i <span class="math inline">\(N_e\)</span> de seneste 100.000 år samt population-specifikke flaskehalse. Modificeret fra <span class="citation" data-cites="rogers2019"><span class="nocase">Rogers et al.</span> (<a href="#ref-rogers2019" role="doc-biblioref">2019</a>)</span>.
</figcaption>
</figure>
</div>
<p>Bavianernes evolutionære historie er veldokumenteret, biologisk kompleks og tidsligt parallel med menneskets evolution, hvilket gør dem til et ideelt modelsystem for metodeudvikling. I dette speciale bruges estimater fra <span class="citation" data-cites="sorensen2023"><span class="nocase">Erik F. Sørensen et al.</span> (<a href="#ref-sorensen2023" role="doc-biblioref">2023</a>)</span>: mutationsrate <span class="math inline">\(\mu = 0{,}9 \times 10^{-8}\)</span> per site per generation og generationstid <span class="math inline">\(g = 11\)</span> år til at omsætte modelparametre til absolutte biologiske enheder. Specialets centrale spørgsmål er om coalescent-modellerne kan estimere biologisk meningsfulde parametre fra de rigtige genomdata, og om SVGD-posterioren er kalibreret korrekt. Specialet er opdelt i otte analytiske notebooks: notebooks 01–06 fokuserer på metodeudvikling og analyserer simulerede data under kontrollerede forhold, notebook 07A indeholder databehandling af baviangenomet og notebook 07B anvender modellerne til inferens af populationshistorie for de seks bavianpopulationer.</p>
</section>
</section>
<section id="metode" class="level1">
<h1>Metode</h1>
<p>Alle modeller er implementeret i seks Jupyter notebooks via phasic-pakken, der repræsenterer fase-type fordelinger som vægtede rettede grafer og understøtter eksakt beregning af momenter, PDF, CDF og SVGD-inferens. <a href="#tbl-notebooks" class="quarto-xref">Table&nbsp;1</a> giver en oversigt.</p>
<div id="tbl-notebooks" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-notebooks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Oversigt over de seks notebooks og deres formål.
</figcaption>
<div aria-describedby="tbl-notebooks-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Notebook</th>
<th>Fokus</th>
<th>Tilgang</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>01</td>
<td>Kingmans coalescent som fase-type fordeling</td>
<td>Analytisk verificering, reward-transformation, SFS</td>
</tr>
<tr class="even">
<td>02</td>
<td>Bayesiansk inferens med SVGD</td>
<td>Prior-sensitivitet, learning rate, posterior validering</td>
</tr>
<tr class="odd">
<td>03</td>
<td>Identifiability og inferens i to-ø modellen</td>
<td>SVGD på to-parameter model, MoM-sammenligning</td>
</tr>
<tr class="even">
<td>04</td>
<td>Numerisk præcision og beregningsgrænser</td>
<td>MPFR, state space-udvækst, grid-søgning</td>
</tr>
<tr class="odd">
<td>05</td>
<td>Time-inhomogeneous coalescent og demografisk inferens</td>
<td>Flaskehalse, multi-epoch modeller, IM-modellen</td>
</tr>
<tr class="even">
<td>06</td>
<td>Inferens via joint sandsynligheder og diskrete SFS-observationer</td>
<td><em>joint_prob_graph</em>, deficit, to-locus ARG</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="coalescentmodellen-implementering-og-validering" class="level2">
<h2 class="anchored" data-anchor-id="coalescentmodellen-implementering-og-validering">Coalescentmodellen: implementering og validering</h2>
<p>Kingmans coalescent implementeres i phasic som en kontinuert absorption Markov-kæde <span class="citation" data-cites="Roikjer2022 phasic">(<a href="#ref-Roikjer2022" role="doc-biblioref">Røikjer et al. 2022</a>; <a href="#ref-phasic" role="doc-biblioref">Munch 2026</a>)</span> hvor tilstandsvektoren <span class="math inline">\(\mathbf{s} = (s_1, s_2, \ldots, s_n)\)</span> angiver antallet af linjer med henholdsvis <span class="math inline">\(1, 2, \ldots, n\)</span> efterkommere. Starttilstanden er <span class="math inline">\(\mathbf{s}^{(0)} = (n, 0, \ldots, 0)\)</span> og coalescence af to linjer med <span class="math inline">\(i\)</span> og <span class="math inline">\(j\)</span> efterkommere giver en ny linje med rate <span class="math inline">\(\lambda_{ij} = s_i(s_j - \delta_{ij})/(1 + \delta_{ij})\)</span>. Den grafbaserede implementering konstruerer automatisk tilstandsrummet via en callback-funktion uden manuel specificering af overgangsmatricen. Korrekthed verificeres ved at sammenligne numeriske resultater med analytiske formler: for <span class="math inline">\(n = 4\)</span> giver phasic <span class="math inline">\(\mathbb{E}[H] = 1{,}5000\)</span> og <span class="math inline">\(\text{Var}[H] = 1{,}1389\)</span> med relativ afvigelse under <span class="math inline">\(10^{-6}\)</span> for alle <span class="math inline">\(n = 2, \ldots, 8\)</span> og sojourn-tiderne for <span class="math inline">\(k = 4, 3, 2\)</span> linjer er <span class="math inline">\(0{,}167\)</span>, <span class="math inline">\(0{,}333\)</span> og <span class="math inline">\(1{,}000\)</span> coalescent-enheder som forventet.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/01_coalescent_basics.ipynb" data-notebook-title="Notebook 1: coalescent som fase-type fordeling" data-notebook-cellid="cell-tbl-verificering">
<div class="cell" data-execution_count="6">
<div id="tbl-verificering" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-verificering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Verificering af E[H] mod analytisk formel for n=2 til 8. Afvigelse er nul for alle n hvilket bekræfter at phasic er korrekt implementeret.
</figcaption>
<div aria-describedby="tbl-verificering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">E[H] numerisk</th>
<th data-quarto-table-cell-role="th">E[H] analytisk</th>
<th data-quarto-table-cell-role="th">Forskel</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1.00000</td>
<td>1.00000</td>
<td>0.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1.33333</td>
<td>1.33333</td>
<td>0.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1.50000</td>
<td>1.50000</td>
<td>0.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1.60000</td>
<td>1.60000</td>
<td>0.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>1.66667</td>
<td>1.66667</td>
<td>0.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1.71429</td>
<td>1.71429</td>
<td>0.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>1.75000</td>
<td>1.75000</td>
<td>0.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/01_coalescent_basics.ipynb" data-notebook-title="Notebook 1: coalescent som fase-type fordeling" data-notebook-cellid="cell-tbl-sojourn">
<div class="cell" data-execution_count="7">
<div id="tbl-sojourn" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sojourn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Forventede sojourn-tider per fase for n=4. Med k linjer er sojourn-tiden 2/[k(k-1)]. Fasen med k=2 udgør 67% af den forventede TMRCA.
</figcaption>
<div aria-describedby="tbl-sojourn-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">k linjer</th>
<th data-quarto-table-cell-role="th">Tilstande i fasen</th>
<th data-quarto-table-cell-role="th">Sojourn analytisk 2/[k(k-1)]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>4</td>
<td>(4, 0, 0, 0)</td>
<td>0.16667</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>3</td>
<td>(2, 1, 0, 0)</td>
<td>0.33333</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>2</td>
<td>(0, 2, 0, 0), (1, 0, 1, 0)</td>
<td>1.00000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<p>SFS-komponenterne for <span class="math inline">\(n = 4\)</span> er <span class="math inline">\((\mathbb{E}[B_1], \mathbb{E}[B_2], \mathbb{E}[B_3]) = (2{,}000, 1{,}000, 0{,}667)\)</span> og den samlede grenlængde <span class="math inline">\(\mathbb{E}[L] = 3{,}667\)</span> stemmer præcist med Wattersons formel. Kovariansstrukturen viser at singletons og doubletons er negativt korrelerede (<span class="math inline">\(\text{Cov}(B_1, B_2) = -0{,}222\)</span>) og singletons og tripletons positivt korrelerede (<span class="math inline">\(\text{Cov}(B_1, B_3) = +0{,}889\)</span>).</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/01_coalescent_basics.ipynb" data-notebook-title="Notebook 1: coalescent som fase-type fordeling" data-notebook-cellid="cell-tbl-kovarians">
<div class="cell" data-execution_count="13">
<div id="tbl-kovarians" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="13">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-kovarians-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Kovariansmatrix for SFS-grenlængder (n=4). Singletons og doubletons er negativt korrelerede (Cov=-0,222). Naiv uafhængighedsantagelse undervurderer usikkerheden på demografiske estimater.
</figcaption>
<div aria-describedby="tbl-kovarians-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">1'ton</th>
<th data-quarto-table-cell-role="th">2'ton</th>
<th data-quarto-table-cell-role="th">3'ton</th>
<th data-quarto-table-cell-role="th">4'ton</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1'ton</th>
<td>1.7778</td>
<td>-0.2222</td>
<td>0.8889</td>
<td>0.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2'ton</th>
<td>-0.2222</td>
<td>2.3333</td>
<td>-0.4444</td>
<td>0.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">3'ton</th>
<td>0.8889</td>
<td>-0.4444</td>
<td>0.8889</td>
<td>0.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4'ton</th>
<td>0.0000</td>
<td>0.0000</td>
<td>0.0000</td>
<td>0.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<p>Dobbelt-præcision sammenlignes med MPFR 128-bit præcision for <span class="math inline">\(n = 2\)</span>–<span class="math inline">\(17\)</span>. Den relative fejl i <span class="math inline">\(\mathbb{E}[H]\)</span> er aldrig over <span class="math inline">\(4 \times 10^{-16}\)</span>, og alle bavian-relevante parametre (<span class="math inline">\(\theta \in [0{,}3, 5{,}0]\)</span>) giver fejl under <span class="math inline">\(10^{-14}\)</span> i det tredje moment. MPFR er 17–86x langsommere og anvendes ikke i bavian-analyserne da dobbelt-præcision er tilstrækkelig. RAM er under 7 KB selv ved <span class="math inline">\(n = 15\)</span>, og <span class="math inline">\(\mathbb{E}[H]\)</span>-beregning tager under 0,3 ms for alle prøvestørrelse, hvilket bekræfter at modellen er beregningsmæssigt effektiv selv for de større tilstandsrum der kræves til to-ø og IM-modellen.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/04_numerical_precision_and_scaling.ipynb" data-notebook-title="Notebook 4: Numerisk præcision, parallel skalering og beregningsgrænser" data-notebook-cellid="cell-tbl-præcision">
<div class="cell" data-execution_count="3">
<div id="tbl-præcision" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-præcision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Numerisk præcision for Kingmans coalescent: dobbelt-præcision vs.&nbsp;MPFR for n=2 til 17. Den relative fejl i E[H] er aldrig over 4e-16 hvilket er tæt på maskin-epsilon. Dobbelt-præcision er tilstrækkelig for alle prøvestørrelser relevante for bavian-analysen.
</figcaption>
<div aria-describedby="tbl-præcision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">hjørner</th>
<th data-quarto-table-cell-role="th">E[H] dobbelt</th>
<th data-quarto-table-cell-role="th">E[H] MPFR</th>
<th data-quarto-table-cell-role="th">E[H] analytisk</th>
<th data-quarto-table-cell-role="th">Abs fejl E[H]</th>
<th data-quarto-table-cell-role="th">Rel fejl E[H]</th>
<th data-quarto-table-cell-role="th">Abs fejl 2. mom.</th>
<th data-quarto-table-cell-role="th">Abs fejl 5. mom.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>2</td>
<td>3</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>0.00e+00</td>
<td>0.00e+00</td>
<td>0.00e+00</td>
<td>N/A</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>3</td>
<td>4</td>
<td>1.333333</td>
<td>1.333333</td>
<td>1.333333</td>
<td>0.00e+00</td>
<td>0.00e+00</td>
<td>4.44e-16</td>
<td>N/A</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>4</td>
<td>6</td>
<td>1.500000</td>
<td>1.500000</td>
<td>1.500000</td>
<td>4.44e-16</td>
<td>2.96e-16</td>
<td>8.88e-16</td>
<td>N/A</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>5</td>
<td>8</td>
<td>1.600000</td>
<td>1.600000</td>
<td>1.600000</td>
<td>2.22e-16</td>
<td>1.39e-16</td>
<td>4.44e-16</td>
<td>2.84e-14</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>6</td>
<td>12</td>
<td>1.666667</td>
<td>1.666667</td>
<td>1.666667</td>
<td>2.22e-16</td>
<td>1.33e-16</td>
<td>8.88e-16</td>
<td>5.68e-14</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>7</td>
<td>16</td>
<td>1.714286</td>
<td>1.714286</td>
<td>1.714286</td>
<td>0.00e+00</td>
<td>0.00e+00</td>
<td>8.88e-16</td>
<td>0.00e+00</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>8</td>
<td>23</td>
<td>1.750000</td>
<td>1.750000</td>
<td>1.750000</td>
<td>6.66e-16</td>
<td>3.81e-16</td>
<td>8.88e-16</td>
<td>5.68e-14</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>9</td>
<td>31</td>
<td>1.777778</td>
<td>1.777778</td>
<td>1.777778</td>
<td>8.88e-16</td>
<td>5.00e-16</td>
<td>8.88e-16</td>
<td>0.00e+00</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>10</td>
<td>43</td>
<td>1.800000</td>
<td>1.800000</td>
<td>1.800000</td>
<td>4.44e-16</td>
<td>2.47e-16</td>
<td>8.88e-16</td>
<td>0.00e+00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>11</td>
<td>57</td>
<td>1.818182</td>
<td>1.818182</td>
<td>1.818182</td>
<td>6.66e-16</td>
<td>3.66e-16</td>
<td>8.88e-16</td>
<td>5.68e-14</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>12</td>
<td>78</td>
<td>1.833333</td>
<td>1.833333</td>
<td>1.833333</td>
<td>4.44e-16</td>
<td>2.42e-16</td>
<td>1.78e-15</td>
<td>0.00e+00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>13</td>
<td>102</td>
<td>1.846154</td>
<td>1.846154</td>
<td>1.846154</td>
<td>2.22e-16</td>
<td>1.20e-16</td>
<td>8.88e-16</td>
<td>5.68e-14</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>14</td>
<td>136</td>
<td>1.857143</td>
<td>1.857143</td>
<td>1.857143</td>
<td>8.88e-16</td>
<td>4.78e-16</td>
<td>8.88e-16</td>
<td>5.68e-14</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>15</td>
<td>177</td>
<td>1.866667</td>
<td>1.866667</td>
<td>1.866667</td>
<td>4.44e-16</td>
<td>2.38e-16</td>
<td>2.66e-15</td>
<td>5.68e-14</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>16</td>
<td>232</td>
<td>1.875000</td>
<td>1.875000</td>
<td>1.875000</td>
<td>6.66e-16</td>
<td>3.55e-16</td>
<td>2.66e-15</td>
<td>2.27e-13</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>17</td>
<td>298</td>
<td>1.882353</td>
<td>1.882353</td>
<td>1.882353</td>
<td>2.22e-16</td>
<td>1.18e-16</td>
<td>1.78e-15</td>
<td>1.14e-13</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/04_numerical_precision_and_scaling.ipynb" data-notebook-title="Notebook 4: Numerisk præcision, parallel skalering og beregningsgrænser" data-notebook-cellid="cell-fig-skalering-states">
<div id="cell-fig-skalering-states" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-skalering-states" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-skalering-states-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-04_numerical_precision_and_scaling-fig-skalering-states-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Figure&nbsp;13: Beregningsmæssig skalering med prøvestørrelse n.&nbsp;Øverst venstre: tilstandsrumsudvækst fra 3 tilstande (n=2) til 177 tilstande (n=15). Øverst højre: grafkonstruktion vokser fra 0.0004 til 0.015 sekunder. Nederst venstre: E[H] og moment-beregning er under 1 ms, PDF dominerer ved høj n.&nbsp;Nederst højre: RAM er lineær og under 7 KB."><img src="index_files/figure-html/..-notebooks-04_numerical_precision_and_scaling-fig-skalering-states-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-skalering-states-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Beregningsmæssig skalering med prøvestørrelse n.&nbsp;Øverst venstre: tilstandsrumsudvækst fra 3 tilstande (n=2) til 177 tilstande (n=15). Øverst højre: grafkonstruktion vokser fra 0.0004 til 0.015 sekunder. Nederst venstre: E[H] og moment-beregning er under 1 ms, PDF dominerer ved høj n.&nbsp;Nederst højre: RAM er lineær og under 7 KB.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Fra den systematiske sammenligning af <span class="math inline">\(n \in \{2, 4, 6, 8, 10\}\)</span> er <span class="math inline">\(n = 4\)</span> valgt som standard til enkelt-populations inferens og <span class="math inline">\(n = 6\)</span> til to-ø og IM-modellen. <a href="#tbl-n-sammenligning" class="quarto-xref">Table&nbsp;6</a> viser at <span class="math inline">\(\mathbb{E}[H]\)</span> konvergerer mod 2 og singleton-andelen stabiliserer sig ved <span class="math inline">\(n \geq 6\)</span>, mens yderligere stigning i <span class="math inline">\(n\)</span> øger tilstandsrummet eksponentielt uden meningsfuld informationsgevinst.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/01_coalescent_basics.ipynb" data-notebook-title="Notebook 1: coalescent som fase-type fordeling" data-notebook-cellid="cell-tbl-n-sammenligning">
<div class="cell" data-execution_count="16">
<div id="tbl-n-sammenligning" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="16">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-n-sammenligning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: E[H], E[L] og singleton-andel som funktion af prøvestørrelse n=2 til 10. E[H] konvergerer mod 2 og singleton-andelen falder monotont. Begrunder valget af n=4 til n=6 som standardstikprøvestørrelse.
</figcaption>
<div aria-describedby="tbl-n-sammenligning-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">E[H]</th>
<th data-quarto-table-cell-role="th">E[L]</th>
<th data-quarto-table-cell-role="th">E[L]/E[H]</th>
<th data-quarto-table-cell-role="th">singleton/samlede</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>2</td>
<td>1.0000</td>
<td>2.0000</td>
<td>2.0000</td>
<td>1.0000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>3</td>
<td>1.3333</td>
<td>3.0000</td>
<td>2.2500</td>
<td>0.6667</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>4</td>
<td>1.5000</td>
<td>3.6667</td>
<td>2.4444</td>
<td>0.5455</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>5</td>
<td>1.6000</td>
<td>4.1667</td>
<td>2.6042</td>
<td>0.4800</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>6</td>
<td>1.6667</td>
<td>4.5667</td>
<td>2.7400</td>
<td>0.4380</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>7</td>
<td>1.7143</td>
<td>4.9000</td>
<td>2.8583</td>
<td>0.4082</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>8</td>
<td>1.7500</td>
<td>5.1857</td>
<td>2.9633</td>
<td>0.3857</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>9</td>
<td>1.7778</td>
<td>5.4357</td>
<td>3.0576</td>
<td>0.3679</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>10</td>
<td>1.8000</td>
<td>5.6579</td>
<td>3.1433</td>
<td>0.3535</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="svgd-prior-optimizer-og-standardkonfiguration" class="level2">
<h2 class="anchored" data-anchor-id="svgd-prior-optimizer-og-standardkonfiguration">SVGD: prior, optimizer og standardkonfiguration</h2>
<p>SVGD repræsenterer posterioren <span class="math inline">\(p(\theta \mid \mathbf{data})\)</span> med <span class="math inline">\(M\)</span> partikler der opdateres iterativt via en kernelbaseret regel der kombinerer gradient-information fra log-posterior med en frastødende kraft der forhindrer partikelkollaps. Log-posterioren er <span class="math inline">\(\log p(\theta \mid \mathbf{t}) = \sum_i \log f(t_i;\theta) + \log \pi(\theta)\)</span>, hvor <span class="math inline">\(f(t;\theta) = \alpha\exp(\mathbf{S}(\theta)t)(-\mathbf{S})\mathbf{e}\)</span> er den analytisk beregnede fase-type PDF — eksakt, ikke approksimativ. Alle SVGD-analyser er implementeret via <em>phasic</em>’s <em>graph.svgd()</em> interface.</p>
<p>Fire prior-strategier er sammenlignet systematisk over bavian-relevante theta-værdier (<span class="math inline">\(\theta \in \{3, 7, 15, 20\}\)</span>, svarende til <span class="math inline">\(N_e \approx 5.000\)</span>–<span class="math inline">\(200.000\)</span>): en bred GaussPrior, en smal GaussPrior, en HalfCauchyPrior og en DataPrior der automatisk konstrueres fra data via method of moments. DataPrior giver konsistent lavest bias over hele theta-intervallet og vælges som standardprior til enkelt-populations inferens. HalfCauchyPrior er velegnet til migrationsraten <span class="math inline">\(\theta_1\)</span> fordi den er positiv-støttet og har en tung hale der undgår systematisk bias mod nul ved lav migration. DataPrior kan ikke bruges til to-parameter modeller da den forårsager <code>Theta length mismatch</code>-fejl i JAX, og til alle to-populations modeller bruges i stedet GaussPrior til <span class="math inline">\(\theta_0\)</span> og HalfCauchyPrior til <span class="math inline">\(\theta_1\)</span>. Forkert centrerede priors dominerer stærkt ved <span class="math inline">\(n_\text{obs} &lt; 500\)</span>: ved <span class="math inline">\(n = 50\)</span> med en prior centreret ved <span class="math inline">\(\mu = 1\)</span> estimeres <span class="math inline">\(\hat{\theta} \approx 3{,}9\)</span> frem for sand <span class="math inline">\(\theta = 7{,}0\)</span>, og biasset aftager gradvist og er stadig tydeligt ved <span class="math inline">\(n = 1000\)</span>.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/02_svgd_inferens_basis.ipynb" data-notebook-title="Notebook 2: Bayesiansk inferens med SVGD – grundlæggende egenskaber og prior-sensitivitet" data-notebook-cellid="cell-tbl-prior-bav">
<div class="cell" data-execution_count="5">
<div id="tbl-prior-bav" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-prior-bav-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Prior-sensitivitet over bavian-realistiske theta-værdier. DataPrior giver lavest bias ved theta=3, 15 og 20. GaussPrior(bred) kollapser ved theta=15 med bias på 153% og theta=20 med 221%. DataPrior anbefales som standardprior til bavian-analysen.
</figcaption>
<div aria-describedby="tbl-prior-bav-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Sand theta</th>
<th data-quarto-table-cell-role="th">Prior</th>
<th data-quarto-table-cell-role="th">Mean</th>
<th data-quarto-table-cell-role="th">Std</th>
<th data-quarto-table-cell-role="th">Bias</th>
<th data-quarto-table-cell-role="th">RelBias procent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>3.0</td>
<td>GaussPrior (bred)</td>
<td>3.0555</td>
<td>0.02928</td>
<td>0.0555</td>
<td>1.85</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>3.0</td>
<td>GaussPrior (smal)</td>
<td>3.0441</td>
<td>0.04461</td>
<td>0.0441</td>
<td>1.47</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3.0</td>
<td>HalfCauchy</td>
<td>3.0649</td>
<td>0.06006</td>
<td>0.0649</td>
<td>2.16</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>3.0</td>
<td>DataPrior (MoM)</td>
<td>3.0616</td>
<td>0.03327</td>
<td>0.0616</td>
<td>2.05</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>7.0</td>
<td>GaussPrior (bred)</td>
<td>9.6323</td>
<td>5.10569</td>
<td>2.6323</td>
<td>37.60</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>7.0</td>
<td>GaussPrior (smal)</td>
<td>6.8260</td>
<td>0.11550</td>
<td>0.1740</td>
<td>2.49</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7.0</td>
<td>HalfCauchy</td>
<td>6.8288</td>
<td>0.13262</td>
<td>0.1712</td>
<td>2.45</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>7.0</td>
<td>DataPrior (MoM)</td>
<td>6.8509</td>
<td>0.05427</td>
<td>0.1491</td>
<td>2.13</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>15.0</td>
<td>GaussPrior (bred)</td>
<td>22.7491</td>
<td>12.44818</td>
<td>7.7491</td>
<td>51.66</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>15.0</td>
<td>GaussPrior (smal)</td>
<td>15.5789</td>
<td>0.78515</td>
<td>0.5789</td>
<td>3.86</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>15.0</td>
<td>HalfCauchy</td>
<td>14.8874</td>
<td>0.59198</td>
<td>0.1126</td>
<td>0.75</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>15.0</td>
<td>DataPrior (MoM)</td>
<td>15.2260</td>
<td>0.13272</td>
<td>0.2260</td>
<td>1.51</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>20.0</td>
<td>GaussPrior (bred)</td>
<td>53.7149</td>
<td>42.23176</td>
<td>33.7149</td>
<td>168.57</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>20.0</td>
<td>GaussPrior (smal)</td>
<td>20.2713</td>
<td>0.98882</td>
<td>0.2713</td>
<td>1.36</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>20.0</td>
<td>HalfCauchy</td>
<td>41.7436</td>
<td>98.97019</td>
<td>21.7436</td>
<td>108.72</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>20.0</td>
<td>DataPrior (MoM)</td>
<td>19.9695</td>
<td>0.23425</td>
<td>0.0305</td>
<td>0.15</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/02_svgd_inferens_basis.ipynb" data-notebook-title="Notebook 2: Bayesiansk inferens med SVGD – grundlæggende egenskaber og prior-sensitivitet" data-notebook-cellid="cell-fig-priors">
<div id="cell-fig-priors" class="cell">
<div class="cell-output cell-output-display">
<div id="fig-priors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-priors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-priors-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="Figure&nbsp;14: De fire prior-fordelinger brugt i analysen. Vag Gaussisk (bred og flad), informativ korrekt centreret ved theta=7, informativ forkert centreret ved theta=1, og HalfCauchy (positiv-støttet med tung hale). Den røde linje markerer sand theta=7."><img src="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-priors-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-priors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: De fire prior-fordelinger brugt i analysen. Vag Gaussisk (bred og flad), informativ korrekt centreret ved theta=7, informativ forkert centreret ved theta=1, og HalfCauchy (positiv-støttet med tung hale). Den røde linje markerer sand theta=7.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Adam(0.1) giver lavest gennemsnitlig posterior-std over alle bavian-relevante theta-værdier og vælges som standardoptimizer. En veldefineret posterior er bred og unimodal. En peaked posterior med kurtosis <span class="math inline">\(\kappa &gt; 2\)</span> indikerer at SVGD er kollapset og undervurderer usikkerheden, og dette diagnostik anvendes konsekvent i alle analyser.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/02_svgd_inferens_basis.ipynb" data-notebook-title="Notebook 2: Bayesiansk inferens med SVGD – grundlæggende egenskaber og prior-sensitivitet" data-notebook-cellid="cell-fig-posterior-form">
<div id="cell-fig-posterior-form" class="cell">
<div class="cell-output cell-output-display">
<div id="fig-posterior-form" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-posterior-form-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-posterior-form-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="Figure&nbsp;15: Posterior-form under varierende læringsrater. Adam(0.25) giver en flad, unimodal posterior (kurtosis lav). Adam(2.0) giver en peaked posterior med høj kurtosis — SVGD er kollapset og undervurderer usikkerheden. Adam(0.001) konvergerer ikke. Kurtosis > 2 bruges som grænse for peaked posterior."><img src="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-posterior-form-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-posterior-form-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Posterior-form under varierende læringsrater. Adam(0.25) giver en flad, unimodal posterior (kurtosis lav). Adam(2.0) giver en peaked posterior med høj kurtosis — SVGD er kollapset og undervurderer usikkerheden. Adam(0.001) konvergerer ikke. Kurtosis &gt; 2 bruges som grænse for peaked posterior.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>En grid-søgning over <span class="math inline">\((n_\text{part}, n_\text{iter}) \in \{20, 40, 60, 80\} \times \{200, 300, 400, 500\}\)</span> med Adam(0.1) identificerer den optimale konfiguration. Alle valg er opsummeret i <a href="#tbl-config" class="quarto-xref">Table&nbsp;9</a>.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/02_svgd_inferens_basis.ipynb" data-notebook-title="Notebook 2: Bayesiansk inferens med SVGD – grundlæggende egenskaber og prior-sensitivitet" data-notebook-cellid="cell-tbl-grid-svgd">
<div class="cell" data-execution_count="7">
<div id="tbl-grid-svgd" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-grid-svgd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Grid-søgning over antal partikler og iterationer med Adam(0.1) og theta=7. Bedste kombination er 20 partikler og 300 iterationer med std=0.023 og beregningstid 34 sekunder.
</figcaption>
<div aria-describedby="tbl-grid-svgd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Particles</th>
<th data-quarto-table-cell-role="th">Iterations</th>
<th data-quarto-table-cell-role="th">Std</th>
<th data-quarto-table-cell-role="th">Bias</th>
<th data-quarto-table-cell-role="th">Tid_s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>20</td>
<td>100</td>
<td>0.11687</td>
<td>0.1610</td>
<td>5.17</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>20</td>
<td>200</td>
<td>0.08645</td>
<td>0.1570</td>
<td>7.95</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>20</td>
<td>300</td>
<td>0.09979</td>
<td>0.1409</td>
<td>11.37</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>20</td>
<td>500</td>
<td>0.05089</td>
<td>0.1287</td>
<td>19.28</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>40</td>
<td>100</td>
<td>0.09778</td>
<td>0.1194</td>
<td>9.65</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>40</td>
<td>200</td>
<td>0.06380</td>
<td>0.1644</td>
<td>17.13</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>40</td>
<td>300</td>
<td>0.07331</td>
<td>0.1211</td>
<td>20.70</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>40</td>
<td>500</td>
<td>0.08713</td>
<td>0.1270</td>
<td>36.23</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>60</td>
<td>100</td>
<td>0.07910</td>
<td>0.1476</td>
<td>13.19</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>60</td>
<td>200</td>
<td>0.10846</td>
<td>0.1458</td>
<td>20.93</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>60</td>
<td>300</td>
<td>0.09097</td>
<td>0.1389</td>
<td>30.25</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>60</td>
<td>500</td>
<td>0.08855</td>
<td>0.1272</td>
<td>51.82</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>80</td>
<td>100</td>
<td>0.11862</td>
<td>0.1389</td>
<td>17.74</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>80</td>
<td>200</td>
<td>0.08809</td>
<td>0.1225</td>
<td>27.98</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>80</td>
<td>300</td>
<td>0.12994</td>
<td>0.1448</td>
<td>42.18</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>80</td>
<td>500</td>
<td>0.11493</td>
<td>0.1457</td>
<td>72.05</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>120</td>
<td>100</td>
<td>0.11577</td>
<td>0.1449</td>
<td>24.93</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>120</td>
<td>200</td>
<td>0.12732</td>
<td>0.1356</td>
<td>40.60</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">18</th>
<td>120</td>
<td>300</td>
<td>0.15177</td>
<td>0.1235</td>
<td>61.45</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>120</td>
<td>500</td>
<td>0.14469</td>
<td>0.1192</td>
<td>106.38</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<div id="tbl-config" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-config-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Standardkonfiguration for SVGD-inferens i bavian-analyserne.
</figcaption>
<div aria-describedby="tbl-config-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Valg</th>
<th>Begrundelse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(n\)</span> (enkelt-pop.)</td>
<td>4</td>
<td>Tilstrækkeligt til SFS-inferens, 35 tilstande</td>
</tr>
<tr class="even">
<td><span class="math inline">\(n\)</span> (to-ø/IM)</td>
<td>6</td>
<td>Identificerbarhed kræver <span class="math inline">\(n \geq 4\)</span>, 140 tilstande</td>
</tr>
<tr class="odd">
<td>Optimizer</td>
<td>Adam(0.1)</td>
<td>Lavest bias over bavian-<span class="math inline">\(\theta\)</span></td>
</tr>
<tr class="even">
<td>Iterationer (enkelt)</td>
<td>300</td>
<td>Konvergeret inden 200 for de fleste modeller</td>
</tr>
<tr class="odd">
<td>Iterationer (to-param.)</td>
<td>400</td>
<td>To-ø modellen konvergerer langsommere</td>
</tr>
<tr class="even">
<td>Partikler</td>
<td>20–60</td>
<td>Optimal balance std/tid</td>
</tr>
<tr class="odd">
<td>Prior (enkelt-pop.)</td>
<td>DataPrior</td>
<td>Lavest bias over <span class="math inline">\(\theta \in \{3,7,15,20\}\)</span></td>
</tr>
<tr class="even">
<td>Prior (<span class="math inline">\(\theta_0\)</span>, to-pop.)</td>
<td>GaussPrior</td>
<td>DataPrior virker ikke til to-parameter</td>
</tr>
<tr class="odd">
<td>Prior (<span class="math inline">\(\theta_1\)</span>, migration)</td>
<td>HalfCauchyPrior</td>
<td>Positiv-støttet, tung hale</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mu\)</span> (bavian)</td>
<td><span class="math inline">\(0{,}9 \times 10^{-8}\)</span></td>
<td><span class="citation" data-cites="sorensen2023"><span class="nocase">Erik F. Sørensen et al.</span> (<a href="#ref-sorensen2023" role="doc-biblioref">2023</a>)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(g\)</span> (generationstid)</td>
<td>11 år</td>
<td><span class="citation" data-cites="sorensen2023"><span class="nocase">Erik F. Sørensen et al.</span> (<a href="#ref-sorensen2023" role="doc-biblioref">2023</a>)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="to-ø-modellen-im-modellen-og-msprime-validering" class="level2">
<h2 class="anchored" data-anchor-id="to-ø-modellen-im-modellen-og-msprime-validering">To-ø modellen, IM-modellen og msprime-validering</h2>
<p>To-ø modellen udvider standard coalescent’en til to populationer med symmetrisk migration og state space’t konstrueres via <code>StateIndexer</code> og <code>Property</code>-klasser der tracker populationstilhørsforhold for hver linje. For lav migration (<span class="math inline">\(\theta_1 &lt; 0{,}5\)</span>) er <span class="math inline">\(\theta_0\)</span> og <span class="math inline">\(\theta_1\)</span> confounded og posterioren er bred og negativt korreleret. Minimum <span class="math inline">\(N_\text{obs} = 5000\)</span> kombineret med HalfCauchyPrior sikrer <span class="math inline">\(\text{std}(\hat{\theta}_1) &lt; 0{,}3\)</span> ved moderat migration. Method of Moments er kun tilstrækkelig i 3 af 5 bavian-scenarier ved <span class="math inline">\(N_\text{obs} = 3000\)</span> og afviger systematisk ved lav migration — SVGD tilføjer primær værdi via korrekt usikkerhedskvantificering og robusthed ved poor identifiability.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/03_svgd_two_island.ipynb" data-notebook-title="Notebook 3: Identifiability og inferens i to-ø modellen" data-notebook-cellid="cell-tbl-prior-migration">
<div class="cell" data-execution_count="10">
<div id="tbl-prior-migration" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-prior-migration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Sammenligning af GaussPrior og HalfCauchyPrior til to-ø modellen (sand theta=[0.7, 0.9]). HalfCauchy giver lavere std for migrationsraten (0.261 vs.&nbsp;0.302) og er positiv-støttet hvilket undgår bias mod negative rater. HalfCauchyPrior anbefales til migrationsraten i alle to-populations modeller.
</figcaption>
<div aria-describedby="tbl-prior-migration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Prior</th>
<th data-quarto-table-cell-role="th">theta0 mean</th>
<th data-quarto-table-cell-role="th">theta0 std</th>
<th data-quarto-table-cell-role="th">theta1 mean</th>
<th data-quarto-table-cell-role="th">theta1 std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>GaussPrior (bred)</td>
<td>0.6907</td>
<td>0.07896</td>
<td>0.8142</td>
<td>0.19602</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>HalfCauchy</td>
<td>0.8254</td>
<td>1.37412</td>
<td>0.5613</td>
<td>0.35399</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/03_svgd_two_island.ipynb" data-notebook-title="Notebook 3: Identifiability og inferens i to-ø modellen" data-notebook-cellid="cell-tbl-identifiability">
<div class="cell" data-execution_count="5">
<div id="tbl-identifiability" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-identifiability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: SVGD-estimater for tre migrationsscenarier med n=5000 observationer. Ved høj migration er theta1 std=6.29 (sand=5.0) et klart identifikationsproblem. Coalescentraten theta0 er konsekvent godt estimeret på tværs af scenarier.
</figcaption>
<div aria-describedby="tbl-identifiability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Scenarie</th>
<th data-quarto-table-cell-role="th">Sand theta0</th>
<th data-quarto-table-cell-role="th">Sand theta1</th>
<th data-quarto-table-cell-role="th">Est. theta0</th>
<th data-quarto-table-cell-role="th">Est. theta1</th>
<th data-quarto-table-cell-role="th">Std theta0</th>
<th data-quarto-table-cell-role="th">Std theta1</th>
<th data-quarto-table-cell-role="th">Bias theta0</th>
<th data-quarto-table-cell-role="th">Bias theta1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Lav migration</td>
<td>0.7</td>
<td>0.2</td>
<td>0.702</td>
<td>0.197</td>
<td>0.0555</td>
<td>0.0322</td>
<td>0.002</td>
<td>0.003</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Moderat migration</td>
<td>0.7</td>
<td>1.0</td>
<td>0.678</td>
<td>1.017</td>
<td>0.0556</td>
<td>0.1957</td>
<td>0.022</td>
<td>0.017</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Høj migration</td>
<td>0.7</td>
<td>5.0</td>
<td>0.686</td>
<td>7.810</td>
<td>0.0174</td>
<td>9.2214</td>
<td>0.014</td>
<td>2.810</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/03_svgd_two_island.ipynb" data-notebook-title="Notebook 3: Identifiability og inferens i to-ø modellen" data-notebook-cellid="cell-tbl-mom-bavian">
<div class="cell" data-execution_count="7">
<div id="tbl-mom-bavian" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mom-bavian-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: MoM vs.&nbsp;SVGD over fem bavian-realistiske parameterscenarier med n=3000. MoM er tilstrækkelig i 3 af 5 scenarier. Ved [0.7, 1.0] og [0.5, 5.0] fejler MoM systematisk for migrationsraten. SVGD giver konsekvent bedre estimater og fuld posterior.
</figcaption>
<div aria-describedby="tbl-mom-bavian-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Sand [t0, t1]</th>
<th data-quarto-table-cell-role="th">MoM t0</th>
<th data-quarto-table-cell-role="th">MoM t1</th>
<th data-quarto-table-cell-role="th">SVGD t0 mean</th>
<th data-quarto-table-cell-role="th">SVGD t0 std</th>
<th data-quarto-table-cell-role="th">SVGD t1 mean</th>
<th data-quarto-table-cell-role="th">SVGD t1 std</th>
<th data-quarto-table-cell-role="th">MoM ok?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>[0.3, 0.5]</td>
<td>0.3058</td>
<td>0.7911</td>
<td>0.2797</td>
<td>0.05481</td>
<td>0.5242</td>
<td>0.24468</td>
<td>Nej</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>[0.7, 1.0]</td>
<td>0.6924</td>
<td>1.7336</td>
<td>0.6415</td>
<td>0.11624</td>
<td>0.9945</td>
<td>0.42635</td>
<td>Nej</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>[1.5, 2.0]</td>
<td>1.4891</td>
<td>2.7038</td>
<td>1.4190</td>
<td>0.21344</td>
<td>2.3464</td>
<td>0.83008</td>
<td>Nej</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>[0.5, 5.0]</td>
<td>0.5023</td>
<td>12.4480</td>
<td>0.3962</td>
<td>0.11707</td>
<td>20.6003</td>
<td>35.87558</td>
<td>Nej</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>[2.0, 0.1]</td>
<td>1.7831</td>
<td>0.0814</td>
<td>1.9375</td>
<td>0.03536</td>
<td>0.0912</td>
<td>0.00544</td>
<td>Ja</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<p>Den asymmetriske model med separate rater <span class="math inline">\(m_{12}\)</span> og <span class="math inline">\(m_{21}\)</span> kræver <span class="math inline">\(n \geq 4\)</span> for identifiability: med <span class="math inline">\(n=2\)</span> er kun summen <span class="math inline">\(m_{12} + m_{21}\)</span> identificerbar, mens <span class="math inline">\(n=4\)</span> reducerer bias til under 5% for begge rater. IM-modellen implementeres som en time-inhomogeneous to-ø model med epoch-skift ved <span class="math inline">\(t_s\)</span> via <code>add_epoch</code>, og split-tidspunktet sættes til den kendte bavian-værdi <span class="math inline">\(t_s \approx 1{,}3\)</span> Ma for <em>P. anubis</em>/<em>P. cynocephalus</em> fra <span class="citation" data-cites="rogers2019"><span class="nocase">Rogers et al.</span> (<a href="#ref-rogers2019" role="doc-biblioref">2019</a>)</span>. Begge modeller valideres med msprime-simulationer: SVGD estimerer <span class="math inline">\(\theta_0\)</span> og <span class="math inline">\(\theta_1\)</span> korrekt tilbage inden for posterior-usikkerheden, og SFS-observationer udtrækkes via <code>sim_mutations</code> med allele counts i coalescent-enheder for sammenlignelighed med phasic-modellerne.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/03_svgd_two_island.ipynb" data-notebook-title="Notebook 3: Identifiability og inferens i to-ø modellen" data-notebook-cellid="cell-tbl-msprime-validering-ø">
<div class="cell" data-execution_count="8">
<div id="tbl-msprime-validering-ø" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="8">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-msprime-validering-ø-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13: msprime-validering af to-ø modellen. SVGD estimerer begge parametre korrekt tilbage inden for posterior-usikkerheden for bavian-realistiske scenarier.
</figcaption>
<div aria-describedby="tbl-msprime-validering-ø-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Scenarie</th>
<th data-quarto-table-cell-role="th">theta0 sand</th>
<th data-quarto-table-cell-role="th">theta0 est</th>
<th data-quarto-table-cell-role="th">theta0 std</th>
<th data-quarto-table-cell-role="th">theta1 sand</th>
<th data-quarto-table-cell-role="th">theta1 est</th>
<th data-quarto-table-cell-role="th">theta1 std</th>
<th data-quarto-table-cell-role="th">Ne est</th>
<th data-quarto-table-cell-role="th">bias0 %</th>
<th data-quarto-table-cell-role="th">bias1 %</th>
<th data-quarto-table-cell-role="th">n_obs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Lav migration</td>
<td>0.00180</td>
<td>0.196584</td>
<td>0.009829</td>
<td>1.0</td>
<td>3.9851</td>
<td>10.3418</td>
<td>5460670</td>
<td>10821.3</td>
<td>298.5</td>
<td>3000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Moderat migration</td>
<td>0.00288</td>
<td>0.292518</td>
<td>0.030153</td>
<td>8.0</td>
<td>17.8405</td>
<td>27.0593</td>
<td>8125509</td>
<td>10056.9</td>
<td>123.0</td>
<td>3000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Høj migration</td>
<td>0.00180</td>
<td>0.202307</td>
<td>0.012795</td>
<td>10.0</td>
<td>17.5267</td>
<td>33.0443</td>
<td>5619637</td>
<td>11139.3</td>
<td>75.3</td>
<td>3000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/05_time_inhomogeneous.ipynb" data-notebook-title="Notebook 5: Tidsinhomogen coalescent og inferens" data-notebook-cellid="cell-tbl-msprime-validering-im">
<div class="cell" data-execution_count="13">
<div id="tbl-msprime-validering-im" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="13">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-msprime-validering-im-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14: msprime-validering af IM-modellen: estimerede vs.&nbsp;sande parametre. Split-tidspunktet er fast og estimeres ikke. SVGD estimerer theta0 og theta1 korrekt tilbage inden for posterior-usikkerheden når theta er korrekt parametriseret i coalescentenheder.
</figcaption>
<div aria-describedby="tbl-msprime-validering-im-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Parameter</th>
<th data-quarto-table-cell-role="th">Sand</th>
<th data-quarto-table-cell-role="th">Estimat</th>
<th data-quarto-table-cell-role="th">Std</th>
<th data-quarto-table-cell-role="th">Bias procent</th>
<th data-quarto-table-cell-role="th">Sand i 95 procent-CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>theta0 (coalescensrate)</td>
<td>0.0018</td>
<td>0.287354</td>
<td>0.005162</td>
<td>15864.1</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>theta1 (migrationsrate)</td>
<td>1.0000</td>
<td>2.026900</td>
<td>7.881500</td>
<td>102.7</td>
<td>True</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="time-inhomogeneous-coalescent-og-joint-probability" class="level2">
<h2 class="anchored" data-anchor-id="time-inhomogeneous-coalescent-og-joint-probability">Time-inhomogeneous coalescent og joint probability</h2>
<p>Den time-inhomogeneous coalescent implementeres via <code>add_epoch</code> som beskrevet ovenfor. SFS under time-inhomogeneous modeller adskiller sig karakteristisk fra den homogene model, og <a href="#fig-sfs-bottleneck" class="quarto-xref">Figure&nbsp;16</a> viser at flaskehalstidspunktet er mere diagnostisk end dybden.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/05_time_inhomogeneous.ipynb" data-notebook-title="Notebook 5: Tidsinhomogen coalescent og inferens" data-notebook-cellid="cell-fig-sfs-bottleneck">
<div id="cell-fig-sfs-bottleneck" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-sfs-bottleneck" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sfs-bottleneck-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-sfs-bottleneck-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="Figure&nbsp;16: SFS-formen som funktion af flaskehals-tidspunkt ved fast dybde f=10. En tidlig flaskehals (t_start=0.3) øger den forventede grenlængde for alle frekvensklasser mest. En sen flaskehals (t_start=2.5) har næsten ingen effekt fordi de fleste linjer allerede er coalesceret. SFS er sensitiv over for flaskehalstidspunktet men ikke over for dybden når dybden er stor."><img src="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-sfs-bottleneck-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sfs-bottleneck-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: SFS-formen som funktion af flaskehals-tidspunkt ved fast dybde f=10. En tidlig flaskehals (t_start=0.3) øger den forventede grenlængde for alle frekvensklasser mest. En sen flaskehals (t_start=2.5) har næsten ingen effekt fordi de fleste linjer allerede er coalesceret. SFS er sensitiv over for flaskehalstidspunktet men ikke over for dybden når dybden er stor.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>For joint probability-inferens konstruerer <code>joint_prob_graph</code> en udvidet graf der tracker alle kombinationer op til <code>tot_reward_limit</code>. <a href="#fig-deficit" class="quarto-xref">Figure&nbsp;17</a> og <a href="#tbl-deficit-guide" class="quarto-xref">Table&nbsp;15</a> dokumenterer valget af standardkonfigurationen mu=1.0 og limit=3 med deficit 0,66%. Forkert <span class="math inline">\(\mu\)</span> giver systematisk bias der ikke forsvinder med større <span class="math inline">\(n\)</span>: faktor 2 fejl i <span class="math inline">\(\mu\)</span> giver faktor 2–3 fejl i <span class="math inline">\(\theta\)</span>-estimatet og motiverer en sensitivitetsanalyse over <span class="math inline">\(\mu\)</span> i bavian-analysen.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/06_joint_probability_inferens.ipynb" data-notebook-title="Notebook 6: Inferens via joint sandsynligheder og diskrete SFS-observationer" data-notebook-cellid="cell-fig-deficit">
<div id="cell-fig-deficit" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-deficit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-deficit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-deficit-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="Figure&nbsp;17: Deficit som funktion af tot_reward_limit og mutationsrate mu. Venstre: deficit på log-skala med rød stiplet linje ved 5%-grænsen. mu=0.5 og mu=1.0 er acceptabelt ved limit=3 (deficit under 1%). mu=2.0 kræver limit=7 og mu=5.0 er ubrugelig uanset limit. Højre: antal tabelposter vokser polynomielt med limit."><img src="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-deficit-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-deficit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: Deficit som funktion af tot_reward_limit og mutationsrate mu. Venstre: deficit på log-skala med rød stiplet linje ved 5%-grænsen. mu=0.5 og mu=1.0 er acceptabelt ved limit=3 (deficit under 1%). mu=2.0 kræver limit=7 og mu=5.0 er ubrugelig uanset limit. Højre: antal tabelposter vokser polynomielt med limit.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/06_joint_probability_inferens.ipynb" data-notebook-title="Notebook 6: Inferens via joint sandsynligheder og diskrete SFS-observationer" data-notebook-cellid="cell-tbl-deficit-guide">
<div class="cell" data-execution_count="6">
<div id="tbl-deficit-guide" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-deficit-guide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15: Anbefalede (mu, tot_reward_limit)-kombinationer med deficit under 5%. mu=1.0 med limit=3 giver deficit=0.66% og vælges som standardkonfiguration til bavian-analysen. mu=2.0 kræver limit=7 for acceptabel dækning.
</figcaption>
<div aria-describedby="tbl-deficit-guide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mu</th>
<th data-quarto-table-cell-role="th">limit</th>
<th data-quarto-table-cell-role="th">Deficit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0.5</td>
<td>2</td>
<td>0.0008</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0.5</td>
<td>3</td>
<td>0.0001</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0.5</td>
<td>4</td>
<td>0.0000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>0.5</td>
<td>5</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>0.5</td>
<td>7</td>
<td>0.0000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1.0</td>
<td>2</td>
<td>0.0277</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>1.0</td>
<td>3</td>
<td>0.0066</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>1.0</td>
<td>4</td>
<td>0.0015</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>1.0</td>
<td>5</td>
<td>0.0004</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>1.0</td>
<td>7</td>
<td>0.0000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>1.5</td>
<td>4</td>
<td>0.0251</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>1.5</td>
<td>5</td>
<td>0.0102</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>1.5</td>
<td>7</td>
<td>0.0016</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>2.0</td>
<td>7</td>
<td>0.0188</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="resultater" class="level1">
<h1>Resultater</h1>
<section id="coalescentens-analytiske-egenskaber-og-skalering" class="level2">
<h2 class="anchored" data-anchor-id="coalescentens-analytiske-egenskaber-og-skalering">Coalescent’ens analytiske egenskaber og skalering</h2>
<p>Fordobling af <span class="math inline">\(N_e\)</span> fordobler <span class="math inline">\(\mathbb{E}[H]\)</span> men firedobler <span class="math inline">\(\text{Var}[H]\)</span> — en kvadratisk skalering der har direkte biologiske konsekvenser: store populationer er ikke blot langsommere til at koalescere men har markant mere variabel koalescenstid. For bavian-realistiske <span class="math inline">\(N_e \in \{5.000, \ldots, 200.000\}\)</span> spænder TMRCA fra 36.000 til 2,9 millioner år, og <a href="#fig-skalering" class="quarto-xref">Figure&nbsp;18</a> illustrerer de lineære og kvadratiske skaleringer direkte. PMF for antal segregerende sites er højreskæv med <span class="math inline">\(P(S = 0) \approx 0{,}85\)</span> under bavian-parametre, og fordelingen nærmer sig Poisson ved høj <span class="math inline">\(N_e\)</span> og <span class="math inline">\(\mu\)</span> — dette er den empiriske begrundelse for at analysere genomdata locus for locus snarere end at aggregere over store regioner.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/01_coalescent_basics.ipynb" data-notebook-title="Notebook 1: coalescent som fase-type fordeling" data-notebook-cellid="cell-fig-skalering">
<div id="cell-fig-skalering" class="cell">
<div class="cell-output cell-output-display">
<div id="fig-skalering" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-skalering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-01_coalescent_basics-fig-skalering-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-19" title="Figure&nbsp;18: Skalering af E[H] og Var[H] med populationsstørrelse N. E[H] skalerer lineært og Var[H] kvadratisk. En fordobling af N firedobler variansen i coalescent tiden."><img src="index_files/figure-html/..-notebooks-01_coalescent_basics-fig-skalering-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-skalering-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: Skalering af E[H] og Var[H] med populationsstørrelse N. E[H] skalerer lineært og Var[H] kvadratisk. En fordobling af N firedobler variansen i coalescent tiden.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/01_coalescent_basics.ipynb" data-notebook-title="Notebook 1: coalescent som fase-type fordeling" data-notebook-cellid="cell-fig-pmf-mutationer">
<div id="cell-fig-pmf-mutationer" class="cell">
<div class="cell-output cell-output-display">
<div id="fig-pmf-mutationer" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pmf-mutationer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-01_coalescent_basics-fig-pmf-mutationer-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-20" title="Figure&nbsp;19: PMF for antal segregerende sites under varierende N og mu. Fordelingen er højreskæv med stor sandsynlighed for få mutationer per locus. Ved høj N og mu nærmer fordelingen sig Poisson."><img src="index_files/figure-html/..-notebooks-01_coalescent_basics-fig-pmf-mutationer-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pmf-mutationer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: PMF for antal segregerende sites under varierende N og mu. Fordelingen er højreskæv med stor sandsynlighed for få mutationer per locus. Ved høj N og mu nærmer fordelingen sig Poisson.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="svgd-validering" class="level2">
<h2 class="anchored" data-anchor-id="svgd-validering">SVGD-validering</h2>
<p>Prior-dominansanalysen viser at likelihood overtager fra prioren ved <span class="math inline">\(n_\text{obs} \approx 500\)</span>–<span class="math inline">\(1000\)</span> for en korrekt centreret prior. Med en forkert centreret prior er estimatet stadig biased ved <span class="math inline">\(n = 1000\)</span>, og kun ved <span class="math inline">\(n = 10.000\)</span> konvergerer de to priors til samme estimat. Med <span class="math inline">\(n_\text{obs} \approx 2000\)</span>–<span class="math inline">\(5000\)</span> SNP-observationer per bavian-population er prior-valget dermed ikke neutralt, og DataPrior er kritisk for at undgå systematisk bias.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/02_svgd_inferens_basis.ipynb" data-notebook-title="Notebook 2: Bayesiansk inferens med SVGD – grundlæggende egenskaber og prior-sensitivitet" data-notebook-cellid="cell-fig-prior-dominans">
<div id="cell-fig-prior-dominans" class="cell">
<div class="cell-output cell-output-display">
<div id="fig-prior-dominans" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-prior-dominans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-prior-dominans-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-21" title="Figure&nbsp;20: Prior-dominans som funktion af prøvestørrelse. Venstre: posterior-mean konvergerer mod sand theta=7 med stigende n.&nbsp;Korrekt prior er tæt på sandhed allerede ved n=100. Forkert prior er kraftigt biased ved n<500 og konvergerer gradvist. Højre: posterior-std falder for begge priors men korrekt prior giver konsistent smallere std."><img src="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-prior-dominans-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-prior-dominans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20: Prior-dominans som funktion af prøvestørrelse. Venstre: posterior-mean konvergerer mod sand theta=7 med stigende n.&nbsp;Korrekt prior er tæt på sandhed allerede ved n=100. Forkert prior er kraftigt biased ved n&lt;500 og konvergerer gradvist. Højre: posterior-std falder for begge priors men korrekt prior giver konsistent smallere std.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    n         prior     mean      std
   50 Korrekt prior 8.040697 0.665939
   50 Forkert prior 4.308981 0.165643
  100 Korrekt prior 7.227696 0.266892
  100 Forkert prior 4.815340 0.199500
  250 Korrekt prior 6.953654 0.105412
  250 Forkert prior 5.344183 1.228706
  500 Korrekt prior 6.610553 0.102156
  500 Forkert prior 5.890757 0.067705
 1000 Korrekt prior 7.292648 0.029937
 1000 Forkert prior 6.399838 1.473696
 3000 Korrekt prior 6.930915 0.146960
 3000 Forkert prior 6.756975 0.062585
10000 Korrekt prior 7.031132 0.009139
10000 Forkert prior 6.932490 0.124229</code></pre>
</div>
</div>
</div>
<p>Coverage-analysen viser at SVGD med korrekt centreret prior giver empirisk <span class="math inline">\(94\%\)</span> dækning ved <span class="math inline">\(n_\text{obs} = 100\)</span> — tæt på det nominelle <span class="math inline">\(95\%\)</span> niveau. Dækningen falder til <span class="math inline">\(80\%\)</span> ved <span class="math inline">\(n_\text{obs} = 2000\)</span>, ikke fordi SVGD er forkert, men fordi variationel inferens systematisk undervurderer posterior-bredde når data er mange og posterioren er smal (underdispersion). Posterior-std bør rapporteres direkte frem for at fortolkes som et klassisk <span class="math inline">\(95\%\)</span>-konfidensinterval. Posterior predictive check bekræfter at coalescent-modellen med det estimerede <span class="math inline">\(\hat{\theta}\)</span> reproducerer de observerede TMRCA-tider: empirisk CDF og model-CDF er visuelt uadskillelige, og model-PDF matcher histogrammet af observerede tider.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/02_svgd_inferens_basis.ipynb" data-notebook-title="Notebook 2: Bayesiansk inferens med SVGD – grundlæggende egenskaber og prior-sensitivitet" data-notebook-cellid="cell-fig-coverage">
<div id="cell-fig-coverage" class="cell">
<div class="cell-output cell-output-display">
<div id="fig-coverage" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-coverage-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-22" title="Figure&nbsp;21: Empirisk 95%-CI dækning som funktion af prøvestørrelse over 50 replikater. Korrekt prior giver 94% dækning ved n=100 men falder til 80% ved n=2000 som følge af variationel inferens’ tendens til underdispersion. Forkert prior giver kun 14% dækning ved n=100 og stiger gradvist efterhånden som likelihood overtager."><img src="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-coverage-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21: Empirisk 95%-CI dækning som funktion af prøvestørrelse over 50 replikater. Korrekt prior giver 94% dækning ved n=100 men falder til 80% ved n=2000 som følge af variationel inferens’ tendens til underdispersion. Forkert prior giver kun 14% dækning ved n=100 og stiger gradvist efterhånden som likelihood overtager.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/02_svgd_inferens_basis.ipynb" data-notebook-title="Notebook 2: Bayesiansk inferens med SVGD – grundlæggende egenskaber og prior-sensitivitet" data-notebook-cellid="cell-fig-ppc">
<div class="cell">
<div id="fig-ppc" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ppc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<div id="fig-ppc-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ppc-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-ppc-output-1.svg" class="lightbox" data-gallery="fig-ppc" title="Figure&nbsp;22&nbsp;(a): Posterior predictive check: modellen med estimeret theta reproducerer de observerede TMRCA-tider. Venstre: histogram af observerede tider (blå) og model-PDF ved posterior-mean (orange). Højre: empirisk CDF og model-CDF er visuelt uadskillelige hvilket bekræfter god modelfit."><img src="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-ppc-output-1.svg" class="img-fluid figure-img" data-ref-parent="fig-ppc"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ppc-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Posterior predictive check: modellen med estimeret theta reproducerer de observerede TMRCA-tider. Venstre: histogram af observerede tider (blå) og model-PDF ved posterior-mean (orange). Højre: empirisk CDF og model-CDF er visuelt uadskillelige hvilket bekræfter god modelfit.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div id="fig-ppc-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-ppc-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-ppc-output-2.svg" class="lightbox" data-gallery="fig-ppc" title="Figure&nbsp;22&nbsp;(b): "><img src="index_files/figure-html/..-notebooks-02_svgd_inferens_basis-fig-ppc-output-2.svg" id="fig-ppc-2" class="img-fluid figure-img" data-ref-parent="fig-ppc"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ppc-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b)
</figcaption>
</figure>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-ppc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;22
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="to-ø-modellen-identifiability-asymmetri-og-demografisk-signal" class="level2">
<h2 class="anchored" data-anchor-id="to-ø-modellen-identifiability-asymmetri-og-demografisk-signal">To-ø modellen: identifiability, asymmetri og demografisk signal</h2>
<p>Den parvise posterior for <span class="math inline">\((\theta_0, \theta_1)\)</span> afslører tre klart forskellige regimer. Ved lav migration (<span class="math inline">\(\theta_1 = 0{,}2\)</span>) er posterioren bred og negativt korreleret — parametrene er i praksis ikke adskillelige. Ved moderat migration (<span class="math inline">\(\theta_1 = 1{,}0\)</span>) er adskillelsen markant bedre, og ved høj migration (<span class="math inline">\(\theta_1 = 5{,}0\)</span>) er <span class="math inline">\(\theta_0\)</span> præcist estimeret mens <span class="math inline">\(\theta_1\)</span> stadig har bred posterior som følge af den stærke skalering af TMRCA med migrationsraten. Populationspar med lav migration vil give brede, negativt korrelerede posteriors i bavian-analysen, og konfidensintervallerne bør fortolkes med forsigtighed.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/03_svgd_two_island.ipynb" data-notebook-title="Notebook 3: Identifiability og inferens i to-ø modellen" data-notebook-cellid="cell-fig-pairwise-scenarier">
<div class="cell">
<div id="fig-pairwise-scenarier" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pairwise-scenarier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<div id="fig-pairwise-scenarier-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-pairwise-scenarier-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-pairwise-scenarier-output-1.svg" class="lightbox" data-gallery="fig-pairwise-scenarier" title="Figure&nbsp;23&nbsp;(a): Pairwise posterior for (theta0, theta1) under tre migrationsscenarier. Ved lav migration er posterioren bred og negativt korreleret — parametrene er konfunderede. Ved høj migration er theta0 præcist estimeret mens theta1 har stor usikkerhed. Den lyserrøde linje markerer sande parameterværdier."><img src="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-pairwise-scenarier-output-1.svg" class="img-fluid figure-img" data-ref-parent="fig-pairwise-scenarier"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-pairwise-scenarier-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Pairwise posterior for (theta0, theta1) under tre migrationsscenarier. Ved lav migration er posterioren bred og negativt korreleret — parametrene er konfunderede. Ved høj migration er theta0 præcist estimeret mens theta1 har stor usikkerhed. Den lyserrøde linje markerer sande parameterværdier.
</figcaption>
</figure>
</div>
</div>
<div id="fig-pairwise-scenarier-2" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-pairwise-scenarier-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<pre><code>&lt;Figure size 900x400 with 0 Axes&gt;</code></pre>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-pairwise-scenarier-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b)
</figcaption>
</figure>
</div>
<div class="cell-output cell-output-display">
<div id="fig-pairwise-scenarier-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-pairwise-scenarier-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-pairwise-scenarier-output-3.svg" class="lightbox" data-gallery="fig-pairwise-scenarier" title="Figure&nbsp;23&nbsp;(c): "><img src="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-pairwise-scenarier-output-3.svg" id="fig-pairwise-scenarier-3" class="img-fluid figure-img" data-ref-parent="fig-pairwise-scenarier"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-pairwise-scenarier-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c)
</figcaption>
</figure>
</div>
</div>
<div id="fig-pairwise-scenarier-4" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-pairwise-scenarier-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<pre><code>&lt;Figure size 900x400 with 0 Axes&gt;</code></pre>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-pairwise-scenarier-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d)
</figcaption>
</figure>
</div>
<div class="cell-output cell-output-display">
<div id="fig-pairwise-scenarier-5" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-pairwise-scenarier-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-pairwise-scenarier-output-5.svg" class="lightbox" data-gallery="fig-pairwise-scenarier" title="Figure&nbsp;23&nbsp;(e): "><img src="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-pairwise-scenarier-output-5.svg" id="fig-pairwise-scenarier-5" class="img-fluid figure-img" data-ref-parent="fig-pairwise-scenarier"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-pairwise-scenarier-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e)
</figcaption>
</figure>
</div>
</div>
<div id="fig-pairwise-scenarier-6" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-pairwise-scenarier-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<pre><code>&lt;Figure size 900x400 with 0 Axes&gt;</code></pre>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-pairwise-scenarier-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(f)
</figcaption>
</figure>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-pairwise-scenarier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;23
</figcaption>
</figure>
</div>
</div>
</div>
<p>MoM-estimater for <span class="math inline">\(\theta_1\)</span> er ustabile ved <span class="math inline">\(N_\text{obs} \leq 1000\)</span> — ved <span class="math inline">\(N_\text{obs} = 300\)</span> estimeres <span class="math inline">\(\hat{\theta}_1 = 3{,}92\)</span> frem for sand <span class="math inline">\(1{,}0\)</span> — mens SVGD-posterior-mean er konsekvent tættere på sandhed og standardafvigelsen afspejler den reelle estimationsusikkerhed. For den asymmetriske model reducerer <span class="math inline">\(n=4\)</span> bias til under 5% for begge rater: <span class="math inline">\(\hat{m}_{12} = 2{,}015 \pm 0{,}627\)</span> og <span class="math inline">\(\hat{m}_{21} = 0{,}285 \pm 0{,}039\)</span>, og asymmetriforholdet <span class="math inline">\(m_{12}/m_{21}\)</span> er identificerbart. SFS under 3-epoch model viser kraftigt overskud af singletons — det klassiske demografiske ekspansionssignal der afspejler at den nuværende lille population giver mange korte eksterne grene mens de store historiske populationer bidrager minimalt til høje frekvensklasser.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/03_svgd_two_island.ipynb" data-notebook-title="Notebook 3: Identifiability og inferens i to-ø modellen" data-notebook-cellid="cell-fig-mom-vs-svgd">
<div id="cell-fig-mom-vs-svgd" class="cell">
<div class="cell-output cell-output-display">
<div id="fig-mom-vs-svgd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mom-vs-svgd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-mom-vs-svgd-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-28" title="Figure&nbsp;24: MoM vs.&nbsp;SVGD som funktion af prøvestørrelse for theta0 og theta1 (sand theta=[0.7, 1.0]). MoM-estimatet for theta1 er ustabilt ved n<1000 med estimat på 3.92 ved n=300. SVGD-posterior-mean er konsekvent tættere på sandhed og giver desuden usikkerhedskvantificering via posterior-std."><img src="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-mom-vs-svgd-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mom-vs-svgd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24: MoM vs.&nbsp;SVGD som funktion af prøvestørrelse for theta0 og theta1 (sand theta=[0.7, 1.0]). MoM-estimatet for theta1 er ustabilt ved n&lt;1000 med estimat på 3.92 ved n=300. SVGD-posterior-mean er konsekvent tættere på sandhed og giver desuden usikkerhedskvantificering via posterior-std.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/03_svgd_two_island.ipynb" data-notebook-title="Notebook 3: Identifiability og inferens i to-ø modellen" data-notebook-cellid="cell-fig-asym4-pairwise">
<div id="cell-fig-asym4-pairwise" class="cell">
<div class="cell-output cell-output-display">
<div id="fig-asym4-pairwise" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-asym4-pairwise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-asym4-pairwise-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-29" title="Figure&nbsp;25: Pairwise posterior for asymmetrisk to-ø model med n=4. m12=2.015 pm 0.627 (sand 2.0) og m21=0.285 pm 0.039 (sand 0.3) begge rater er identificerbare med bias under 5%. Ved n=2 var de to migrationsretninger slet ikke adskillelige. n=4 er derfor minimumet for asymmetrisk migrationsanalyse."><img src="index_files/figure-html/..-notebooks-03_svgd_two_island-fig-asym4-pairwise-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-asym4-pairwise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;25: Pairwise posterior for asymmetrisk to-ø model med n=4. m12=2.015 pm 0.627 (sand 2.0) og m21=0.285 pm 0.039 (sand 0.3) begge rater er identificerbare med bias under 5%. Ved n=2 var de to migrationsretninger slet ikke adskillelige. n=4 er derfor minimumet for asymmetrisk migrationsanalyse.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/05_time_inhomogeneous.ipynb" data-notebook-title="Notebook 5: Tidsinhomogen coalescent og inferens" data-notebook-cellid="cell-fig-sfs-epoch">
<div id="cell-fig-sfs-epoch" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-sfs-epoch" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sfs-epoch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-sfs-epoch-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-30" title="Figure&nbsp;26: SFS under 3-epoch model med n=10 og N_e=[1, 5, 10]. Singletons dominerer kraftigt fordi den nuværende lille population (N_e=1) giver mange korte eksterne grene. De store historiske populationer bidrager minimalt til høje frekvensklasser. Mønstret er det klassiske demografiske ekspansionssignal: overskud af singletons og underskud af høje frekvensklasser."><img src="index_files/figure-html/..-notebooks-05_time_inhomogeneous-fig-sfs-epoch-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sfs-epoch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;26: SFS under 3-epoch model med n=10 og N_e=[1, 5, 10]. Singletons dominerer kraftigt fordi den nuværende lille population (N_e=1) giver mange korte eksterne grene. De store historiske populationer bidrager minimalt til høje frekvensklasser. Mønstret er det klassiske demografiske ekspansionssignal: overskud af singletons og underskud af høje frekvensklasser.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="joint-probability-inferens-informationsindhold-og-grænser" class="level2">
<h2 class="anchored" data-anchor-id="joint-probability-inferens-informationsindhold-og-grænser">Joint probability-inferens: informationsindhold og grænser</h2>
<p>TMRCA-inferens giver konsekvent lavere posterior-std end joint SFS-inferens ved mu=1.0 og limit=3 — joint er ikke bedre end TMRCA under disse betingelser. To forklaringer er mulige: SVGD udnytter ikke joint-tabellets kovariansstruktur optimalt med 300 iterationer, og sammenligningen er ikke fuldt retfærdig fordi TMRCA bruger kontinuerte observationer mens joint bruger diskrete kategorier med begrænset opløsning. Begge metoder konvergerer mod sand <span class="math inline">\(\theta = 7\)</span> ved <span class="math inline">\(n_\text{obs} = 3000\)</span>, og TMRCA er konsekvent mere præcis ved <span class="math inline">\(n &lt; 1000\)</span>.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/06_joint_probability_inferens.ipynb" data-notebook-title="Notebook 6: Inferens via joint sandsynligheder og diskrete SFS-observationer" data-notebook-cellid="cell-fig-joint-vs-tmrca">
<div id="cell-fig-joint-vs-tmrca" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div id="fig-joint-vs-tmrca" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-joint-vs-tmrca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-joint-vs-tmrca-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-31" title="Figure&nbsp;27: Posterior mean og std for joint SFS vs.&nbsp;TMRCA-inferens over theta i {2, 5, 10, 20} med mu=1.0 og N_obs=1000. TMRCA-inferens giver konsekvent lavere posterior-std end joint SFS ved disse parametre. Joint SFS er ikke bedre end TMRCA ved mu=1.0 og tot_reward_limit=3."><img src="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-joint-vs-tmrca-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-joint-vs-tmrca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;27: Posterior mean og std for joint SFS vs.&nbsp;TMRCA-inferens over theta i {2, 5, 10, 20} med mu=1.0 og N_obs=1000. TMRCA-inferens giver konsekvent lavere posterior-std end joint SFS ved disse parametre. Joint SFS er ikke bedre end TMRCA ved mu=1.0 og tot_reward_limit=3.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Fortolkning:
 theta=2.0: TMRCA bedre (gevinst=-153.8procent)
 theta=5.0: TMRCA bedre (gevinst=-215.0procent)
 theta=10.0: TMRCA bedre (gevinst=-93.3procent)
 theta=20.0: TMRCA bedre (gevinst=-2.5procent)</code></pre>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/06_joint_probability_inferens.ipynb" data-notebook-title="Notebook 6: Inferens via joint sandsynligheder og diskrete SFS-observationer" data-notebook-cellid="cell-fig-ss-joint">
<div id="cell-fig-ss-joint" class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>n= 3000: Joint=6.981+/-0.1544  TMRCA=6.978+/-0.1405

   n  Joint mean  Joint std  TMRCA mean  TMRCA std  Indeholder sand (J)  Indeholder sand (T)
  50       8.149     0.7369       7.601     0.2949                 True                False
 100       6.998     0.4883       6.276     0.2479                 True                False
 250       9.003     0.2777       7.122     0.1602                False                 True
 500       7.668     0.3034       6.946     0.0797                False                 True
1000       7.544     0.1587       7.056     0.1148                False                 True
3000       6.981     0.1544       6.978     0.1405                 True                 True</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-ss-joint" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ss-joint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-ss-joint-output-2.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-32" title="Figure&nbsp;28: Joint SFS vs.&nbsp;TMRCA-inferens som funktion af prøvestørrelse n for sand theta=7. Begge metoder konvergerer mod sand theta ved n=3000. TMRCA er konsekvent mere præcis ved n under 1000. Joint indeholder sand theta i 3 af 6 stikprøvestørrelser mod TMRCA 3 af 6."><img src="index_files/figure-html/..-notebooks-06_joint_probability_inferens-fig-ss-joint-output-2.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ss-joint-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;28: Joint SFS vs.&nbsp;TMRCA-inferens som funktion af prøvestørrelse n for sand theta=7. Begge metoder konvergerer mod sand theta ved n=3000. TMRCA er konsekvent mere præcis ved n under 1000. Joint indeholder sand theta i 3 af 6 stikprøvestørrelser mod TMRCA 3 af 6.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Multi-feature SFS giver gevinst ved <span class="math inline">\(\theta = 5\)</span> (15,8%) og <span class="math inline">\(\theta = 10\)</span> (46,6%) men ikke ved <span class="math inline">\(\theta = 2\)</span> eller <span class="math inline">\(\theta = 20\)</span>, og samlede branch length er det sikreste valg ved moderate theta-værdier da gradient-estimaterne er ustabile ved <span class="math inline">\(N_\text{obs} = 2000\)</span>. Forkert <span class="math inline">\(\mu\)</span> giver systematisk bias der ikke forsvinder med større <span class="math inline">\(n\)</span>: faktor 2 fejl i <span class="math inline">\(\mu\)</span> giver faktor 2–3 fejl i <span class="math inline">\(\theta\)</span>-estimatet, og dette motiverer en sensitivitetsanalyse over <span class="math inline">\(\mu\)</span> i bavian-analysen.</p>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/06_joint_probability_inferens.ipynb" data-notebook-title="Notebook 6: Inferens via joint sandsynligheder og diskrete SFS-observationer" data-notebook-cellid="cell-tbl-multifeature-gain">
<div class="cell" data-execution_count="14">
<div id="tbl-multifeature-gain" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="14">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-multifeature-gain-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;16: Gevinst ved multi-feature SFS vs.&nbsp;TMRCA som funktion af theta med N_obs=2000 og Adam(0.1). Multi-feature giver gevinst ved theta=5 (15.8%) og theta=10 (46.6%) men ikke ved theta=2 eller theta=20. Samlede grenlængde er det sikreste valg ved moderate theta-værdier.
</figcaption>
<div aria-describedby="tbl-multifeature-gain-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">theta</th>
<th data-quarto-table-cell-role="th">std TMRCA</th>
<th data-quarto-table-cell-role="th">std Multi</th>
<th data-quarto-table-cell-role="th">Gevinst (procent)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>2</td>
<td>0.04293</td>
<td>0.03867</td>
<td>9.9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>0.05094</td>
<td>0.03019</td>
<td>40.7</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>10</td>
<td>0.79824</td>
<td>1.40187</td>
<td>-75.6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>20</td>
<td>3.08604</td>
<td>2.20376</td>
<td>28.6</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
<div class="quarto-embed-nb-cell" data-notebook="/Users/runner/work/emma-giraf/emma-giraf/notebooks/06_joint_probability_inferens.ipynb" data-notebook-title="Notebook 6: Inferens via joint sandsynligheder og diskrete SFS-observationer" data-notebook-cellid="cell-tbl-mu-bias">
<div class="cell" data-execution_count="16">
<div id="tbl-mu-bias" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="16">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mu-bias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;17: Systematisk bias ved forkert mutationsrate mu i joint-inferens (sand theta=7.0, sand mu=1.0, N_obs=2000). Faktor 2 fejl i mu giver faktor 2-3 fejl i theta-estimatet. Biasset er systematisk og forsvinder ikke med større n.&nbsp;Motiverer sensitivitetsanalyse over mu i bavian-analysen.
</figcaption>
<div aria-describedby="tbl-mu-bias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mu_sand</th>
<th data-quarto-table-cell-role="th">mu_fittet</th>
<th data-quarto-table-cell-role="th">theta_mean</th>
<th data-quarto-table-cell-role="th">theta_std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1.0</td>
<td>0.3</td>
<td>1.3126</td>
<td>1.98379</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1.0</td>
<td>0.7</td>
<td>3.6857</td>
<td>0.65701</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>1.0</td>
<td>1.0</td>
<td>7.6054</td>
<td>0.40737</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1.0</td>
<td>1.5</td>
<td>14.6980</td>
<td>0.69996</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1.0</td>
<td>2.5</td>
<td>31.0460</td>
<td>6.11843</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="diskussion" class="level1">
<h1>Diskussion</h1>
</section>
<section id="konklusion" class="level1">
<h1>Konklusion</h1>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Ackermann2014" class="csl-entry" role="listitem">
Ackermann, Rebecca R., Lauren Schroeder, Jeffrey Rogers, and James M. Cheverud. 2014. <span>“Further Evidence for Phenotypic Signatures of Hybridization in Descendant Baboon Populations.”</span> <em>Journal of Human Evolution</em> 76: 54–62. https://doi.org/<a href="https://doi.org/10.1016/j.jhevol.2014.05.004https://doi.org/10.1016/j.jhevol.2014.05.004">https://doi.org/10.1016/j.jhevol.2014.05.004https://doi.org/10.1016/j.jhevol.2014.05.004</a>.
</div>
<div id="ref-BladtNielsen2017" class="csl-entry" role="listitem">
Bladt, Mogens, and Bo Friis Nielsen. 2017. <em>Matrix-Exponential Distributions in Applied Probability</em>. Vol. 81. Probability Theory and Stochastic Modelling. Springer. <a href="https://doi.org/10.1007/978-1-4939-7049-0">https://doi.org/10.1007/978-1-4939-7049-0</a>.
</div>
<div id="ref-fogel2021" class="csl-entry" role="listitem">
Fogel, Arielle S., Emily M. McLean, Jacob B. Gordon, Elizabeth A. Archie, Jenny Tung, and Susan C. Alberts. 2021. <span>“Genetic Ancestry Predicts Male-Female Affiliation in a Natural Baboon Hybrid Zone.”</span> <em>Animal Behaviour</em> 180: 249–68. <a href="https://doi.org/10.1016/j.anbehav.2021.07.009">https://doi.org/10.1016/j.anbehav.2021.07.009</a>.
</div>
<div id="ref-hobolth2021" class="csl-entry" role="listitem">
Hobolth, Asger, Mogens Bladt, and Lars Nørvang Andersen. 2021. <span>“Multivariate Phase-Type Theory for the Site Frequency Spectrum.”</span> <em>Preprint / arXiv</em>, ahead of print. https://doi.org/<a href="https://doi.org/10.48550/arXiv.2101.04941">https://doi.org/10.48550/arXiv.2101.04941</a>.
</div>
<div id="ref-Hobolth2024" class="csl-entry" role="listitem">
Hobolth, Asger, Iker Rivas-González, Mogens Bladt, and Andreas Futschik. 2024. <span>“Phase-Type Distributions in Mathematical Population Genetics: An Emerging Framework.”</span> <em>Theoretical Population Biology</em> 157: 14–32. https://doi.org/<a href="https://doi.org/10.1016/j.tpb.2024.03.001">https://doi.org/10.1016/j.tpb.2024.03.001</a>.
</div>
<div id="ref-Hobolth2018" class="csl-entry" role="listitem">
Hobolth, Asger, Arno Siri-Jegousse, and Mogens Bladt. 2018. <span>“Phase-Type Distributions in Population Genetics.”</span> <em>arXiv Preprint arXiv:1806.01416</em>, ahead of print. https://doi.org/<a href="https://doi.org/10.1016/j.tpb.2019.02.001">https://doi.org/10.1016/j.tpb.2019.02.001</a>.
</div>
<div id="ref-hobolth2019" class="csl-entry" role="listitem">
Hobolth, Asger, Arno Siri-Jégousse, and Mogens Bladt. 2019. <em>Lecture Notes: Phase-Type Distributions in Population Genetics</em>.
</div>
<div id="ref-jordan2018papio" class="csl-entry" role="listitem">
<span class="nocase">Jordan, Vallmer E., Jerilyn A. Walker, Thomas O. Beckstrom, Cody J. Steely, Cullen L. McDaniel, et al.</span> 2018. <span>“A Computational Reconstruction of Papio Phylogeny Using Alu Insertion Polymorphisms.”</span> <em>Mobile DNA</em> 9: 13. <a href="https://doi.org/10.1186/s13100-018-0118-3">https://doi.org/10.1186/s13100-018-0118-3</a>.
</div>
<div id="ref-kelleher2019" class="csl-entry" role="listitem">
Kelleher, Jerome, Yan Wong, Anthony W. Wohns, Chaimaa Fadil, Patrick K. Albers, and Gil McVean. 2019. <span>“Inferring Whole-Genome Histories in Large Population Datasets.”</span> <em>Nature Genetics</em>, ahead of print. <a href="https://doi.org/10.1038/s41588-019-0483-y">https://doi.org/10.1038/s41588-019-0483-y</a>.
</div>
<div id="ref-kemeny1976" class="csl-entry" role="listitem">
Kemeny, John G., and J. Laurie Snell. 1976. <em>Finite Markov Chains</em>. Springer.
</div>
<div id="ref-Kingman1982" class="csl-entry" role="listitem">
Kingman, John F. C. 1982. <span>“The Coalescent.”</span> <em>Stochastic Processes and Their Applications</em> 13 (3): 235–48. <a href="https://doi.org/10.1016/0304-4149(82)90011-4">https://doi.org/10.1016/0304-4149(82)90011-4</a>.
</div>
<div id="ref-kopp2023" class="csl-entry" role="listitem">
Kopp, Gisela H., Riashna Sithaldeen, Franziska Trede, Franziska Grathwol, Christian Roos, and Dietmar Zinner. 2023. <span>“A Comprehensive Overview of Baboon Phylogenetic History.”</span> <em>Genes</em> 14: 614. <a href="https://doi.org/10.3390/genes14030614">https://doi.org/10.3390/genes14030614</a>.
</div>
<div id="ref-liu2016svgd" class="csl-entry" role="listitem">
Liu, Qiang, and Dilin Wang. 2016. <span>“Stein Variational Gradient Descent: A General Purpose Bayesian Inference Algorithm.”</span> <em>Advances in Neural Information Processing Systems</em> 29. <a href="https://arxiv.org/abs/1608.04471">https://arxiv.org/abs/1608.04471</a>.
</div>
<div id="ref-phasic" class="csl-entry" role="listitem">
Munch, Kasper. 2026. <em>Phasic: A Library for Modelling and Inference on Markov Jump Processes</em>. V. latest. Released. <a href="https://munch-group.org/phasic/">https://munch-group.org/phasic/</a>.
</div>
<div id="ref-Neuts1981" class="csl-entry" role="listitem">
Neuts, Marcel F. 1981. <em>Matrix-Geometric Solutions in Stochastic Models: An Algorithmic Approach</em>. Johns Hopkins University Press.
</div>
<div id="ref-rogers2019" class="csl-entry" role="listitem">
<span class="nocase">Rogers, Jeffrey, Muthuswamy Raveendran, et al.</span> 2019. <span>“The Comparative Genomics and Complex Population History of Papio Baboons.”</span> <em>Science Advances</em> 5 (1): eaau6947. <a href="https://doi.org/10.1126/sciadv.aau6947">https://doi.org/10.1126/sciadv.aau6947</a>.
</div>
<div id="ref-Roikjer2022" class="csl-entry" role="listitem">
Røikjer, Tobias, Asger Hobolth, and Kasper Munch. 2022. <span>“Graph-Based Algorithms for Phase-Type Distributions.”</span> <em>Statistics and Computing</em> 32: 103. <a href="https://doi.org/10.1007/s11222-022-10174-3">https://doi.org/10.1007/s11222-022-10174-3</a>.
</div>
<div id="ref-sorensen2023" class="csl-entry" role="listitem">
<span class="nocase">Sørensen, Erik F. et al.</span> 2023. <span>“Genome-Wide Coancestry Reveals Details of Ancient and Recent Male-Driven Reticulation in Baboons.”</span> <em>Science</em> 380: eabn8153. <a href="https://doi.org/10.1126/science.abn8153">https://doi.org/10.1126/science.abn8153</a>.
</div>
<div id="ref-sorensen2023_selection" class="csl-entry" role="listitem">
Sørensen, Erik Fogh, Garrett Hellenthal, and Kasper Munch. 2023. <span>“Negative Selection on Baboon Admixture Is Strongest on Chromosome x.”</span> <em>bioRxiv / Preprint</em>, ahead of print. https://doi.org/<a href="https://doi.org/10.1101/2024.12.18.629079">https://doi.org/10.1101/2024.12.18.629079</a>.
</div>
<div id="ref-spence2018" class="csl-entry" role="listitem">
Spence, Jeffrey P., Matthias Steinrücken, Jonathan Terhorst, and Yun S. Song. 2018. <span>“Inference of Population History Using Coalescent HMMs: Review and Outlook.”</span> <em>arXiv Preprint arXiv:1807.02763</em>, ahead of print. https://doi.org/<a href="https://doi.org/10.1016/j.gde.2018.07.002">https://doi.org/10.1016/j.gde.2018.07.002</a>.
</div>
<div id="ref-vilgalys2022" class="csl-entry" role="listitem">
<span class="nocase">Vilgalys, Tauras P., Arielle S. Fogel, Jordan A. Anderson, et al.</span> 2022. <span>“Selection Against Admixture and Gene Regulatory Divergence in a Long-Term Primate Field Study.”</span> <em>Science</em> 377 (6606): 635–41. <a href="https://doi.org/10.1126/science.abm4917">https://doi.org/10.1126/science.abm4917</a>.
</div>
<div id="ref-wakeley2009coalescent" class="csl-entry" role="listitem">
Wakeley, John. 2009. <em>Coalescent Theory: An Introduction</em>. Roberts &amp; Company Publishers.
</div>
</div>
</section>
<section id="appendiks" class="level1">
<h1>Appendiks</h1>
<section id="data-availability" class="level2">
<h2 class="anchored" data-anchor-id="data-availability">Data Availability</h2>
<p>Alle notebooks, kode og resultater til dette speciale er tilgængelige på GitHub. Analyserne er fuldt reproducerbare via <em>phasic</em>-biblioteket og de otte Jupyter notebooks der er navngivet kronologisk og kører sekventielt.</p>
</section>
<section id="brug-af-generativ-kunstig-intelligens" class="level2">
<h2 class="anchored" data-anchor-id="brug-af-generativ-kunstig-intelligens">Brug af Generativ Kunstig Intelligens</h2>
<p>I overensstemmelse med Aarhus Universitets retningslinjer oplyser jeg hermed min brug af AI-værktøjer under udarbejdelsen af dette speciale. Alle analyser, fortolkninger og videnskabelige bidrag er mine egne. <strong>Claude (Anthropic)</strong> blev brugt til kodereview, fejlsøgning i Python-notebooks og strukturering af Quarto-dokumentet.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>